deploy/lib/parca-agent/parca-agent.libsonnet
This mount is unnecessary, it was left over from debugging.
Closes https://github.com/parca-dev/parca/issues/346
=> deploy: Remove localtime mount

pkg/agent/profile.go, pkg/perf/perf.go, pkg/perf/perf_test.go
Untested but hopefully good enough to get some early comments. We need some follow-up to make this work (and safe) for containerized workloads (mount_namespace, pid_namespace).
=> Parse Linux perf's map and try to symbolize

deploy/lib/parca-agent/parca-agent.libsonnet
Fixes #115
List of changes:
- Removed mount for `/` directory and removed access in PSP
- Removed mount for `/proc` directory as it is not needed due to `hostPID: true` setting
- Removed access to `/etc` directory in PSP
- Made root FS in container read-only to increase the security aspect of a highly privileged pod.
=> deploy/lib: remove unnecessary mounts

README.md, cmd/parca-agent/main.go, pkg/agent/systemdmanager.go
My system.slice on OpenSUSE tumbleweed seems to be at a different place. Also don't fail to render the status page when a unit can not be resolved.
=> systemd: Deal with non-resolvable units and slice locations

pkg/perf/perf.go, pkg/perf/perf_test.go
Closes https://github.com/parca-dev/parca-agent/issues/129
Test image available at: `ghcr.io/parca-dev/parca-agent:v0.2.0-45-gdfa59a1`
=> pkg/perf: Discover namespace PID for perf map support in containers

pkg/perf/perf.go, pkg/perf/perf_test.go, pkg/perf/testdata/nodejs-perf-map, pkg/perf/testdata/proc-status
=> pkg/perf: Allow memory address strings to have the 0x prefix

Makefile
Similar to https://github.com/parca-dev/parca/pull/494 the default shell
in Make in `/bin/sh` which does not implement `source`. Specify
`/bin/bash` specfically which does implement that command.
=> *: Add explicit shell to Makefile

Makefile
The test target requires that the parca-agent.bpf.o file has been
created. Make this easier by making it a dependency so it is
automatically built if not already before running the tests.
=> *: Add bpf as a dependency for test target

go.mod, go.sum, pkg/discovery/systemd.go
With cgroup v2 the perf_events controller is implicitly enabled so we
don't have to do anything manually from the perspective of the
parca-agent.
Fixes #23
=> pkg/discovery: Support cgroupv2

cmd/debug-info/main.go, pkg/agent/profile.go, pkg/debuginfo/debuginfo.go
With this PR we check all the debug sections and only remove them if they do not have any bits. This clean up was introduced in https://github.com/parca-dev/parca-agent/pull/102 for another special case for Go binaries where we had  `.debug_gdb_scripts` section without any bits.
I hope the PR will be a solution for both.
Fixes https://github.com/parca-dev/parca-agent/issues/185
cc @derekparker
=> debug-info: Make sure it is safe to remove the section

cmd/parca-agent/main.go, pkg/discovery/systemd.go, pkg/discovery/systemd_test.go
This patch wires up the --systemd-cgroup-path flag and actually plumbs
the user provided value into the systemd config and subsequently into
the systemd discoverer to be used when trying to reconcile unit files.
Fixes #192
=> pkg/discovery: take user provided systemd cgroup path into account

cmd/parca-agent/main.go, go.mod, go.sum, pkg/debuginfo/debuginfo.go
Used https://github.com/containerd/containerd/blob/main/sys/reaper/reaper_unix.go
Could be a mitigation for https://github.com/parca-dev/parca-agent/issues/184
cc @derekparker
=> debug-info: Use child process reaper for more reliable external command execution

README.md, cmd/parca-agent/main.go
There was a previous commit which wired up this flag throughout the
codebase, however that code didn't take into account that this flag
has a default parameter. Remove the default and let the user set it
if it's really necessary.
=> Remove default systemd cgroup path

pkg/containerutils/containerd/containerd.go, pkg/k8s/k8s.go
Previously the k3s containerd socket had to be explicitly configured,
however, similar to the standard Kubernetes containerd configuration k3s
has a (different) standard location as well. In order to not force users
to make special changes for k3s, this patch automatically attempts
discovering the k3s path as well.
=> pkg/containerutils/containerd: Automatically discover k3s containerd

pkg/agent/write_client.go
We have unintentionally built a retry mechanism in our request batching code, that will indefinitely retry if an error occurs. Before this patch whenever a batch fails to send, we will not reset the batch, so we will indefinitely retry the current batch if it continues to error. If a batch causes an out of order insert on the server-side for example, then this will retry forever,
since this will never not be out of order.
=> pkg/agent: Fix accidental infinite retry

.github/dependabot.yaml
Parca libbpf version tight to libbpf-go right now, so it needs to be upgraded together. 
libbpf-go version https://github.com/parca-dev/parca-agent/blob/433779305d362e617d587fed7a73ce3e7ab32740/go.mod#L7
https://github.com/libbpf/libbpf/commits/v0.6.1
=> Pin libbpf version

scripts/local-dev.sh
At least some people should be able to run the script as is, with 4 cores and 16GiB memory.
=> Set minikube resources slightly more reasonable

pkg/profiler/profiler.go
=> pkg/profiler: hack to fix double-registration  panic

.github/workflows/container.yml, Dockerfile, Makefile, make-containers.sh
=> Add multiarch container builds

pkg/maps/maps.go
This should prevent trying to access the root symlink because the m.File is empty.
```
level=warn ts=2022-03-02T15:50:14.508461455Z caller=maps.go:102 msg="failed to read obj build ID" obj=/proc/12497/root err="failed to open elf: read /proc/12497/root: is a directory"
``` 
(Hopefully)
Fixes: #82
=> pkg/maps: Skip more pseudo-paths and anonymous mappings 

Makefile
Should fix
```
Run make push-container
podman manifest push ghcr.io/parca-dev/parca-agent:main-1110c48a
Error: accepts 2 arg(s), received 1
make: *** [Makefile:212: push-container] Error 125
Error: Process completed with exit code 2.
```
https://github.com/parca-dev/parca-agent/runs/5393544962?check_suite_focus=true
=> Makefile: Fix pushing container manifests

pkg/containerutils/containerutils.go
Before this commit, we only supported discovering cgroups via systemd by
reading /proc/$PID/cgroup:
```
[...]
1:name=systemd:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
[...]
```
On systems running openrc for instance, that line doesn't exist. Instead
we have:
```
1:name=openrc:/docker
```
With this, parca-agent would discover the __cgroup_path__ for the job to
be `/sys/fs/cgroup/perf_event`, leading to parca-agent profiling
everything for every pod.
This commit adds logic to support discovering the cgroup via perf_event.
If the system is running systemd, it'll always fall back to using that
line as it is the second from the last.
Fixes #268
=> discovery: Support systems without systemd

pkg/objectfile/cache.go
For position independent shared libraries, the computed base differs for each process, so cache them separately.
=> objectfile: Fix object file cache key issue

pkg/debuginfo/debuginfo.go, pkg/debuginfo/extract.go
Previous order:
1) Check the binary itself for debug info
a) Check symtab + dynsym
b) Check DWARF 
c) Check gopclntab
2) Check /usr/lib/debug
New order:
1) Check /usr/lib/debug
2) Check the binary itself for debug info
a) Check DWARF
b) Check gopclntab
c) Check symtab + dynsym
If we already have it locally downloaded, no need to try to process running binary. Besides, we try to extract (c) symtab/dynsym as a last resort, which we don't have a corresponding code in server (yet).
=> debuginfo: Change the order of debuginfo file discovery

pkg/discovery/kubernetes.go
Modify the kubernetes service discovery mechanism to expose shared labels from application metadata as well. 
=> pkg/discovery: Expose shared labels

pkg/discovery/kubernetes.go
Take two ...
Turns out in #318 I incorrectly sanitized the label-values not the label-names. Label values can be anything, they do not have to be sanitized.
=> discovery: Sanitize Kubernetes label names

parca-agent.bpf.c
`struct bpf_map_def` is deprecated in libbpf. So let's use BTF enabled definitions instead.
Fixes #294 
=> eBPF: Remove the use of deprecated bpf_map_def

pkg/profiler/profiler.go
Use a buffer pool for write profiles to reduce redundant allocations
cc @Sylfrena @v-thakkar @javierhonduco
=> profiler: Use a buffer pool for write profiles

go.mod, pkg/profiler/profiler.go
Until we have the following feature lands in the libbpf, we need a way to increase rlimit. libbpf-go sets it to 512MB when the module loaded, however I always hits this limit whenever I change something regarding BPF maps so, I'm introducing a way to increase it and also by default this Pr increases that limit to 1024MB.
Check out rlimits if you ever encounter `operation not permitted` error.
cc @javierhonduco @v-thakkar @Sylfrena
=> profiler: Increase rlimit

parca-agent.bpf.c
The BPF metadata feature [see commit](https://github.com/torvalds/linux/commit/ffa915f46193b6be780483c8d31cc53f093f6d9a) allows
to define variables that start with the `bpf_metadata_` prefix that can be read with
several tools, including `bpftool`:
```
$ sudo bpftool prog | grep perf -A20
1832: perf_event  name do_sample  tag 6ce6efa2110df18f  gpl
loaded_at 2022-04-13T08:15:16-0700  uid 0
xlated 416B  jited 432B  memlock 4096B  map_ids 3489,3490,3492
btf_id 1409
pids parca_agent_by_(470302)
metadata:
name = "parca-agent (https://github.com/parca-dev/parca-agent)"
version = "v0.7.0"
```
By exposing a name for our BPF program, as well as the version[1], we can quickly find out
which exact program and version of the BPF code we are running.
Under the hood, they are backed by an BPF array: …
=> bpf: Add some basic metadata

parca-agent.bpf.c, pkg/profiler/profiler.go, scripts/local-run.sh
As a pre-work to #346, add metrics to keep track of stack unwinding failures.
cc @v-thakkar
=> profiler: Keep track of stack unwinding failures

Makefile
Spotted this as running `make` is very slow on my network-attached
disk and found that it's due to `go list ./...` taking a couple of
seconds in the worst in case in my machine.
I really need to optimise my setup, but let's remove this variable
as it's unused anyways :D
```
$ time make aaaa
make: *** No rule to make target 'aaaa'.  Stop.
real	0m1.394s
user	0m0.521s
sys	0m0.517s
```
```
$ time make aaaa
make: *** No rule to make target 'aaaa'.  Stop.
real	0m0.304s
user	0m0.031s
sys	0m0.050s
```
=> Makefile: remove unused `GOPKGS` variable

.goreleaser.yml, cmd/parca-agent/main.go, pkg/buildinfo/buildinfo.go
This commit adds some small wrapper to gather the Go build
information we care about and shows some of these values
during the initialisation of the agent.
Having this information is useful to understand the precise
version that people run.
Now it shows both the commit and the date when it was built
as well as the architecture:
```
$ sudo dist/parca-agent --node=test --systemd-units=docker.service --log-level=debug --kubernetes=false --insecure
ts=2022-04-13T11:38:14.915638561Z caller=main.go:119 msg=starting... node=test store=
level=debug ts=2022-04-13T11:38:14.915780145Z caller=main.go:120 msg="parca-agent initialized" version= commit=d7870a66fa1aa31a9555ba9bb66a6574a5898a17 date=2022-04-13T11:36:50Z builtBy= config="{debug :7071 test map[]    true 10s false 1 false  [docker.service] …
```
=> Add Golang build information

Dockerfile, pkg/ksym/ksym.go, pkg/profiler/profiler.go
* Split profileLoop into semantically sound functions
* Use binary.Read to ready BPF keys to Go structs
* Add recovery mechanism to profileLoop for unexpected panics
* Handle known errors
=> profiler: Refactor profileLoop for more readability 

pkg/profiler/profiler.go
```
panic: runtime error: index out of range [0] with length 0
goroutine 82 [running]:
github.com/parca-dev/parca-agent/pkg/profiler.(*CgroupProfiler).writeProfile(0x2040000bb8c0, {0x2790780, 0x204000846120}, 0x3f3d360?)
github.com/parca-dev/parca-agent/pkg/profiler/profiler.go:772 +0xa24
github.com/parca-dev/parca-agent/pkg/profiler.(*CgroupProfiler).profileLoop(0x2040000bb8c0, {0x2790780, 0x204000846120}, {0x0?, 0x23f4010?, 0x3f0bb80?})
github.com/parca-dev/parca-agent/pkg/profiler/profiler.go:521 +0xe44
github.com/parca-dev/parca-agent/pkg/profiler.(*CgroupProfiler).Run(0x2040000bb8c0, {0x2790780, 0x20400080fe00})
github.com/parca-dev/parca-agent/pkg/profiler/profiler.go:377 +0xe40
github.com/parca-dev/parca-agent/pkg/target.(*ProfilerPool).Sync.func1() …
```
=> profiler: Fix index out of range

pkg/debuginfo/extract.go
We are not removing the `debuginfo.stripped` object file:
```
level=debug ts=2022-04-25T15:28:01.4489913Z caller=extract.go:152 component=debuginfo component=extractor msg="running external binary utility command" cmd="eu-strip --strip-debug -f /tmp/9479b311aa7cd2529685da47d4f6e855734db786.debuginfo -o /tmp/9479b311aa7cd2529685da47d4f6e855734db786.debuginfo.stripped /proc/1037819/root/app/parca-demo"
level=warn ts=2022-04-25T15:28:01.45394735Z caller=extract.go:125 component=debuginfo component=extractor msg="failed to remove temporary file" file=9479b311aa7cd2529685da47d4f6e855734db786.stripped err="remove 9479b311aa7cd2529685da47d4f6e855734db786.stripped: no such file or directory"
```
```shell
$ ls /tmp/9479b311aa7cd2529685da47d4f6e855734db786.debuginfo* …
```
=> debuginfo: remove `.debuginfo.stripped` binaries

.gitattributes
So linguist doesn't tally them https://github.com/github/linguist/blob/master/docs/overrides.md
cc/ @kakkoyun
=> .gitattributes: Mark some files as gen / 3rd party

Makefile, go.mod, go.sum, pkg/profiler/profiler_test.go
Ran:
```
$ go get github.com/aquasecurity/libbpfgo@80f44303d40f3e65702de30d4976ada883e79fe2
```
Changes from the version we have until this pinned revision: https://github.com/aquasecurity/libbpfgo/compare/v0.2.5-libbpf-0.7.0...80f44303d40f3e65702de30d4976ada883e79fe2.
This fixes a number of issues that were affecting us, including:
- Batch APIs not collecting partial results https://github.com/aquasecurity/libbpfgo/commit/64458ba5a32013dda2d4f88838dde8456922333d fixed by @kakkoyun 
- Deletion APIs not checking for errors properly, both batch and single key (https://github.com/aquasecurity/libbpfgo/pull/160, tracked in https://github.com/aquasecurity/libbpfgo/issues/159). In the case of batched APIs it resulted in them not working properly rather than returning partial results
- Expose …
=> Bump libbpfgo + add regression tests 

pkg/ksym/ksym.go, pkg/profiler/profiler.go
To help us understand the effectiveness of the Kernel symbolizer cache
**Test plan**
http://localhost:7071/metrics contains
```
parca_agent_profiler_kernel_symbolizer_cache_hit_rate{target="{__cgroup_path__=\"/sys/fs/cgroup/system.slice/docker-0cd1ac1dee8df9859b5dd10b794b38b235ef5745cedfde653896dd09264cf615.scope/\", node=\"test\", systemd_unit=\"docker-0cd1ac1dee8df9859b5dd10b794b38b235ef5745cedfde653896dd09264cf615.scope\"}"} 38.035961272475795
```
=> ksym: Calculate cache hit rate

CONTRIBUTING.md, README.md, cmd/parca-agent/main.go, pkg/discovery/systemd.go, scripts/local-run.sh
The currently named SystemD discovery mechanism is a bit of a misnomer as in reality we
are just dealing with Cgroups.
The Cgroups I have been profiling both in this PR and in other PRs was ran with Docker
or Podman without any issues.
This is the first PR in https://github.com/parca-dev/parca-agent/issues/400
**Test plan**
```
$ GODEBUG=cgocheck=2 make ENABLE_ASAN=yes && sudo dist/parca-agent --node=test --log-level=debug --kubernetes=false --insecure --systemd-units=docker-b8873e261a9fb63e83d3d865a8780066e12e55b2f7eb8f6ac87db0b08444c6a8.scope
mkdir -p dist/parca-agent.bpf
cp $(find parca-agent.bpf.c dist/libbpf/usr/include/bpf 3rdparty/include -type f) dist/parca-agent.bpf
go mod tidy -compat=1.17
find dist -exec touch -t 202101010000.00 {} +
GOOS=linux GOARCH=arm64 CC=clang …
```
=> cmd/parca-agent: SystemD => Cgroup

README.md, bpf/LICENSE
parca-agent BPF code is using GPL-only functions and specifies GPL in
the `license` ELF section. Make it clear also in README.
Signed-off-by: Michal Rostecki <vadorovsky@gmail.com>
=> bpf: License under GPLv2

Dockerfile, Dockerfile.dev, make-containers.sh
- Adds missing dynamic libraries for external commands
- Make sure the development container is closer to the production container
This PR targets the release branch 0.8. After merging this we will release 0.8.1
=> Add dynamic libraries for external commands

cmd/parca-agent/main.go
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>\
Thanks, @javierhonduco for the idea.
cc @v-thakkar 
1. `level=error ts=2022-05-31T15:51:24.74057947Z caller=main.go:178 msg="failed to check whether external dependency is healthy" err="exit status 127" cmd=eu-strip output="eu-strip: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory\n"`
2. `level=error ts=2022-05-31T15:14:27.640210588Z caller=main.go:168 msg="failed to find external dependency in the PATH; make sure it is installed and added to the PATH" cmd=objcopy`
=> Add boot time checks for external dependencies

cmd/parca-agent/main.go, pkg/profiler/profiler.go, pkg/target/profiler_pool.go
Hello there, I am looking at the "good first issues" :wave:
I may be completely wrong, but I am trying to get to know the internals, so it looks like it is simply a matter of measuring `time.Since(captureTime)` in `buildProfile()`, set from here:
https://github.com/parca-dev/parca-agent/blob/4dcd283d602a97325cc2a5371634686196946fb5/pkg/profiler/profiler.go#L390-L391
The exact collection of the samples starting/finishing _slightly_ later/earlier, adding `start := time.Now()` before the BPF Maps loop:
https://github.com/parca-dev/parca-agent/blob/4dcd283d602a97325cc2a5371634686196946fb5/pkg/profiler/profiler.go#L415-L416
And measuring `duration := time.Since(start)` after exiting the loop, then pass it down to `buildProfile()` should also work.
The former is much simpler (1 line change), …
=> fix: set profile duration to real measurement

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docs.yml, .github/workflows/release.yml, Dockerfile, Dockerfile.dev, bpf/Makefile, bpf/README.md, rust-toolchain.toml
I figured we can simplify further, the toolchain can be fully configured from `rust-toolchain.toml`:
https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
And yes, oddly `rustup show` installs the toolchain :upside_down_face:
=> chore: configure entire toolchain in rust-toolchain.toml

CONTRIBUTING.md, shell.nix
This adds a `shell.nix` file to manage the development dependencies, this is my first attempt at using it in project. The idea is to contain as much as possible the dependencies within the repository and avoid spilling on the system or even the user's home.
I added instructions about how to use it in the `CONTRIBUTING.md`, including basics on how to install Nix even though it is out of the scope of `parca-agent`.
It sets a few environment variables to keep things within the repository like Go and Rust binaries, we can add more or remove if that causes troubles.
Once `nix-shell` has been run and with #447 to configure the Rust toolchain, only a couple more commands are needs to build the agent, basically you are ready to work with:
```console
$ nix-shell
[nix-shell:/path/to/parca-agent]$ …
```
=> chore: add shell.nix file for development

bpf/Makefile
Before this change, the arm64 build of bpf-linker was failing with:
```
Could not determine LLVM version from llvm-config.
```
The upstream llvm-sys fix is here:
https://gitlab.com/taricorp/llvm-sys.rs/-/merge_requests/22
Until it gets merged and released, we need to define LLVM_SYS_140_PREFIX
as a workaround.
Co-authored-by: Vaishali Thakkar <me.vaishalithakkar@gmail.com>
Signed-off-by: Michal Rostecki <vadorovsky@gmail.com>
=> docker: Fix arm64 build

Makefile, deploy/e2e.jsonnet, e2e/e2e_test.go, e2e/local-e2e.sh, go.mod
Very early version, so excuse the lazy shell scripting, plus need to add a lot more test cases. 
Use `make dev/e2e`  from root of the repo to run the tests.
Fixes #317
cc @v-thakkar @javierhonduco
=> Add e2e tests

Dockerfile, Dockerfile.dev
This is a suggestion. apt.llvm.org only keeps the latest build.
This uses the `sid` (`unstable`) channel from the Debian snapshot to get the LLVM 14 toolchain.
`bookworm` (`testing`) should also work depending on how stable or fast fixes are desired.
https://wiki.debian.org/DebianUnstable
https://wiki.debian.org/DebianTesting
It does get hard to tell which channel provides which package due to how they depend on each other, but unstable/testing should get the lowest priority if I understand correctly: https://manpages.debian.org/bullseye/apt/apt_preferences.5.en.html#APT's_Default_Priority_Assignments
Closes #449
=> build(deps): use llvm-14 from Debian snapshot

.editorconfig, Dockerfile, Dockerfile.dev, make-containers.sh
* Fix `set +euxo pipefail` --> `set -eux pipefail`
* Pin manifest list digest of base images directly in `Dockerfile` (you can use `regctl manifest digest --require-list IMAGE_NAME` to find it), instead of passing individual arch digest via args, this should make updates simpler, and Dependabot may be able to do PRs, if not, I highly recommend [Renovate](https://github.com/apps/renovate) which [can do a lot more](https://docs.renovatebot.com/docker/#digest-pinning)
* Use [Buildkit's `TARGETARCH` ARG](https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope) instead of `ARCH`, it standardize things a little and makes things easier if you happen to build with `docker-buildx`
* Lint with `shellcheck` and `hadolint`
* Sync `Dockerfile` and `Dockerfile.dev` …
=> build: fix silent container build failure and lint

README.md, cmd/debug-info/main.go, cmd/parca-agent/main.go, go.mod, go.sum, pkg/debuginfo/debuginfo.go, pkg/debuginfo/extract.go, pkg/debuginfo/upload.go, pkg/elfwriter/elfwriter.go, pkg/elfwriter/elfwriter_test.go, pkg/profiler/profiler.go, pkg/target/manager.go, pkg/target/profiler_pool.go
With the introduction of the new Go `elfwriter` package, we don't need to keep a temporary state in the local filesystem for interim files. We can directly write to a memory buffer and flush it to the gRPC connection. So this PR exactly does that.
cc @v-thakkar @javierhonduco
=> debuginfo: Remove temporary local file state

cmd/parca-agent/main.go, pkg/agent/profile_listener.go, pkg/template/statuspage.html, pkg/template/template.go, pkg/template/template_test.go, pkg/template/testdata/statuspage.html
* Use next profile start time instead of last. Last has become less relevant (goes up to 2x duration) and shows 52 years for the first duration
* Change `Show Profile` into `Show Next Profile`
* Add `title` to link (tooltip) informing it may take up to the profiling duration to display
* Trim white-spaces
* Change `Download Pprof` into `Download Next Pprof`, add tooltip as well
* Calculate query timeout based on `--profiling-duration` flag
* Fix `profileListener.NextMatchingProfile()` (it was always returning the first profile)
Related to #146
=> fix(statuspage): improve display of next profile

.github/workflows/build.yml, .github/workflows/release.yml
Follow up on #491, that pinned a few actions I had missed in #485.
Without the tags used by releases, we would get obscure digest updates, instead of pretty release notes
=> chore(deps): use full tag for gh actions

.github/workflows/build.yml, Makefile
Let's add [Golang's race detector](https://go.dev/doc/articles/race_detector) to our Makefile. I have been running it in my test environment, and it showed zero errors, even under a lot of pressure (lots of concurrent debug info uploads, etc).
With the `GORACE="log_path=/tmp/race"` env variable we can pick a path where to write its output, rather than stdout / stderr.
Right now we should run this locally, but once https://github.com/parca-dev/parca-agent/issues/463 lands, this will be run in CI, too! 🎉 
Fixes: https://github.com/parca-dev/parca-agent/issues/445
**Build without sanitisers works**:
```
[javierhonduco@computer parca-agent]$ make build-dyn 
GOOS=linux GOARCH=amd64 CC=clang CGO_CFLAGS="-I /home/javierhonduco/code/parca-agent/dist/libbpf/usr/include" …
```
=> build: Add race detector flag

.github/workflows/build.yml
Fixes:
```
/home/runner/work/_temp/420af443-00f1-4def-b386-9035d4dc1c24.sh: line 1: GOLANGCI_LINT_VERSION: command not found
golangci/golangci-lint info checking GitHub for latest tag
```
=> ci: fix golangci-lint version

.gitmodules, go.mod, go.sum, renovate.json, shell.nix
I have renamed the git submodule to be location/path independent and enabled update automation. Renovate might actually follow tags for submodules, we'll see with the next release
Due to the submodule renaming, you might need to re-initialize it:
```shell
rm -rf .git/modules 3rdparty
git submodule init && git submodule update --recursive
```
Closes #527
=> build(deps): update libbpfgo to v0.3.0-libbpf-0.8.0

renovate.json
The `git-submodules` manager follow the `HEAD` of the repository instead of the tags, some comments in the feature request seemed to indicate it could be working, which prompted me to test it.
https://docs.renovatebot.com/modules/manager/git-submodules/#open-feature-requests
=> chore(renovate): disable git-submodules updates

Makefile
I have not tested pushing, but ~I have a hunch~ Podman's `--tag` behave like the classic `docker build`, rather than changing to Docker Buildx's behavior with `--platform`, so platforms override one after the other and `--manifest` must be used instead
> When more than one platform is specified, the `--manifest` option should be used instead of the `--tag` option.
https://docs.podman.io/en/latest/markdown/podman-build.1.html#platform-os-arch-variant
Fixes #559
=> ci: fix image manifest push

bpf/xtask/Cargo.toml, renovate.json
The default is equivalent to a caret: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements
=> chore(deps): pin rust crates

Makefile, bpf/Makefile, shell.nix
Since `bpf-linker` is built with `--features system-llvm`, LLVM 14 needs to be setup properly in `nix-shell` as well. 
~Blocked by NixOS/nixpkgs#148117 (https://nixpk.gs/pr-tracker.html?pr=178007)~
=> chore(nix-shell): fix llvm

pkg/profiler/cpu.go
Fixes: https://github.com/parca-dev/parca-agent/issues/635, https://github.com/parca-dev/parca-agent/issues/631
After landing system-wide profiling (https://github.com/parca-dev/parca-agent/pull/627) we started noticing way more profiles that failed with various error messages (https://github.com/parca-dev/parca-agent/issues/635), such as:
- `gzip: invalid header`
- `flate: corrupt input before offset 2170`
- `unexpected EOF`
Which indicated some sort of corruption going on. This correlates well to the addition of system-wide, which not only produces way more profiles overall but also increases the pace at which they are generated.
After playing around with the code in the [write client](https://github.com/parca-dev/parca-agent/blob/0c75dc960f9046d1e49bedc3a09d07504dcf580f/pkg/agent/write_ …
=> profiler: Fix race condition in the profile's buffer

pkg/metadata/utils.go, pkg/metadata/utils_test.go, pkg/profiler/cpu.go
**Added tests**:
```
$ make test/profiler
--- PASS: TestGetValueAndDeleteBatchExactElements (0.00s)
=== RUN   TestThing
=== RUN   TestThing/single_cgroup_path
=== RUN   TestThing/single_cgroup_path_without_trailing_newline
=== RUN   TestThing/deeper_cgroup_path
=== RUN   TestThing/root_cgroup_path
=== RUN   TestThing/extract_cpu_controller_from_multiple_cgroup_controllers
=== RUN   TestThing/extract_cpu_controller_from_multiple_cgroup_controllers#01
=== RUN   TestThing/malformed_path_does_not_panic
=== RUN   TestThing/empty_path_does_not_panic
--- PASS: TestThing (0.00s)
--- PASS: TestThing/single_cgroup_path (0.00s)
--- PASS: TestThing/single_cgroup_path_without_trailing_newline (0.00s)
--- PASS: TestThing/deeper_cgroup_path (0.00s)
--- PASS: TestThing/root_cgroup_path (0.00s)
--- PASS: …
```
=> profiler: Add cgroup name to the process metadata

pkg/debuginfo/debuginfo.go
and increase the cache expiration time
Spotted this while running the Agent for several minutes. The rationale for this change is that:
- The increase in memory usage won't be very large: from 2,048 bytes to 6,144 bytes (+ the overhead of the cache data structures)
(Also removed an outdated comment).
Let me know what you think and if I missed anything
=> debuginfo: Increase exists cache size

.github/workflows/build.yml, .github/workflows/cargo-audit.yml, .github/workflows/container.yml, .github/workflows/release.yml, Makefile, bpf/Cargo.lock, bpf/Makefile, bpf/cpu-profiler/src/main.rs, bpf/xtask/Cargo.toml, bpf/xtask/src/main.rs, cmd/parca-agent/main.go, pkg/profiler/cpu.go, pkg/profiler/noop.go
This PR enables various lint strategies for Rust I have recently learned
* Deny all warnings
* Run `fmt`, `clippy`, and `doc` (even though there is no doc comments at the moment) in CI
* Use `cargo-audit`. Since CodeQL does not support Rust, [rustsec.org](https://rustsec.org) is the best alternative I have found (although it is not static analysis)
* Enable Clippy for RLS users (`#![warn(clippy::all)]`): [rust-lang/rls#configuration](https://github.com/rust-lang/rls#configuration)
* Downgrade `anyhow` to v1.0.59. Found out v1.0.60 has been yanked with `cargo-audit`
* Remove `go vet`. Redundant with `golangci-lint`
* Format with `gofumpt`. Not sure why `golangci-lint run --fix` does not work for that
* Optimize `go list` commands in `Makefile`
=> ci: improve linting of Rust code

.github/workflows/release.yml, .github/workflows/snap.yml, .gitignore, .goreleaser.yml, RELEASE.md, snap/README.md, snap/hooks/configure, snap/local/parca-agent-wrapper, snap/snapcraft.yaml
Adds snap packaging to the goreleaser config, along with some CI setup to test/publish the snap on merges to main, or when publishing a release.
Will need some credentials adding before merging for the publishing to work! :)
Similar to https://github.com/parca-dev/parca/pull/1488 but works slightly differently. Because the agent is built in a container, and snapcraft cannot be installed in a container (Snapcraft is only delivered as a snap) I've had to make it a separate build step.
Fixes #674
=> feat: add snap packaging

.github/workflows/release.yml, .github/workflows/snap.yml, .gitignore
Related to #692
This PR
- Disables publishing to `latest/stable` in the Snap store until we can fix the confinement issue
- Adds some entries to `.gitignore` that are useful when debugging snaps locally
- Removes some unneeded steps from the snap tests
=> ci: disable publish to latest/stable in snap store

pkg/ksym/ksym.go, pkg/ksym/ksym_test.go
Rather than an unlimited one, which has the potential of creating too much memory pressure.
When the cache is full, finding an element is cheaper than it used to thanks to https://github.com/parca-dev/parca-agent/pull/708, as:
- We don't have to read the file nor parse it every single time
- And most importantly, we swapped the linear search with a binary search
=> Ksym cache: Use a bounded cache

pkg/profiler/cpu/cpu.go
This error is not preventing us from shipping data to a storage, so seeing this error in logs is more confusing to users than helpful. When debugging it might be useful though so lowering it to debug level.
=> pkg/profiler/cpu: Lower log level when failing to symbolize

pkg/perf/perf.go
I tried to understand what a log line was trying to tell me and I kept thinking that the Parca Agent was failing to find symbols for something, when it was really just not finding a perf-map for that process, which is perfectly fine since most processes don't have jitted symbols.
=> pkg/perf: Clarify the not found error is about perf-maps

Makefile
I use Podman in rootless mode, so `DOCKER_SOCK` is `/run/user/1000/podman/podman.sock`.
(I have not been able to build these targets tho, which is required to build a local container, goreleaser+Makefile has given me a headache, giving up for now, we might want to use `goreleaser build --rm-dist --single-target --snapshot --debug` in the `make build`)
=> chore: parametrize DOCKER_SOCK in Makefile

pkg/perf/perf.go, pkg/symbol/symbol.go
As I was debugging https://github.com/parca-dev/parca-agent/issues/750 I realized
that we are returning the same error when checking if the map file is present
but also the proc status file which might be confusing during troubleshooting.
=> perf: split perf-map and proc status not found errors

internal/dwarf/frame/table.go, internal/dwarf/frame/testdata/generated_tables/libc-6.txt
Addresses a good portion of the issues in table generation that affected our test libc. Also, pass the length hint to the map to avoid reallocations + unnecessary copying on map growth.
=> .eh_frame: Carry over the initial and previous registers

.github/workflows/snap.yml
Now that this PR: https://github.com/snapcore/snapd/pull/12061 is landed, snapd should permit the agent to read the kernel config from `/boot/config*`.
Marking as "Draft" for now until `snapd` releases properly.
=> ci: use snapd from edge channel

internal/dwarf/frame/entries.go, internal/dwarf/frame/table.go, pkg/stack/unwind/plan_table_test.go
= Adds missing implementations for DWARF frame instructions.
```
DW_CFA_MIPS_advance_loc8		MIPS-specific. Implementation is provided regardless.
DW_CFA_GNU_window_save			SPARC-specific. Unsupported architecture. Read and skip.
DW_CFA_GNU_args_size			This instruction specifies the total of the size of the arguments which have been pushed onto the stack.
DW_CFA_GNU_negative_offset_extended	PowerPC-specific. Deprecated. Read and skip.
```
- Fixrd failing test
- Renames `FrameContext` to `Context` to avoid stutter.
=> dwarf/frame: Add missing instructions

internal/dwarf/frame/table.go, internal/dwarf/frame/testdata/generated_tables/libc-6.txt, internal/dwarf/frame/testdata/generated_tables/parca-demo-cpp-out.txt
This fixes the missing instruction issue described in https://github.com/parca-dev/parca-agent/issues/772 (see 'Missing instruction (4011f0..401243)').
I was logging all the instructions that are being executed and noticed that different `advance_location` flavour were being called. This can be observed with `readelf`:
```
[javierhonduco@fedora parca-agent]$ readelf --debug-dump=frames  /proc/$(pidof parca-demo-cpp)/exe  | grep 4011f0 -A15
00000088 000000000000001c 0000008c FDE cie=00000000 pc=00000000004011f0..0000000000401243
DW_CFA_advance_loc: 1 to 00000000004011f1
DW_CFA_def_cfa_offset: 16
DW_CFA_offset: r6 (rbp) at cfa-16
DW_CFA_advance_loc: 3 to 00000000004011f4
DW_CFA_def_cfa_register: r6 (rbp)
DW_CFA_advance_loc1: 78 to 0000000000401242
DW_CFA_def_cfa: r7 (rsp) ofs 8
DW_CFA_nop …
```
=> .eh_frame: Carry over state in all advance locations

bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go
- increase table size by 30k items
- read symbols from the dynamic string table, too
- add initial code to compact the unwind table by removing redundant rows (disabled by default, will add tests in the near future, but tested with `parca-demo-cpp-no-fp` and `parca-demo-cpp` and they both worked)
=> .eh_frame: unwind table map improvements

pkg/profiler/profile_writer.go
This changes the file name format to:
```
<PID>_<profiler>_<timestamp>.pb.gz
```
Making it easy to find profiles for given processes
=> fix(file-writer): prefix file name with PID

pkg/symbol/symbol.go
This happens often and shows in the UI. The 2 errors used to be one and were meant to be ignored before.
=> fix(symbol): ignore ErrPerfMapNotFound error

internal/dwarf/frame/table.go, internal/dwarf/frame/testdata/generated_tables/libc-6.txt
In some cases, we weren't generating the correct tables, for example, for the libc we use to test `internal/dwarf/frame/testdata/libc.so.6`.
`readelf` builds this unwind table:
```
LOC           CFA      ra
00000000001999a0 rsp+8    c-8
00000000001999a8 rsp+64   c-8
0000000000199b0f rsp+8    c-8
0000000000199b18 rsp+64   c-8
0000000000199b43 rsp+8    c-8
0000000000199b48 rsp+64   c-8
```
while our implementation produces wrong results:
```
=> Function start: 1999a0, Function end: 199cd8
(found 6 rows)
Loc: 1999a0 CFA: $rsp=8   	RBP: u
Loc: 1999a8 CFA: $rsp=64  	RBP: u
Loc: 199b0f CFA: $rsp=8   	RBP: u
Loc: 199b18 CFA: $rsp=8   	RBP: u
Loc: 199b43 CFA: $rsp=8   	RBP: u
Loc: 199b48 CFA: $rsp=8   	RBP: u
```
This is due to the way the `DW_CFA_remember_state` and `DW_CFA_restore_state` dwarf …
=> .eh_frame: Fix remember and restore state

bpf/cpu/cpu.bpf.c, internal/dwarf/frame/testdata/generated_tables/libc-6.txt, internal/dwarf/frame/testdata/generated_tables/parca-demo-cpp-no-fp-out.txt, internal/dwarf/frame/testdata/generated_tables/parca-demo-cpp-out.txt, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go, pkg/stack/unwind/plan_table.go
Right now we were skipping over expressions but we weren't setting the current CFAs that require a expression to be evaluated as such.
This PR doesn't tackle expression evaluation. It focuses on ensuring that CFAs are marked as either a combination of register and an offset, which we already support, or as an unsupported expression. In the latter case we will not walk the stack in BPF.
This also fixes the table printing as rows with expressions had the previous value, which is not correct.
=> .eh_frame: CFA := (exp | regOffset)

bpf/cpu/cpu.bpf.c
```
$ sudo cat /sys/kernel/debug/tracing/trace_pipe | grep stats -A5 
parca-demo-cpp-400183  [011] d.h2. 452862.116620: bpf_trace_printk: [[ stats ]]
parca-demo-cpp-400183  [011] d.h2. 452862.116620: bpf_trace_printk: success=33
parca-demo-cpp-400183  [011] d.h2. 452862.116620: bpf_trace_printk: unsup_expression=1
parca-demo-cpp-400183  [011] d.h2. 452862.116621: bpf_trace_printk: truncated_counter=0
parca-demo-cpp-400183  [011] d.h2. 452862.116621: bpf_trace_printk: total_counter=35
```
=> .eh_frame: Add basic stats to the stack walker

pkg/debuginfo/metrics.go
As the license checks are failing locally
Before this PR:
``` 
[javierhonduco@fedora parca-agent]$ make lint
./scripts/check-license.sh
license header checking failed:
./pkg/debuginfo/metrics.go
make: *** [Makefile:168: check-license] Error 255
```
After:
``` 
[javierhonduco@fedora parca-agent]$ make lint
./scripts/check-license.sh
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CC="clang" golangci-lint run
[...]
```
=> pkg/metrics: Add license header

Makefile, cmd/eh-frame/main.go, internal/dwarf/frame/entries.go, internal/dwarf/frame/table.go, internal/dwarf/util/buf.go, internal/dwarf/util/util.go, internal/dwarf/util/util_test.go, pkg/stack/unwind/unwind_table.go, pkg/stack/unwind/unwind_table_test.go
This PR builds on https://github.com/parca-dev/parca-agent/pull/863, which added the initial DWARF parsing code and continues by adding almost all the remaining changes:
- Various utilities to decode DWARF's `sleb` and `uleb` numbers;
- The unwind table generation;
- A program to print the whole table, which we've been using to run snapshot tests and ensure that changes didn't affect correctness in unintended ways;
- Correctness fixes to the table generation:
- Ensuring we copy all the registers from previous rows within a function, this fixes issues we saw with `$rbp`;
- Creating new code locations for every `advancelocation` family of opcodes;
- Fixing the remember and restore state, as the CFA wasn't stored
The original commits for this feature in the WIP branch:
- @kakkoyun …
=> .eh_frame: Unwind table generation

cmd/parca-agent/main.go, pkg/discovery/systemd.go
This adds empty `TargetGroup`s (with only `Source` set) to notify the discovery manager when systemd units have exited. Kubernetes has a delete channel which allow do that nicely, but systemd would just leave them dangling until now. It may be possible to use DBus signals instead when doing #760
It also corrects the PID labels cache configuration (I had initially not seen it was configured with an option, and thought it was not configured at all):
* Expire after write as some keys may never be accessed
* Set expiration in relation to profiling duration as the cache is accessed in the profile loop, not during remote batch write
Fixes #806
=> fix(discovery): ensure systemd units which have disappeared are accounted for

Makefile, shell.nix
This basically makes the binary static.
I was unable to build it on NixOS:
```
go build  -trimpath -v -o dist/eh-frame ./cmd/eh-frame
os/user(.text): relocation target malloc not defined
os/user(.text): relocation target free not defined
os/user(.text): relocation target getgrgid_r not defined
os/user(.text): relocation target getgrnam_r not defined
os/user(.text): relocation target getpwnam_r not defined
os/user(.text): relocation target getpwuid_r not defined
os/user(.text): relocation target realloc not defined
os/user(.text): relocation target sysconf not defined
runtime/cgo(.text): relocation target stderr not defined
runtime/cgo(.text): relocation target fwrite not defined
runtime/cgo(.text): relocation target __vfprintf_chk not defined
runtime/cgo(.text): relocation target fputc …
```
=> build(eh-frame): build with osusergo

.golangci.yml, README.md, cmd/parca-agent/main.go, go.mod, parca-agent.yaml, pkg/config/config.go, pkg/config/config_test.go, pkg/profiler/cpu/cpu.go, pkg/profiler/noop.go, pkg/template/statuspage.html, pkg/template/template.go, pkg/template/template_test.go, pkg/template/testdata/statuspage.html
This adds supports for `relabel_configs: []` via an optional configuration file.
There are some awkward back-and-forths between `model.LabelSet` and `labels.Labels` types, I tried to minimize them as much as possible.
On the long-run, how and where labels/metadata are managed will need to be rethought.
I had to re-arrange the status page once again to ensure relabeling works with the full set of labels for each profile types.
Following this PR, I have in mind:
* add back k8s/cgroup/systemd flags for best-effort backward compatibility and keep them for 1 or 2 minor releases (#690), this only require appending a relabel config for each case
* update the agent documentation
* reload configuration on-change
Closes #7 and #690
=> feat: support relabeling

bpf/Makefile, bpf/cpu/cpu.bpf.c, go.mod, go.sum
Upgrade to libbpfgo@v0.4.0-libbpf-1.0.1
**e2e test with Parca and Parca Agent running side by side**
**Ensure that there are no warnings**
```
[javierhonduco@fedora parca-agent]$ sudo dist/parca-agent --log-level=debug --node=info |& grep -e libbpf
```
=> libbpf: Upgrade to libbpf v1.0.1

.github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/jsonnet.yml, .github/workflows/release.yml, Makefile, deploy/Makefile, deploy/e2e.jsonnet, e2e/ci-e2e.sh, e2e/e2e-dump.sh, e2e/e2e_test.go, e2e/podportforward.go, env-jsonnet.sh, env.sh, go.mod, go.sum, internal/dwarf/frame/table.go
Modify actions and tests to allow e2e testing in parca agent.
For every PR, a test image of parca agent is created(hosted at parca-agent-test)
which is then tested alongwith the latest release of parca server
within a minikube setup in CI.
Add support for debugging opaque failures in CI using upterm shell.
All scripts and tests can be found in the `e2e` directory in parca-agent
Co-developed-by: Frederic Branczyk
=> ci: Enable e2e testing in ci

.github/workflows/snap.yml, snap/snapcraft.yaml
After some thought, I think the way `parca-agent` accesses the underlying system makes it a more compelling candidate for `classic` confinement, rather than `strict`.
:warning:  This PR shouldn't be merged until the store have enabled classic confinement for this snap - I'll post back when that's done and take care of that getting sorted. :warning:
=> Adjust snap package to use classic confinement

.github/workflows/build.yml, .gitmodules, Makefile, pkg/stack/unwind/unwind_table_test.go
This PR adds a new submodule under `testdata/`, which contains [the executables and their expected unwind tables](https://github.com/parca-dev/testdata/tree/main/tables).
**Run Go tests**
```
$ make tests
```
**Unwind tables snapshot tests**
```
$ make test-dwarf-unwind-tables
```
=> .eh_frame: Add unwinding table tests

pkg/stack/unwind/unwind_table_test.go
Adding a benchmark for our table generation code to track its performance over time
```
$ go test -v github.com/parca-dev/parca-agent/pkg/stack/unwind -bench=.
=== RUN   TestBuildUnwindTable
--- PASS: TestBuildUnwindTable (0.00s)
goos: linux
goarch: amd64
pkg: github.com/parca-dev/parca-agent/pkg/stack/unwind
cpu: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
BenchmarkParsingLibcDwarfUnwindInformation
BenchmarkParsingLibcDwarfUnwindInformation-12    	      58	  57819288 ns/op	32710616 B/op	  149598 allocs/op
PASS
ok  	github.com/parca-dev/parca-agent/pkg/stack/unwind	3.380s
```
cc @brancz @v-thakkar 
=> pkg/stack: Add benchmark for unwind table generation

pkg/metadata/compiler.go
**TL;DR:** >40% of the Parca Agent CPU cycles are spent reading all the elf symbols for each binary to see whether they are stripped or not. Some extra cycles come from added pressure on the garbage collector
The compiler metadata, specifically, the stripped check, consumes a large amount of CPU as it parses and traverses the whole symbol table for each process running on the system.
This first commit caches the compiler metadata using the BuildID as the caching key.
I noticed that while checking CPU profiles in our demo environment:
I Ran Parca and Parca Agent side by side, and everything looked good, the compiler metadata uses way fewer cycles
The `string => elf.File` refactor in https://github.com/parca-dev/parca-agent/pull/876 was mostly to improve the API, performance-wise the impact …
=> pkg/metadata: Cache compiler metadata output

pkg/ksym/ksym_test.go
Checking Parca's CPU profiles it was clear that the `kallsymsHash()` function consumes a non-trivial amount of CPU time, around ~8% of the Agent's CPU cycles, while `loadKsyms()` barely appears in them.
This makes sense, as the kernel symbols won't change often, so most of the time, the hash won't change and we won't re-read the kernel symbols and rebuild its table.
I wanted to understand the benefit of doing the hash and in case it's not the same, re-loading the kernel symbols, so wrote some simple benchmarks to understand the CPU and memory usage.
```
[javierhonduco@fedora testdata]$ go test -v github.com/parca-dev/parca-agent/pkg/ksym  -bench=.
=== RUN   TestEnsureKsymSizeDoesNotGrow
--- PASS: TestEnsureKsymSizeDoesNotGrow (0.00s)
=== RUN   TestKsym
--- PASS: TestKsym (0.00s)
goos: …
```
=> pkg/ksym: Add benchmarks for the kernel symbolizer

Makefile, README.md, bpf/cpu/cpu.bpf.c, cmd/parca-agent/main.go, docs/hacking_on_native_stack_unwinding_without_frame_pointers.md, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/cpu_test.go, pkg/profiler/cpu/maps.go, pkg/stack/unwind/unwind_table.go, pkg/stack/unwind/unwind_table_test.go
This PR implements the v1 of native stack walking using dwarf unwind tables. What this means, in practice, is that it's in beta status and this work doesn't include the full scope of the final implementation. More importantly, this implementation focuses:
- Correctness, not performance;
- The x86_64 architecture and ABI;
- C and C++;
- Only the `.eh_frame` section is supported;
- Processes with combined unwind tables up to 130k rows;
- While we support all the important DWARF opcodes, `expression` and `register` related opcodes are ignored at this point;
There are 3 commits that add the BPF unwinder, the necessary supporting facilities in Go, and some documentation.
Umbrella issue: https://github.com/parca-dev/parca-agent/issues/768
```shell
$ dist/parca-agent $FLAGS …
```
=> Native stack walking with DWARF v1

Makefile, README.md, cmd/parca-agent/main.go
Maybe you've discuss it or thought about it some time ago?
This defaults `--node` to the host name provided by the kernel, which is correct if not running in a container. Making all `parca-agent` flags optional.
=> feat: set default node name

bpf/common.h, bpf/cpu/cpu.bpf.c, internal/dwarf/frame/table.go, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/cpu_test.go, pkg/profiler/cpu/maps.go
This PR implements the v2 of the DWARF stack unwinder:
- The first commit reduces the unwind table size by half, allowing for more entries to fit in the table;
- The second commit removes `bpf_loop`, reducing the minimum required kernel version;
- The third commit reenables the CPU tests;
The details for each commit can be found in their commit message.
Ensured, visually, that the stacks are correct:
**`testdata/out/basic-cpp-no-fp`**:
<details>
</details>
**CRuby interpreter**
<details>
[...]
</details>
=> Native stack walking with DWARF v2

pkg/elfwriter/aggregating_elfwriter_test.go, pkg/elfwriter/elfwriter_test.go
This is just to be in sync with the debuginfo extractor of parca agent. Doesn't change anything in the result produced by the tests.
=> elfwriter_test: Add all types in the symbol table

pkg/executable/executable.go, pkg/executable/executable_test.go, pkg/stack/unwind/unwind_table.go
Right now, processes that are loaded at a randomized address won't work
with the current dwarf-based stack unwinding code. The reason for this
is that the program counters aren't adjusted accordingly.
This commit adds a new package under `pkg/executable` that will host
code specific to executables. The `IsASLRElegible` is documented inline,
it's a pretty basic function and doesn't handle some edge cases, but
this should do for most of the processes I've tried in my host (see test
plan of this PR and in the upcoming sharded unwind table work).
In the future, this will be refactored in a more cohesive module that
will do more groundwork necessary for other parts of the profiler.
Caching will be added later on, too.
The first commit updates the testdata repository which adds the PIE …
=> .eh_frame: Initial ASLR support

.github/workflows/build.yml, bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go, pkg/stack/unwind/unwind_table.go
This commits range-shards the unwind table bumping the maximum table size from 250k elements to 750k, allowing us to profile larger executables.
While running all these tests, `sudo bpftool prog tracelog | grep error` returned no results.
The stats looked similar in all the below, but for Postgres:
``` 
postmaster-123830  [007] d.h2.  9831.335675: bpf_trace_printk: [[ stats for cpu 7 ]]
postmaster-123830  [007] d.h2.  9831.335677: bpf_trace_printk: success=349
postmaster-123830  [007] d.h2.  9831.335678: bpf_trace_printk: unsup_expression=0
postmaster-123830  [007] d.h2.  9831.335679: bpf_trace_printk: truncated=0
postmaster-123830  [007] d.h2.  9831.335680: bpf_trace_printk: catchall=0
postmaster-123830  [007] d.h2.  9831.335681: bpf_trace_printk: never=0
postmaster-123830  [007] d.h2. …
```
=> .eh_frame: Shard unwind table

README.md, cmd/parca-agent/main.go, pkg/debuginfo/manager.go
There may be cases where we want to investigate whether there is a problem with re-written binaries, in those cases, it would be handy to have a flag to turn it off.
=> *: Add flag to allow skipping stripping of binaries

.github/workflows/container.yml, Makefile, deploy/e2e.jsonnet, deploy/jsonnetfile.json, deploy/jsonnetfile.lock.json, e2e/ci-e2e.sh, e2e/e2e_test.go, renovate.json, scripts/local-dev.sh
* Use Minikube's `none` driver to run Kubernetes on GH runner directly
* Only take care of the deployment in `ci-e2e.sh`, wrapping the `minikube` CLI does not add a lot of value and is complex depending on the driver used and host machine, everything is taken care by the setup action here, otherwise it's a simple `minikube start` (a simple comment on how to do it locally has been added with a mandatory Kube context parameter as a safe guard from unintentional deployments)
* Use Minikube's `stable` Kubernetes version (v1.25 currently), this should improve compatibility/stability. It will be bumped with each Minikube updates
* Hide PSP resources from Jsonnet output (removed in K8s v1.25) 
* Remove Minikube's `--feature-gates=EphemeralContainers=true`, now stable in v1.25
* ~~Remove …
=> ci(e2e): simplify setup

bpf/cpu/cpu.bpf.c, pkg/discovery/discovery_manager.go, pkg/profiler/cpu/cpu.go, pkg/profiler/profiler.go, pkg/symbol/symbol.go
* Merge profiles per process
* Provide Group target labels
Fixes #995 
* `make dev/up`
* Check correct labels
=> metadata: Add missing container labels back

bpf/cpu/cpu.bpf.c, cmd/parca-agent/main.go, pkg/discovery/discovery_manager.go, pkg/metadata/cgroup.go, pkg/metadata/compiler.go, pkg/metadata/labels/manager.go, pkg/metadata/labels/manager_test.go, pkg/metadata/metadata.go, pkg/metadata/process.go, pkg/metadata/service_discovery.go, pkg/metadata/system.go, pkg/metadata/target.go
* Cache labels by the provider
* Reduce the number of layer cache
* Refactor to ensure separation of concerns
* Add `ppid` for parent process ids
=> metadata: Refactor metadata provider

bpf/cpu/cpu.bpf.c, bpf/cpu/hash.h
Fixes https://github.com/parca-dev/parca-agent/issues/991#issuecomment-1315796852
```
[javierhonduco@fedora parca-agent]$ sudo bpftool prog tracelog   | grep stats -A7
basic-cpp-no-fp-4043219 [004] d.h2. 558229.143991: bpf_trace_printk: [[ stats for cpu 4 ]]
basic-cpp-no-fp-4043219 [004] d.h2. 558229.143991: bpf_trace_printk: success=449
basic-cpp-no-fp-4043219 [004] d.h2. 558229.143991: bpf_trace_printk: unsup_expression=0
basic-cpp-no-fp-4043219 [004] d.h2. 558229.143992: bpf_trace_printk: truncated=0
basic-cpp-no-fp-4043219 [004] d.h2. 558229.143992: bpf_trace_printk: catchall=0
basic-cpp-no-fp-4043219 [004] d.h2. 558229.143992: bpf_trace_printk: never=0
basic-cpp-no-fp-4043219 [004] d.h2. 558229.143992: bpf_trace_printk: total_counter=450
basic-cpp-no-fp-4043219 [004] d.h2. …
```
=> bpf: Ensure that the hashing code is unrolled

.github/workflows/release.yml
Fixes #1027 
The snap build action that happens for a release was missing a checkout, this PR fixes that.
=> ci: fix snap build for tags

deploy/lib/parca-agent/parca-agent.libsonnet
=> deploy: Add missing path prefixes to PodSecurityPolicy

bpf/cpu/cpu.bpf.c, cmd/parca-agent/main.go, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go, pkg/stack/unwind/unwind_table.go, scripts/local-run.sh
```
// Hidden debug flags (only for debugging):
--debug-process-names []string 
Only attach profilers to specified processes. comm name will be used to match the given matchers. Accepts Go regex syntax (https://pkg.go.dev/regexp/syntax).
// These flags are experimental. Use them at your own peril.
--experimental-enable-dwarf-unwinding bool 
Unwind stack using .eh_frame information.
```
1. `sudo ./scripts/local-run.sh` with **`testdata/out/basic-cpp-no-fp`**:
<details>
```shell
sudo "${PARCA_AGENT}" \
--node=local-test \
--http-address=:7071 \
--log-level=debug \
--experimental-enable-dwarf-unwinding \
--debug-process-names=basic-cpp-no-fp \
--remote-store-address=localhost:7070 \
--remote-store-insecure
```
</details>
2.  `sudo …
=> Introduce debug-process-names and experimental-enable-dwarf-unwinding

bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go
Reduce BPF map memory usage by using one BPF map for the multiple shards.
When sharding was introduced, multiple BPF maps were added for each of the shards. This is very wasteful as the kernel must preallocate **and** lock the memory, so it can never be paged out.
The other issue is that machines with low memory count would not have enough memory to create all the maps.
Before this commit we were using 3 shards * 256 (MAX_PID_MAP_SIZE ) * 64B * 2 (size of each row) * 250k MAX_UNWIND_TABLE_SIZE + other metadata that's not too big ~= 24.6GB. This is obviously a ridiculous amount of memory.
This commit changes the sharded table scheme to just use one BPF map where they key is (pid, shard_id) with the same size, so it will roughly lock 8GB. This number is still rather large. I've reduced …
=> bpf: Reduce BPF map memory usage

.github/workflows/release.yml, .github/workflows/snap.yml
Fixes #1048 
Github has slowly been changing the meaning of `ubuntu-latest` in their actions runners. Until recently, this was allocating Ubuntu 20.04 VMs for the builds, but has recently changed to 22.04.
In 22.04, there is a conflict between the version of Docker that is installed in the runners, and LXD. The result is that LXD containers cannot reach the internet when both Docker and LXD are installed. This is a small fix to the iptables rules on the actions runner that ensures the build can succeed.
Example run of this succeeding in a test branch in my fork: https://github.com/jnsgruk/parca-agent/actions/runs/3513824216
=> ci: deconflict docker/lxd iptables rule for snapcraft builds

pkg/buildid/buildid.go, pkg/buildid/buildid_test.go, pkg/metadata/compiler.go, pkg/objectfile/object_file.go, pkg/objectfile/object_file_test.go, pkg/process/maps.go
CPU usage for `elf.Open()` = **39.73 %** (13.63 + 13.42 + 12.68)
CPU usage for `elf.Open()` = **22.89 %**
Fixes #964
=> Reduce elf.Open() calls

go.mod, pkg/profiler/profile_writer.go
A drop-in replacement for gzip has impressively low allocs with decent speed/compression https://github.com/klauspost/compress/pull/216. See, gzip related code no longer shows up in the pprof top20.
<details>
```
(pprof) top20 -cum
Showing nodes accounting for 104.70MB, 40.74% of 257.02MB total
Dropped 109 nodes (cum <= 1.29MB)
Showing top 20 nodes out of 125
flat  flat%   sum%        cum   cum%
0     0%     0%   100.85MB 39.24%  github.com/oklog/run.(*Group).Run.func1
0     0%     0%   100.85MB 39.24%  github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).Run
0     0%     0%   100.85MB 39.24%  main.run.func6
0     0%     0%   100.85MB 39.24%  main.run.func6.1
0     0%     0%   100.85MB 39.24%  runtime/pprof.Do
0     0%     0%    73.71MB 28.68% …
```
=> pkg/profile: Replace gzip package to reduce allocs

bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go
Right now, we set the unwind tables map size to 100 elements. This means that we havce to allocate and lock roughly 100 elements * 250k entries * 16 bytes per entry ~= 400 MB, just for this map.
We are currently working on some optimisations that will result in lower memory required for the unwind tables, but this will take some weeks to land, so in the meantime, this commit reduces the default unwind tables map size to 2, which would be around 8MB, and only bump it to a 100 elements if dwarf based unwinding is enabled.
We still want to allocate and lock some memory even if we know that dwarf unwinding is disabled, as in the future this would be transparently enabled and it's highly likely that at least few processes (or mappings, soon) will use the dwarf based unwind approach. This way …
=> Conditionally set unwind tables map size

README.md
parca 0.10.0 does not have a `--pod-label-selector` flag anymore.
=> docs(README): remove pod-label-selector from README

bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/maps.go
Going from 0.75M to 1.5M unwind table rows in total. This will unblock some large binaries.
**Test plan**
Profiling systemd worked
=> Bump unwind table shards from 3 to 6

docs/labelling.md
See the sync script: https://github.com/parca-dev/docs/blob/d0fd8c32f5fa09a0dfdb98271f8645e090be1ab1/Makefile#L2
xref: https://github.com/parca-dev/docs/pull/202
original PR: https://github.com/parca-dev/docs/pull/186
=> docs: Move labelling doc from downstream parca-dev/docs

bpf/cpu/cpu.bpf.c, cmd/parca-agent/main.go, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go
Outputs of `bpftool map`:
<p> 
DWARF Unwinding Enabled
<details>
```text
100: percpu_array  name heap  flags 0x0
key 4B  value 1056B  max_entries 1  memlock 36864B
btf_id 323
pids parca-agent(1884277)
101: prog_array  name programs  flags 0x0
key 4B  value 4B  max_entries 1  memlock 4096B
owner_prog_type perf_event  owner jited
btf_id 323
pids parca-agent(1884277)
102: hash  name debug_pids  flags 0x0
key 4B  value 1B  max_entries 32  memlock 4096B
btf_id 323
pids parca-agent(1884277)
103: hash  name stack_counts  flags 0x0
key 20B  value 8B  max_entries 10240  memlock 327680B
btf_id 323
pids parca-agent(1884277)
104: stack_trace  name stack_traces  flags 0x0
key 4B  value 1016B  max_entries 1024  memlock 1048576B
pids parca-agent(1884277) …
```
=> Lower the required memlock rlimit if dwarf unwinding is not enabled

.github/workflows/container.yml, deploy/jsonnetfile.lock.json
```
parca: error: unknown flag --http-address, did you mean "--otlp-address"?
```
This fixes the E2E tests and downgrade the Parca Jsonnet lib until next release with new flags.
=> ci: ensure e2e runs when jsonnet files are updated

pkg/stack/unwind/unwind_table_test.go
```
$ go test -v github.com/parca-dev/parca-agent/pkg/stack/unwind -bench=.
=== RUN   TestBuildUnwindTable
--- PASS: TestBuildUnwindTable (0.00s)
goos: linux
goarch: amd64
pkg: github.com/parca-dev/parca-agent/pkg/stack/unwind
cpu: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
BenchmarkParsingLibcUnwindInformation
BenchmarkParsingLibcUnwindInformation-12                      57          43231125 ns/op        32710595 B/op     149598 allocs/op
BenchmarkParsingRedpandaUnwindInformation
BenchmarkParsingRedpandaUnwindInformation-12                   4         273076838 ns/op        524039788 B/op   2205965 allocs/op
PASS
ok      github.com/parca-dev/parca-agent/pkg/stack/unwind       5.774s
```
=> .eh_frame/parser: Add redpanda to benchmark

internal/dwarf/frame/table.go, pkg/stack/unwind/unwind_table.go, pkg/stack/unwind/unwind_table_test.go
As we are going to enable DWARF-based unwinding by default soon, which
means that the DWARF unwind information parser and the table generation
will be called significantly more times.
During prototyping, some shortcuts were taken, such as generating the
unwind table ahead of time. The unwind table is an array of unwind rows,
which for "medium-sized" binaries it can reach 200k entries. For the largest
binaries we've seen, the unwind tables were up to 2M entries big.
Generating and keeping these large slices in memory is not good for
performance, as we need to re-allocate them multiple times when
regrowing the backing memory buffer, as well as copying the data over, if
necessary.
While we could reasonably estimate the final size of the buffer using the
`.text` size as a proxy, this is not …
=> .eh_frame: Don't allocate the full unwind table by default

pkg/debuginfo/manager.go
Correctly set the size of the upload that is about to be initiated. Setting this will soon be enforced on the server side: https://github.com/parca-dev/parca/pull/2282
=> pkg/debuginfo: Set size of upload in upload initiation

pkg/profiler/cpu/cpu_test.go
I sometimes compile this test statically and run it in a VM to ensure that everything works. By allocating the extra space for unwind tables we'll ensure that there are no issues increasing their size.
Existing tests in CI
=> cpu/test: Ensure that unwind table can grow

go.mod, go.sum
- fixes the undefined behavoiur issue that we recently reported: https://github.com/aquasecurity/libbpfgo/issues/272
=> Bump libbpfgo to v0.4.5-libbpf-1.0.1

internal/dwarf/frame/table.go, pkg/profiler/cpu/cpu_test.go, pkg/stack/unwind/unwind_table.go, pkg/stack/unwind/unwind_table_test.go
We used maps to track every register, but we only need rbp, rsp (to calculate the CFA) and the return address.
Note that we don't need the return address offset for x86_64 but we'll need it for arm64 and this code will have to be modified to account for this architecture.
```
$ go test -v github.com/parca-dev/parca-agent/pkg/stack/unwind -bench=.  -count=30 > /tmp/new2
```
Not relying on maps yields a non-trivial perf improvement:
```
$ benchstat /tmp/old /tmp/new
name                                 old time/op    new time/op    delta
ParsingLibcUnwindInformation-12        15.5ms ±30%    11.8ms ±25%  -23.71%  (p=0.000 n=30+30)
ParsingRedpandaUnwindInformation-12    75.9ms ±12%    64.0ms ±11%  -15.68%  (p=0.000 n=30+29)
name                                 old alloc/op   new alloc/op …
```
=> .eh_frame/parser: Only collect registers used for unwinding

.github/workflows/build.yml, .github/workflows/vmtest.yml, .gitignore, Makefile, env.sh, kerneltest/kernels/README.md, kerneltest/logs/README.md, kerneltest/vmtest.sh, pkg/profiler/cpu/cpu_test.go
This PR ensures that we can load the BPF program in different kernels with 1.6G of available memory.
See https://github.com/parca-dev/parca-agent/issues/1141
```
$ ./env.sh # to install bluebox
```
`qemu-system-x86_64` and `curl` should be installed, too.
```
$ time make vmtest
[...]
Test summary: 4 passed, 0 failed
real	0m53.361s
user	0m55.341s
sys	0m2.298s
```
**locally, happy path**
```
$ make vmtest
[...]
=============
Test results:
=============
- ✅ 5.4
- ✅ 5.10
- ✅ 5.18
- ✅ 5.19
Test summary: 4 passed, 0 failed
```
**locally, error path**
```
$ make vmtest
[...]
=============
Test results:
=============
- ✅ 5.4
- ❌ 5.10
- ✅ 5.18
- ✅ 5.19
Test summary: 3 passed, 1 failed
(See logs in kerneltest/logs/)
make: *** [Makefile:222: vmtest] Error 1
```
**GH Actions**
See the `Kernel tests` …
=> Add initial kernel testing infrastructure

internal/dwarf/frame/table.go, pkg/stack/unwind/unwind_table.go, pkg/stack/unwind/unwind_table_test.go
of the initial context.
Improvements due to:
- avoiding copies of the initial CIE instructions (bytes.Buffer -> bytes.Reader)
- fewer Context object allocations
- due to the above, GC pressure was considerably reduced, which was the main objective of this changes as Parca Agent's CPU budget for the GC is already too high
resulting in ~4x less allocated memory and improvements in the runtime:
```
$ go test -v github.com/parca-dev/parca-agent/pkg/stack/unwind -bench=. -count=30
```
```
$ benchstat /tmp/main-6ad1efd /tmp/new
name                                 old time/op    new time/op    delta
ParsingLibcUnwindInformation-12        11.5ms ±14%     3.3ms ±17%  -70.82%  (p=0.000 n=26+29)
ParsingRedpandaUnwindInformation-12    66.1ms ±22%    37.7ms ± 2%  -42.99%  (p=0.000 n=30+30)
name …
```
=> .eh_frame: Reuse unwind context and reduce copies

.github/workflows/build.yml
Unsure sure why `make clean` is present. It should not be necessary
Sample of previous executions (they seem quite variable):
- 1.00mins: (https://github.com/parca-dev/parca-agent/actions/runs/3881975408/jobs/6621935520
- 2.47mins: https://github.com/parca-dev/parca-agent/actions/runs/3803239571/jobs/6469477128
- 3.39mins: https://github.com/parca-dev/parca-agent/actions/runs/3743606728/jobs/6355970546
- 3.43mins: https://github.com/parca-dev/parca-agent/actions/runs/3847317028/jobs/6553629022
=> ci: Do not clean before running tests

pkg/debuginfo/client.go, pkg/debuginfo/client_test.go, pkg/debuginfo/manager_test.go
@brancz [mentioned](https://github.com/parca-dev/parca-agent/pull/1138#issuecomment-1354576440) that `EnsureUploaded` has a room for perf improvements.
> Judging by what I'm seeing on demo I think we have much bigger fish to fry right now (allocations in EnsureUploaded and profiler loop stacks look like they should give us a major wins).
I found a TODO comment that mentions caching the hash, so I was thinking to prepare a benchmark for that code path to begin with.
```
// TODO: We should be able to cache the hash further to avoid
// re-hashing the same binary and getting to the same result
// again.
```
```
$ go test -benchmem -run=. -bench ^BenchmarkEnsureUploadedAlreadyExists$ ./pkg/debuginfo/
goos: linux
goarch: amd64
pkg: github.com/parca-dev/parca-agent/pkg/debuginfo
cpu: Intel(R) …
```
=> pkg/debuginfo: ensureUploaded benchmark

go.mod, go.sum, pkg/stack/unwind/executable.go, pkg/stack/unwind/executable_test.go
Starting with checking Go's version to see if it might have frame pointers enabled by default. Part of https://github.com/parca-dev/parca-agent/issues/1052
Added tests:
```
$ go test -v github.com/parca-dev/parca-agent/pkg/stack/unwind -- TestHasFramePointers
=== RUN   TestHasFramePointersInModernGolang
--- PASS: TestHasFramePointersInModernGolang (0.00s)
=== RUN   TestHasFramePointersInCApplication
--- PASS: TestHasFramePointersInCApplication (0.00s)
=== RUN   TestBuildUnwindTable
--- PASS: TestBuildUnwindTable (0.00s)
PASS
ok      github.com/parca-dev/parca-agent/pkg/stack/unwind       0.003s
```
=> .eh_frame: Add initial frame pointer detection

pkg/stack/unwind/maps.go, pkg/stack/unwind/maps_test.go
Add helpers to retrieve the information we need for native stack unwinding from process memory mappings.
This is the first step towards moving away from monolithic unwind tables to improve performance and the code: https://github.com/parca-dev/parca-agent/issues/1052.
Eventually, we might consolidate all these `proc/maps` helpers under the same package but can keep them in unwind right now as this is something we will only use here for the time being.
Added unittests
```
$ sudo /usr/local/go/bin/go test -v github.com/parca-dev/parca-agent/pkg/stack/unwind
[...]
--- PASS: TestBuildUnwindTable (0.00s)
PASS
ok      github.com/parca-dev/parca-agent/pkg/stack/unwind       0.040s
```
(running under sudo to also ensure no panics/weird behaviours with all the processes of my box, in CI, these …
=> .eh_frame: Add helpers for memory mappings

internal/dwarf/frame/entries.go
Needed by the per executable section unwind tables work (https://github.com/parca-dev/parca-agent/issues/1052), as it's good a good idea to sort the FDEs when generating the full unwind table, so we reduce sorting from `O(total_unwind_rows)` to `O(fdes)`, the latter being always (significantly) smaller.
=> internal/dwarf/frame: Make FrameDescriptionEntries sortable

pkg/executable/executable.go
Profiling while developing unwind tables per executable showed that `elf.Open()` was a big source of memory allocations. The extra CPU cycles caused by allocations, GC pressure, and the work inside of `elf.Open` accounted for ~20% of CPU cycles in my experiments.
In the current WIP rework, we already have an ELF file handle open that we can reuse, hence the added function.
Part of this work: https://github.com/parca-dev/parca-agent/issues/1052
=> pkg/executable: Add ASLR check with an existent ELF object

pkg/stack/unwind/compact_unwind_table.go, pkg/stack/unwind/compact_unwind_table_test.go, pkg/stack/unwind/dwarf_expression.go
Before, the code to convert from the initial DWARF unwind information rows to the compact representation we use for BPF was duplicated and not well-tested. This commit:
- cleans the code
- adds comprehensive unit tests
- prepares the ground for snapshot tests in forthcoming PR (https://github.com/parca-dev/testdata/pull/10)
The current code to convert to compact unwind tables will be cleaned up in another PR
Part of https://github.com/parca-dev/parca-agent/issues/1052, https://github.com/parca-dev/parca-agent/issues/874
Added unit-tests (will add snapshot tests in another PR)
=> Unify compact unwind tables code

Makefile, cmd/eh-frame/main.go, pkg/stack/unwind/unwind_table.go
Add compact tables snapshot tests to ensure that we don't accidentally break them.
part of https://github.com/parca-dev/parca-agent/issues/1052
```
$ make write-dwarf-unwind-tables
$ git diff
$
```
I've spot checked the table, and also ensured that the entries # matched:
```bash
$ wc -l testdata/{compact_,}tables/* | sort | tail -n +2 | awk -F' ' '{ count[$1]++ } END {for (el in count) print el, count[el]}'
14 2
23 2
49 2
53 2
18894 2
20620 2
28476 2
56693 2
71031 2
468837 2
```
=> Add compact tables snapshot tests

kerneltest/vmtest.sh
As they got modified in the subsequent commit and CI is broken now.
```
$ make vmtest
=============
Test results:
=============
- ✅ 5.4
- ✅ 5.10
- ✅ 5.18
- ✅ 5.19
Test summary: 4 passed, 0 failed
```
=> vmtest: pin kernel images revision

cmd/parca-agent/main.go, pkg/byteorder/byteorder.go
As both arm64 and x86_64 are little endian. While some arm64 processors support changing the their endianness, most implementations chose little endian.
Later on, we can change all the `binary.Write`s to have the endianness hardcoded.
=> Fail if the CPU is big endian

bpf/.clang-format, bpf/Makefile, bpf/cpu/cpu.bpf.c, go.mod, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/cpu_test.go, pkg/profiler/cpu/maps.go, pkg/stack/unwind/unwind_table.go, pkg/stack/unwind/unwind_table_test.go
This commit reworks the current DWARF-based unwinder and surrounding userspace facilities to deal with unwind tables per executable, rather than per process. It also removes the need to specify the processes names, only `--experimental-enable-dwarf-unwinding` is required.
The main benefits of this change are:
- Improved efficiency. We don't need to globally sort all the unwind entries, which in some cases resulted in a nontrivial CPU sorting millions of items. We also only produce the unwind tables for every unique executable once, and just add some metadata when a process contains a known mapping. We can completely skip the parsing of DWARF information as well as the interpretation to generate the table. This is a major win as most libraries are, well, shared, such as `libc`! :)
- Better …
=> .eh_frame: unwind table per executable

pkg/profiler/cpu/cpu.go
Long story short, profiling a hot box with lots of different processes might result in more than `MAX_STACK_COUNTS_ENTRIES` entries in the stack_counts map.
When that happens we don't store this profile, but because it might exist, we don't error.
In userspace, we attempt to read this ID, which was never written to the map, hence failing. The issue stems from that code, if there are any issues reading the user stack, with continue with the rest of the sample, when we should just drop it on the floor.
The samples would then look odd, as they would miss the user components and their mappings. Zeroes will be added on the left and some children nodes would not sum to ~100% of the parent.
Another question is whether we should use `BPF_ANY` instead of `BPF_NOEXIST`. We can leave that discussion …
=> pkg/profiler/cpu: skip samples with errored user stacks

cmd/parca-agent/main.go, pkg/profiler/cpu/cpu.go
Set the pprof profile handler only once we have loaded our BPF program to avoid SIGPROFs [1] while we are loading it which results in increased loading time in the best scenario, and failure to start the Agent in the worst case.
Loading our program takes a little bit, mostly due to the verification process, and if any signals are received during that time, the kernel will abort the loading process [2] and return with -EAGAIN. Libbpf will retry up to 5 times [3], and then return the error.
1: https://github.com/golang/go/blob/2ab0e04681332c88e1bfb5fe5a72d35c1c5aae8a/src/runtime/proc.go#L4658
2: https://github.com/torvalds/linux/blob/master/kernel/bpf/verifier.c#L13793-L13794
3: https://github.com/libbpf/libbpf/blob/d73ecc91e1f9a2f2782e00f010a5a0d6abec09a4/src/bpf.h#L68-L69
Test Plan …
=> Do not enable pprof profiling until BPF program is loaded

env.sh
As the current version consumes too much memory and it's OOMing my box after trying to use more than 50GB of memory.
=> env.sh: update golangci-lint to v1.51.1

pkg/profiler/cpu/cpu.go, pkg/stack/unwind/executable.go, pkg/stack/unwind/executable_test.go
As of right now it uses 50% of CPU cycles in Demo. We only saw it there as
it seems that the disks we use there are very slow.
Test Plan
=========
Ran the agent for a while with zero issues. Let's push this change to
the Demo environment and ensure that we are getting the performance wins
we expect.
Running locally:
=> Frame pointer detection caching

pkg/profiler/buffer.go, pkg/profiler/buffer_test.go, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go
Using `binary.Write` to write to memory buffers we use to update BPF maps is not only using quite a bit of CPU cycles but also incurs quite a bit of small allocations. In particular, [every single write performs an allocation](https://github.com/golang/go/blob/02d8ebda8398342516a24a3e8435d527ed156cab/src/encoding/binary/binary.go#L345).
This commit reduces allocations to 0 and CPU cycles by ~14x by writing to the buffer without performing any allocations. We do this with a new type, defined over a byte slice, which directly writes to the buffer using the lower-level `binary` APIs.
This also introduces two other advantages:
- The underlying array backing the slice will never grow in case of bugs. We want the buffers to be static and of exactly the size we expect in BPF.
- We can zero the …
=> Improve performance of BPF map buffer writes

pkg/profiler/cpu/cpu.go
sometimes i find it take a lot of time between agent get profile and server get debuginfo.
the agent upload each pid profile's objectfile to parca.
and the debuginfomanager use singleflight to make sure that only one debuginfoManager.EnsureUploaded is running.
if the exists api cost 10x ms, it will make the agent only upload one pid's objectfile.
it upload all pid's objectfile to parca.
which makesure that all pid's objectfile will uploaded.
=> pkg/profiler: Batch upload all prof's objFile

pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go
Trying to delete a key that doesn't exist fails with `ENOENT`. This might happen due to race conditions. For example, stacks keep on being written while we list and remove them.
In the future, we might want to have a better mechanism to prevent races from occurring in the first place, but let's ensure that we progress and continue removing items from the map if a key is not present.
If we don't do this, we might leave the map filled with older data, and can produce broken profiles.
This commit also moves the common listing+removing functionality to its own function
Test Plan
=========
Run the agent for >1h with DWARF unwinding and several hot processes without issues:
=> pkg/profiler/cpu: Ignore non-existent keys

cmd/parca-agent/main.go, pkg/metadata/pod_hosts.go, pkg/metadata/pod_hosts_test.go
it is not always ok to let parca-agent query k8s directly to connect pid and pod。
so we should provide pid's pod name if possible.
=> pkg/metadata: Add PodHosts provider to provide pod_ip and pod

bpf/cpu/cpu.bpf.c
Right now, the current value is ~1k. We will have collisions very quickly. With 500 elements alone, we'll have a probability of almost 1 of a hash collision (see [0]), so let's bump it to 64k.
[0] : https://preshing.com/20110504/hash-collision-probabilities
=> bpf: Increase the number unique stacks

bpf/cpu/cpu.bpf.c
When using `BPF_F_REUSE_STACKID` if a different stack hashes to the same hash, the old stack will be replaced with a new one. If a collision like that happens, we will get the wrong stack when finding the right kernel stack for its hash.
Right now we only have up to `MAX_STACK_TRACES_ENTRIES=1024` unique stacks, which is makes hash collitions incredibly common. This will be changed in a forthcoming commit.
=> bpf: Do not reuse kernel stack hash

bpf/cpu/cpu.bpf.c, cmd/eh-frame/main.go, pkg/profiler/cpu/maps.go, pkg/stack/unwind/compact_unwind_table.go, pkg/stack/unwind/compact_unwind_table_test.go, pkg/stack/unwind/unwind_table.go
Context
=======
DWARF unwind information specifies the low and high PC for every
function it covers. Within a function, it has entries for each
instruction boundary. These entries have the program counter they
start covering, but not its end.
This is not a problem for any instruction boundary except the last one,
but while we have that information when parsing the DWARF info, we never
add it anywhere in the BPF representation.
While this was not a problem for a large majority of the stacks we need
to unwind it introduce two issues:
- We know we've reached the bottom frame when a PC doesn't have unwind
info + frame pointer == 0. Normally the bottom frame has a PC that's
not covered by the (lowest, highest) PCs that the unwind info has, but
as far as I know there's no guarantee of this. If …
=> Add synthetic unwind row entry for the function end

Makefile
Test Plan
=========
```
$ make libbpf
$ ar x dist/libbpf/amd64/libbpf.a
$ gdb linker.o
```
**Before**
```
Dump of assembler code for function bpf_linker__new:
0x00000000000000fa <+10>:	sub    $0x28,%rsp
0x00000000000000fe <+14>:	mov    %rdi,%rbp
0x0000000000000101 <+17>:	test   %rsi,%rsi
```
**After**
```
Dump of assembler code for function bpf_linker__new:
0x00000000000000f0 <+0>:	push   %rbp
0x00000000000000f1 <+1>:	mov    %rsp,%rbp
```
=> build: Compile libbpf with frame pointers

bpf/cpu/cpu.bpf.c, pkg/stack/unwind/compact_unwind_table.go
We know we've reached the bottom of the stack when:
- we don't have unwind information && `$rbp==0`;
- we have unwind information, but the saved return address is undefined;
This commit adds the second case. The special value is encoded in the frame register to save some space as the field for return address (__reserved_do_not_use) is not needed in x86 and can be removed altogether.
Test Plan
=========
Profiled MySQL without issues. Before, it was failing to detect the end of frame condition as we didn't handle this case.
=> .eh_frame: Handle undefined rip

bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/maps.go
Oops. Forgot to remove these from testing... 🙃
- the RBP_TYPE is completely wrong and that condition won't ever reach.
- the default size is wrong. This will be adaptively changed in a future PR
=> .eh_frame: Remove testing values

bpf/cpu/cpu.bpf.c
Log the right frame index after tail-calls.
=> bpf/cpu: Log the right frame index

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/snap.yml
LLVM 11 is ancient, let's upgrade to 14. Additionally, this fixes the problem that https://github.com/parca-dev/parca-agent/pull/1357 was trying to fix. I suggest we land both because the code is a bit cleaner and it would be good to use a more modern compiler 😄
=> build: Upgrade LLVM from 11 to 14

cmd/parca-agent/main.go, go.mod, go.sum
This will unify the process libraries throughout the codebase.
=> main.go: Remove usage of keybase/go-ps

kerneltest/vmtest.sh, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/cpu_test.go, pkg/profiler/cpu/maps.go
Right now we request 50 unwind shards which account for ~200MB of kernel memory. Some systems might not have so much memory if they are running in constrained environments.
Rather than trying to figure out how much memory we have at our disposal, which is quite complicated to do, let's try to load some amount of shards and if that fails, try again with half the size.
Test Plan
=========
Now the kernel tests for 5.4 run with 1/3 of the memory, exercising this
code path.
```
[            ] stderr: level=debug name=parca-cpu-test ts=2023-02-21T10:53:55.189470094Z caller=cpu.go:238 msg="actual memory locked rlimit" cur="1.3 GB" max="1.3 GB"
[            ] stderr: level=info name=parca-cpu-test ts=2023-02-21T10:53:55.235053489Z caller=cpu.go:246 msg="Attempting to create unwind shards" …
```
=> .eh_frame: Adaptively size unwind info shard count

pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/cpu_test.go
As I didn't pass the right value in https://github.com/parca-dev/parca-agent/commit/8e9f580a79f4cfdabc74688b10ed259bf88b4a81
```
level=error name=parca-agent ts=2023-02-21T16:49:00.909431559Z caller=cpu.go:267 msg="Could not create unwind info shards"
panic: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x19896fd]
goroutine 133 [running]:
github.com/aquasecurity/libbpfgo.(*Module).Close(0x0)
github.com/aquasecurity/libbpfgo@v0.4.5-libbpf-1.0.1/libbpfgo.go:411 +0x1d
panic({0x1ce3ce0, 0x3128b10})
runtime/panic.go:890 +0x262
github.com/aquasecurity/libbpfgo.(*Module).GetProgram.func1(0x1fbb29c?, 0xb?) …
```
=> Fix panic due to low rlimit value

README.md, bpf/cpu/cpu.bpf.c, cmd/parca-agent/main.go, pkg/profiler/cpu/cpu.go
This commit:
- enables DWARF-unwinding by default, adding a flag to opt-out `--disable-dwarf-unwinding`;
- adds on-demand unwind table generation using the information provided by the BPF program when it can't unwind the stack using FPs and the unwind information isn't found;
- adds a new flag, `--dwarf-unwinding-use-polling` to produce the unwind tables ahead of time, if desired;
Notes
=====
I expect the CPU usage to be slightly lower thanks to not generating unwind info ahead of times for processes that perhaps will use no CPU.
Some stacks fail due to not following the ABI. This needs more investigation but seems related to the way Go grows goroutines stacks. This might cause many events to produce unwind tables to be sent, but this should not be a problem as the Go binary detection is …
=> .eh_frame: Enable DWARF-based unwinder by default

README.md, bpf/cpu/cpu.bpf.c, cmd/parca-agent/main.go, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/cpu_test.go
The current logging is very comprehensive and helpful during debugging but it's a waste of cycles to always log in production. Besides efficiency, logging so much is a bit antisocial too, as engineers using BPF logging facilities in other applications or debug tools will get flooded with Parca's logs.
Additionally, while some additional branches might not have a big perf hit, modern kernels will completely remove the branch that test whether debug is enabled or not.
Test Plan
=========
With
```
--verbose-bpf-logging
```
logs are shown, without it, just the stats:
```
irb-11693   [002] d.h2.  4845.737945: bpf_trace_printk: [[ stats for cpu 2 ]]
irb-11693   [002] d.h2.  4845.737947: bpf_trace_printk:    success=130
irb-11693   [002] d.h2.  4845.737947: bpf_trace_printk: …
```
=> bpf: Make logging opt-in

bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/maps.go
By not writing the field that we will use in arm64 for the saved return address which is not needed in x86_64. This saves 2 bytes, going from 16 to 14 bytes.
Test Plan
=========
No errors with `--verbose-bpf-logging`
```
[javierhonduco@fedora parca]$ sudo bpftool prog tracelog  | grep err
```
=> bpf: Make unwind row size ~12% smaller

bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/maps.go
- Rename incorrectly named shards to chunks;
- Remove struct names, they are unused;
- Create a new error for unsupported frame pointer operations;
Test Plan
========
Ran the Agent, profiles are correct:
```
[javierhonduco@fedora parca-agent]$ sudo bpftool prog tracelog   | grep -E "\[(err|unsup)"
```
=> bpf: Various clean ups

cmd/parca-agent/main.go, pkg/hsperfdata/hsperfdata.go, pkg/metadata/java_process.go, pkg/perf/perf.go, pkg/perf/perf_test.go
Fixes: #1306 
Java Hotspot VM provides telemetry data through jvmstat performace counters and publishes it through a memory-mapped file in a temp directory /tmp/hsperfdata_{user}/{pid}. Currently, in parca-agent there is no way to determine if a certain process is a Java process. So above naming convention will help us to find running Java processes in the system as well as add it as a metadata.
Proposed PR does the following things:
- For the given pid it searches in the global /tmp/ directory first to check in case process is being run on a host
- If not then it searches for the associated NSPid to find the hsperfdata file associated with the pid
- It also adds a new metadata label 'java', see #1366 for more details 
Output from `jps`:
Parca-agent output for the process running on host: …
=> Discover java processes via hsperfdata

bpf/cpu/cpu.bpf.c
We have kernel tests that will ensure that we don't add helpers that cause regressions.
Additionally, there are many other sources of BPF loading issues, beyond helper usage, such as using of global variables, etc
=> bpf: Remove comment warning on helpers

bpf/cpu/cpu.bpf.c, kerneltest/vmtest.sh, pkg/profiler/cpu/maps.go
While the current limit is enough for most applications, there are some behemoths out there, looking at you, gnome-shell, that bring more than 150 mappings.
Let's bump the maximum mappings so we can support many other processes. This increases our memory footprint and it's something we will be looking to optimise in the future.
Note that we still perform a linear search over the array of mappings. We'll also measure the impact of switching this to other searching algorithms and decide if it's worth changing it.
Test Plan
=========
Ran the agent for 30 mins without any issue, 100% of the firefox stacks were collected https://pprof.me/9a8a8c3
```
=============
Test results:
=============
- ✅ 5.4
- ✅ 5.10
- ✅ 5.18
- ✅ 5.19
```
=> bpf: Bump max mappings per process to 250

pkg/profiler/cpu/maps.go, pkg/stack/unwind/maps.go, pkg/stack/unwind/maps_test.go
Reported by an user after seeing a bunch of errors in their production cluster such as:
```
elf.Open failed: bad magic number '[68 84 105 74]' in record at byte 0x0"
```
They graciously provided the mappings for this process, and this one stood out:
```
7f6c903cc000-7f6c903cd000 r-xp 00000000 08:01 403978                     /tmp/jit-11.dump
```
This commit also adds extra context to the logs to make it easier to debug these issues in the future.
=> unwinding/native: Ignore jitdump sections

.gitignore, .pre-commit-config.yaml, CONTRIBUTING.md, flake.lock, flake.nix, nix/devshell.nix, nix/go-tools.nix, renovate.json, shell.nix
This uses the experimental `nix develop` command with Nix Flakes, this way we can use the unstable channel to get the latest packages and lock its revision with ease (Renovate has support for Nix Flakes). I made the list of packages more exhaustive as well.
`nix-shell` is still usable for now thanks to the [flake-compat](https://github.com/edolstra/flake-compat) module.
=> chore: migrate to `nix develop`

bpf/cpu/cpu.bpf.c
This is useful while debugging multi-threaded applications. Note that we are printing the userspace process ID, or kernel thread ID.
=> bpf: Print PID on unwind info requests

pkg/profiler/cpu/cpu.go
libbpfgo changed [[0]] the way it handles libbpf logs and right now they are being printed by default. This commit reroutes these logs as debug logs in our logging facilities
[0]: https://github.com/aquasecurity/libbpfgo/commit/fde1f6e5ba094d1bceb68b3e6ab038832a44bd8b
=> bpf: Use our logger for libbpf logs

cmd/parca-agent/main.go, go.mod, go.sum, pkg/discovery/systemd.go
Hi! I would like to share some of the results I got with https://github.com/marselester/systemd. ~~There are still things I need to finish though...~~
The current version of `discovery.SystemdDiscoverer` makes use of 1.1 MB/op and 32,332 allocs/op to get a list of systemd services along with their PIDs. That accounts for 40% of CPU cycles in the agent, excluding the GC time, see https://pprof.me/e711789. The proposed change gets 13.96 KB/op and 30 allocs/op.
```
BenchmarkSystemd-2    	       1	1001314916 ns/op	 1163552 B/op	   32332 allocs/op
BenchmarkSystemd2-2   	       1	1003780290 ns/op	   14304 B/op	      30 allocs/op
```
I ran the benchmarks as follows:
- temporarily removed `pkg/discovery/kubernetes.go` or else tests won't run `github.com/parca-dev/parca-agent/pkg/cgroup: build …
=> pkg/discovery: systemd discoverer with less allocs

bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/bpf_metrics.go, pkg/profiler/cpu/maps.go, pkg/profiler/cpu/metrics.go
The unwinder stats that we have been logging using BPF's printing facilities have been very useful during the development of the DWARF-based unwinder. It has surfaced areas of improvement and bugs.
This commit exports the counters via Prometheus so our users and ourselves can track how the native unwinder is doing.
In this commit, there are some other changes:
- Grouped the statistics to a single struct to be able to read the whole struct at once;
- Before, the JIT samples that we are dropping weren't accounted properly if the first frame was already JIT'ed;
Note that these metrics will always be inherently racy and the sum of success + failure might be slightly different than the total sample count. For more context, check out the comment in `metrics.go`.
Notes
=====
Just to reiterate …
=> unwinder/native: Export metrics

bpf/cpu/cpu.bpf.c, pkg/address/normalizer.go, pkg/process/mapping.go, pkg/process/maps_test.go, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go, pkg/profiler/profiler.go
This commit starts the work on increasing the chances of success when profiling short-lived processes.
Among other things:
- populate the mappings cache on-demand to be able to normalize and find the build ids for processes that exit before we collect this information;
- we will now drop samples that contained frames that failed to normalize;
- reduced the unwind info batch deadline from 250 to 150 ms to increase the chance of profiling short-lived processes;
This commit doesn't tackle:
- symbolisation of short-lived processes. See comment in cpu.go;
- DWARF-based unwinding for processes that run for less than 150ms;
- improvements to how the mappings are cached;
- single stray frames that require more investigation;
- configurable batch deadlines;
- adding an eviction strategy for the …
=> *: Populate process mappings on-demand

pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/metrics.go
- Add prometheus metrics for sucess and errors;
- Skip stacks that contain frames that failed to normalize;
Test Plan
=========
```
$ curl --silent http://localhost:7071/metrics | grep parca_agent_profiler_normalization_attempts_total
parca_agent_profiler_normalization_attempts_total{status="error",type="cpu"} 3
parca_agent_profiler_normalization_attempts_total{status="success",type="cpu"} 2028
```
=> profiler: Improve normalization errors handling

bpf/cpu/cpu.bpf.c
We've seen a lot of single frame stacks that aren't corresponding to any
bottom frame such as `_start`, `__libc_start_main_impl`, `start_thread`,
or `runtime.goexit`, in the case of Go.
After some debugging, it looks like some applications compiled without
frame pointers have zero as their frame pointer, tripping our checks.
While this is completely valid, and perhaps a better check would be to
stop walking the stack once we've reached its end, most of the instances
for this problem show as a single frame. Theoretically it could be any
number of frames until finding `rbp=0`.
This commits implements a heuristic to work around this issue. Any
process that's been compiled normally will have at least two frames, so
let's drop samples that only contain one and generate unwind tables for
them …
=> unwinder/native: Discard stacks with just one frame

.github/workflows/build.yml
We are seeing failures with
```
Fetched 37.7 MB in 10s (3639 kB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/p/pulseaudio/libpulse0_15.99.1%2bdfsg1-1ubuntu2_amd64.deb  404  Not Found [IP: 52.250.76.244 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/ceph/librados2_17.2.0-0ubuntu0.22.04.2_amd64.deb  404  Not Found [IP: 52.250.76.244 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/ceph/librbd1_17.2.0-0ubuntu0.22.04.2_amd64.deb  404  Not Found [IP: 52.250.76.244 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
> Note: Always run sudo apt-get update before installing a package. In case the apt index is stale, this command fetches and re-indexes any available packages, …
=> vmtest: Update packages

pkg/profiler/cpu/cpu.go
This somehow slips through, my bad. This is not correct. The issue shows up if no other executables end up triggering a persist of the unwind table
=> pkg/profiler/cpu: Fix condition for RequestUnwindInformation

pkg/discovery/systemd.go, pkg/discovery/systemd/client.go, pkg/discovery/systemd/config.go, pkg/discovery/systemd/decoder.go, pkg/discovery/systemd/header.go, pkg/discovery/systemd/header_test.go
Javier found a bug in systemd package which occurs when the header decoder receives a corrupted dbus message, see https://github.com/parca-dev/parca-agent/issues/1511.
```
github.com/parca-dev/parca-agent/pkg/discovery/systemd.(*Client).ListUnits(0xc000b08000, 0xc000a8aba0?, 0xc000191a00?)
github.com/parca-dev/parca-agent/pkg/discovery/systemd/message.go:159 +0x99
github.com/parca-dev/parca-agent/pkg/discovery/systemd.(*messageDecoder).DecodeListUnits(0xc00074c4b0, {0x231d880?, 0xc000b08060}, 0x33bea80?, 0xc001361a48)
github.com/parca-dev/parca-agent/pkg/discovery/systemd/header.go:126 +0x149
github.com/parca-dev/parca-agent/pkg/discovery/systemd.decodeHeader(0xc000b06030, 0x206bad6?, 0xc00074c578, 0x1)
goroutine 88 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 …
```
=> pkg/discovery: Fix panic when systemd gets corrupted header

pkg/debuginfo/extract.go, pkg/debuginfo/extract_test.go, pkg/debuginfo/manager.go, pkg/debuginfo/manager_test.go
Previously the `stripDebuginfo` field was constantly overridden by whether or not the given binary had a text section or not, which lead to disregarding if stipping debuginfos was explicitly turned off.
Additionally, this was unsafe as it was overriding the global configuration, which could have been written concurrently.
=> pkg/debuginfo: Fix extraction logic

pkg/cache/stats_counter.go, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go
* prevent the panics when we try to retry with a different number of shards
=> Merge release v0.17.2

scripts/download-async-profiler.sh
Initially we thought that fdtransfer is not needed. But as libasyncprofiler.so gets loaded as an agent in JVM, we can't be sure about the privileges of the running Java process(on both host and containers). Luckily, async-profiler already has a small program called 'fdtransfer' to deal with such issues and access perf_event_open. So let's use it!
See [https://github.com/async-profiler/async-profiler#troubleshooting](async-profiler-troubleshooting) for more details.
Move fdtransfer to target directory from the fetched async profiler tarball.
Java process running on the host without root privileges:
```
vaishali@pop-os:~/parca-agent$ jps
510479 Jps
510333 spring-two-0.0.2-SNAPSHOT.jar
```
Running `profiler.sh` without  fdtransfer
```
root@pop-os:~# /home/vaishali/async-profiler/profiler.sh …
```
=> Move fdtransfer to target directory

README.md, cmd/parca-agent/main.go, pkg/profiler/cpu/cpu.go
As it's not used or tested anymore, we rely on the on-demand unwind info generation.
Test Plan
=========
Ran the agent for a little while without issues
=> unwinder/native: Remove polling mode

pkg/profiler/cpu/cpu.go
pkg/profiler/cpu: Log address in hex for normalization errors
=> pkg/profiler/cpu: Log address in hex for normalization errors

cmd/parca-agent/main.go, pkg/ksym/ksym.go, pkg/ksym/ksym_test.go, pkg/ksym/optimizer.go, pkg/ksym/optimizer_test.go
Context
======
There are several use-cases, such as symbolization, that conceptually boil
down to a list of tuples, each formed of an identifier and a string, where
we want to efficiently find the string for a particular identifier.
A possible approach to solve this problem is to create a large list
in memory, sorted by identifier, so we can binary-search over the ids
and find the entry for which entry_i.Id <= Id < entry_i+1.Id.
While this works well and it's easy to understand and maintain, when
the list grows too large, this can be a large source of retained memory.
This issue is particularly bad when memory offloading (swap/zswap) is not
enabled, as the "cold" anonymous memory won't have a way to be moved to
secondary storage.
This implementation produces a simple binary format that's …
=> ksym: Introduce disk-based symbolizer

bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go
Right now we always allocate 5k entries in `debug_pids` in kernel memory even if the filter mode `--debug-process-names` is not enabled. Let's only allocate the entries if we are filtering processes.
The saved memory isn't too much, around a few KB, but kernel memory is precious and in particular this memory, as it's locked.
Test Plan
=========
**no filters**
```
[javierhonduco@fedora parca-agent]$ sudo bpftool map | grep debug_pids -A3
739: hash  name debug_pids  flags 0x0
key 4B  value 1B  max_entries 1  memlock 4096B
btf_id 670
pids parca-agent-deb(154991)
```
**with filters**
```
[javierhonduco@fedora parca-agent]$ sudo bpftool map | grep debug_pids -A3
765: hash  name debug_pids  flags 0x0
key 4B  value 1B  max_entries 5000  memlock 40960B
btf_id 697
pids parca-agent-deb(156286)
```
=> profiler: Reduce mem usage in maps with no filters

pkg/asyncprofiler/asyncprofiler.go
As part of the ongoing work for #1510, this PR adds a go package to load the `libasyncprofiler.so` via `jattach`. It also loads `fdtransfer` to deal with the java processes with limited privileges.
**Test Plan:**
[This](https://github.com/parca-dev/parca-agent/pull/1590) toy program has been used to check the basic functionality provided by this package.
**Output of the above program:**
```
vaishali@pop-os:~/parca-agent$ ./asyncprofiler-test
paths are ok
fdtransfer server is running
Server ready at '59064'
context is ok
command is ok
start output is ok
stop output is ok
```
Note: The function `NewAsyncProfiler` only provides the basic functionality at the moment so that we can test the other functions. It will be reworked as part of #1508 to provide the fully functional API that can be …
=> Add Go package to interact with libasyncprofiler

.golangci.yml
I keep seeing the following warnings when running `make go/lint`:
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'ifshort' is deprecated (since v1.48.0) due to: The repository of the linter has been deprecated by the owner.
Disable deprecated linters.
I'm not sure if renovate bot handles this usually. But let me know if we would prefer some other way to get around these warnings rather than …
=> chore: Disable deprecated linters

pkg/asyncprofiler/asyncprofiler.go
In preparation of the separate package for the per process asyncprofiler, refactor NewAsyncProfiler by removing the options parameter and utilizing functional options instead. Also, use SetAction function to accept functional options, as these options are more tied to the actions and we can leave the decision of using particular options on users.
This is more convenient and easier to use for testing as well.
See updated #1590 for the intended use.
Before when start and stop commands were executed:
```
Executing command: /home/vaishali/parca-agent/pkg/asyncprofiler/testdata/jattach 43220 load /home/vaishali/parca-agent/pkg/asyncprofiler/testdata/libasyncProfiler.so true start event=cpu duration=60s file=prof.jfr
Executing command: …
```
=> pkg/asyncprofiler: Refactor NewAsyncProfiler to use functional options

pkg/asyncprofiler/asyncprofiler.go
The expected format of the command is:
`jattach pid load libasyncProfiler.so true start,event=cpu,file=prof.jfr`.
Current code doesn't add the semicolon while building a command. Fix this as part of the options format.
This commit also improves the code to handle the situation when we have multiple ProfilerOptions maps.
Result of the current #1590 
```
vaishali@pop-os:~/parca-agent/pkg/asyncprofiler$ go test
Executing command: /home/vaishali/parca-agent/pkg/asyncprofiler/testdata/jattach 9771 load /home/vaishali/parca-agent/pkg/asyncprofiler/testdata/libasyncProfiler.so true start,event=cpu,file=prof.jfr
Executing command: /home/vaishali/parca-agent/pkg/asyncprofiler/testdata/jattach 9771 load /home/vaishali/parca-agent/pkg/asyncprofiler/testdata/libasyncProfiler.so true stop
PASS
ok …
```
=> pkg/asyncprofiler: Fix options format in SetAction

go.mod, go.sum, pkg/profiler/cpu/cpu.go
Upgrade libbpfgo to [v0.4.8-libbpf-1.2.0.0.20230509162948-80f41e18e690 from v0.4.7-libbpf-1.2.0-b2e29a1](https://github.com/aquasecurity/libbpfgo/compare/80f41e18e690..b2e29a1).
libbpf was bumped from [6597330c45d185381900037f0130712cd326ae59 to fbd60dbff51c870f5e80a17c4f2fd639eb80af90](https://github.com/libbpf/libbpf/compare/b2e29a10265eff85afa61b11c9588f49111df79a..fbd60dbff51c870f5e80a17c4f2fd639eb80af90)
Test Plan
=======
Ran it for a little while + tests are all green
=> Upgrade libbpfgo to `80f41e18e690`

.golangci.yml
We no longer have arguments package after #1518. Remove exclude-rules for it in the CI.
=> chore: Remove exclude-rules for the arguments pkg

pkg/perf/parsehexuint.go, pkg/perf/perf.go
Avoid allocations and remove unnecessarily generic functions for parsing memory addresses.
```
benchstat old.txt new.txt
name             old time/op  new time/op  delta
PerfMapParse-10  5.62µs ± 1%  3.86µs ± 1%  -31.21%  (p=0.000 n=10+10)
```
I think there is still quite a bit more improvement possible, like using a btree instead of a regular slice (since we want it to be sorted afterward), and reusing/pooling buffered readers.
=> pkg/perf: Optimize perf map parsing

pkg/address/normalizer.go, pkg/process/maps.go, test/integration/profiler_test.go
Addresses written to "perf maps" or jitdump are absolute to the processes, so currently symbolization is broken.
This the first step to unblock the broken JIT symbolization. There is more work to do, will open an issue to track this.
Test Plan
=========
The current integration tests `make test/profiler` pass. Will add an integration test once we have the mixed-mode unwinder ready.
=> Do not normalize addresses from JIT'd code

test/integration/profiler_test.go
@kakkoyun reported that on his box the integration tests fail because the bottom frames set up by the loader are different. This commit removes those as they are an implementation detail and might change at any time. Now we only assert the symbols we have control over.
Another nuisance was that if a test failed, the result was not very user friendly. Now the stack we are trying to find if it's contained in a slice of stacks will both be printed if the assertion fails:
Test Plan
=========
`$ make test/integration`
**happy path worked**
**bad assertion works too**
```
=== RUN   TestCPUProfilerWorks
profiler_test.go:343: The stack [top2() c2() b2() a2() not_main] is not contained in any of [[top2() c2() b2() a2() main __libc_start_call_main __libc_start_main_alias_2] [top2() c2() b2() a2() …
```
=> tests/integration: Improve assertions

go.mod, go.sum, pkg/profiler/cpu/bpf_metrics_collector.go
As this is causing issues in some AMD CPUs. For context: https://github.com/parca-dev/parca-agent/issues/1696#issuecomment-1568736923.
Note: This should never be used in perf_event_open(2) as it will fail in the CPUs that are overreported by some AMD systems.
Fixes https://github.com/parca-dev/parca-agent/issues/1696
=> Use libbpf's cpu number helper

test/integration/profiler_test.go
As it was checking containment within the profile, not within the profile's stacks. This is important because some different Go versions might have slighly different frames, in CI sometimes we see:
```
profiler_test.go:380: The stack [time.Now main.main] is not contained in any of [[time.Time.After runtime.main runtime.goexit.abi0] [time.now time.Now main.main runtime.main runtime.goexit.abi0] [time.now time.Now main.main runtime.main runtime.goexit.abi0] [time.now time.Now main.main runtime.main runtime.goexit.abi0] [time.now time.Now main.main runtime.main runtime.goexit.abi0] [time.now time.Now main.main runtime.main runtime.goexit.abi0] [time.now time.Now main.main runtime.main runtime.goexit.abi0] [time.now time.Now main.main runtime.main runtime.goexit.abi0] [time.now time.Now …
```
=> tests/integration: Fix stackContains

.gitignore, cmd/parca-agent/main.go, go.sum, pkg/objectfile/object_file.go, pkg/objectfile/pool.go, pkg/process/info.go, pkg/profiler/cpu/cpu.go
* Add WorkerPool to the hot path
* Prevent excessive allocation on the hot path.
Previously, we were constantly re-creating goroutines for each event we received from the kernel.
This PR introduces a worker pool on the hot path to prevent constant routine creation.
It also avoids creating a new task if there is an in-flight one. 
As one last optimization, it uses a `sync.Pool` to avoid re-allocating the jobs (previously, we have seen many closure creations in the profiles).
Moreover, it uses a similar strategy to ensure we do not create an upload request if there's already something in-flight.
Even though previously we made sure there was only one upload request in-flight at a time, we were creating a lot of blocked goroutines.
1. make …
=> *: Avoid constant recreation of goroutines

pkg/process/info.go, pkg/process/maps.go, pkg/profiler/cpu/cpu.go
And expire the process info cache after-write to make sure we refresh.
=> Do not cache process info if we failed to read a mapping

README.md, cmd/parca-agent/main.go, pkg/objectfile/object_file.go
It's possible on machines that create a lot of very short lived processes to evict an object file from the pool before it was possible to be used. In these cases the best solution is to increase the object pool size since not increasing it would lead to extremely high cache misses which would also be very bad.
#1798 
Increase the default object file pool (128 seemed extraordinarily low) and add instructions to the panic output what to do in this case.
We could also return an error, however, it is likely that incorrect data would be produced, so I felt it is better to fail and be a bit more forcing to the user to update the value to something better that will work for their environment.
n/a
=> Increase default object file pool size and improve error

.github/workflows/container.yml, .github/workflows/release.yml, .github/workflows/snap.yml, .goreleaser.yml, Makefile, bpf/Makefile
We want to publish arm64 images and they're currently broken.
Fix builds.
Always building BPF code for arm64 and amd64 and choosing the right one to include in the static binary.
This fixes CI so the only way to test is to run CI.
=> *: Fix arm64 builds to choose correct BPF file

.github/workflows/container.yml, .github/workflows/release.yml, .github/workflows/snap.yml, .goreleaser.yml
I noticed in several CI runs that we have various log lines mentioning that pkg-config is not available.
=> .github: Install pkg-config

.github/workflows/container.yml, .github/workflows/release.yml, .github/workflows/snap.yml, .goreleaser.yml, Makefile, pkg/profiler/cpu/cpu.go, test/integration/profiler_test.go
They are small so it doesn't make much of a difference and unfortunately the build tooling otherwise keeps overriding the compiled BPF programs.
=> Always include all architectures of BPF programs

Makefile
As the wrong arch will result in broken builds until these files are removed
Test Plan
=========
**before**
```
export ARCH=LOL
make
make clean
make
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CC="clang" CGO_CFLAGS="-I/home/javierhonduco/code/parca-agent/dist/libbpf/amd64/usr/include" CGO_LDFLAGS="-fuse-ld=ld -lzstd /home/javierhonduco/code/parca-agent/dist/libbpf/amd64/libbpf.a" go build  -tags osusergo,netgo -mod=readonly -trimpath -v --ldflags="-extldflags=-static" -o dist/parca-agent ./cmd/parca-agent
pkg/profiler/cpu/cpu.go:55:13: pattern bpf/*: cannot embed directory bpf/LOL: contains no embeddable files
```
=> build: Clean generated BPF object files

deploy/dev.jsonnet, deploy/e2e.jsonnet, deploy/jsonnetfile.lock.json, deploy/lib/parca-agent/parca-agent.libsonnet
Make PSP optional and disable it by default `Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+`
For PSP:
- I have followed https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/ as much as possible.
- Also adds a namespace with admission control for development: https://kubernetes.io/docs/tutorials/security/cluster-level-pss/
- https://jamesdefabia.github.io/docs/user-guide/security-context/
For Capabilites:
- https://man7.org/linux/man-pages/man7/capabilities.7.html
- https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
ref: https://github.com/parca-dev/parca/pull/3142
=> deploy/jsonnet: Make PSP optional

bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/cpu.go, pkg/stack/unwind/executable.go
We can't unwind nodejs and other v8-base applications as we can't continue unwinding after the first AoT frame:
```
[...]
current pc: 7fb0cf84904a
current sp: 7fff93701498
current bp: 7fff937014d8
[debug] Unwinding JITed stacks
[debug] Within unwinding machinery loop
current pc: 157a329
current sp: 7fff937014e8
current bp: 7fff93701548
~about to check shards found=1
~checking shards now
[info] found chunk
le offset: 0
========== left 0 right 249997
.done
=> table_index: 206094
=> adjusted pc: 157a329
cfa type: 4, offset: 0 (row pc: 156f656)
[info] PC 157a329 not contained in the unwind info, found marker
[warn] mapping not added yet rbp 7fff93701548
pid 227936 tgid 227936
```
Turns out this AoT function doesn't have the corresponding DWARF unwind information:
```
$ dist/eh-frame …
```
=> Use frame pointer unwinding for v8-based application

README.md, cmd/parca-agent/main.go
Fixes https://github.com/parca-dev/parca-agent/issues/1854
=> cmd/parca-agent: Bind debug endpoint to localhost only by default

pkg/profiler/cpu/cpu.go
This caused any process to only report on a single thread per profile cycle, which resulted in incorrect profiling data.
Main (only single thread stack traces per profile) :
Patch (multiple thread stack traces per profile):
=> pkg/profiler/cpu: Fix noop due to value struct

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, Makefile, env.sh
Govulncheck provides a low-noise, reliable way for Go users to learn about known vulnerabilities that may affect their dependencies. 
See details on Go's support for vulnerability management:
https://go.dev/blog/govulncheck
https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
https://github.com/marketplace/actions/golang-govulncheck-action
=> Add govulncheck

deploy/lib/parca-agent/parca-agent.libsonnet
Liveness probes are dangerous: https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html
=> deploy: Remove liveness probe

pkg/convert/jfr.go, pkg/convert/jfr_test.go
the old logic could not process native method.
i need the file name to connect source code and pprof.
support native method and add file name.
support native method:  see https://github.com/async-profiler/async-profiler/blob/master/src/converter/jfr2pprof.java#L188
connect source code and pprof:
1, uncompress jar file
2, decompile jar file in ./BOOT-INF/lib
3, rewrite java file 
example:
decompile jar file
```
mkdir src && cd src && jar xf /Users/jie.yang05/Downloads/risk_management_web.web.jar
wget https://github.com/intoolswetrust/jd-cli/releases/download/jd-cli-1.2.0/jd-cli-1.2.0-dist.tar.gz && tar xvf jd-cli-1.2.0-dist.tar.gz
java -jar jd-cli.jar --displayLineNumbers ./BOOT-INF/lib/kafka-clients-2.5.0.jar --outputDir ./
cd org/apache/kafka/clients
```
the java file could not directly …
=> Feature/convert: Add filename and support native method

pkg/convert/jfr.go, pkg/convert/jfr_test.go
in my company, the jfr to pprof allocate too much times of objects, and those cost most of cpu.
this is the allocation memory profile of my parca-agent:
this pr reduce 99% percent of memory allocation and reduce 80% of cpu cost in jfr to pprof.
1, cache parseArgs and getFileName and getPid and dimensions.
2, reuse slice as more as we can.
3, use bytes.buffer to build function key, and use unsafe string in map search to avoid memory allocation.
4, use unsafe string sample key in map search, only create locations when new sample created.
5, use uint64 as location key to avoid int to string convert.
=> pkg/convert: reduce allocation

pkg/process/maps.go
These patterns are already used to prevent main binaries from being opened, but were forgotten for other object files of mappings.
=> pkg/mapping: Add more patterns for mappings not to open

go.mod, go.sum, pkg/analytics/analytics.go, pkg/analytics/remote_write.go, pkg/runtime/elf_symbols.go, pkg/runtime/python.go, pkg/runtime/ruby.go, pkg/runtime/v8.go, pkg/stack/unwind/executable.go
Before this patch searching symbol tables allocated a lot of memory in one allocation which caused heap to spike dramatically at the start.
Same strategy as in https://github.com/xyproto/ainur/pull/5
Remove big bulk allocation. 
Haven't tested other than compiling.
=> pkg/runtime: Prevent allocations from searching symbol tables

bpf/cpu/cpu.bpf.c
Fixes https://github.com/parca-dev/parca-agent/issues/1880, which contains more details, but the summary is that this commit and greater prevent our code to load.
```
Author: Eduard Zingerman <eddyz87@gmail.com>
Date:   Tue Jun 13 18:38:23 2023 +0300
bpf: Verify scalar ids mapping in regsafe() using check_ids()
```
I am not super sure of all the effects of that commit above, but it seems that perhaps the verifier is accounting for more execution paths, increasing the number of instructions that's analysing, making it go over the threshold.
This is remediated by reducing the number of instructions we have per program. Before we packed as many iterations of the main loop as we could, which now we have to reduce.
A possible side-effect is that for very large stacks we'll have to run more …
=> Fix "BPF program too large" error in kernel release 6.4 and greater

pkg/convert/jfr.go
have a bug in create sample locations.
it is not correct to range over []byte to get location id.
add field locations and reuse it, deep copy when create new sample.
=> pkg/convert: fix locations

snap/hooks/configure, snap/local/parca-agent-wrapper
Add a config option to the Parca Agent snap to simplify the onboarding of agents to Parca Cloud.
This change introduces a new snap config option named `remote-store-bearer-token`, and changes the default store address to `grpc.polarsignals.com:443`. The change to default store address will only affect new installs.
```
sudo snap install --classic parca-agent
sudo snap set parca-agent remote-store-bearer-token=<token>
sudo snap start parca-agent
``` 
- Download the snap artefact from the CI pipeline and install with `sudo snap install --classic --dangerous ./<path-to-snap`
- Generate a new Parca Cloud token
- Run `sudo snap set parca-agent remote-store-bearer-token=<token>`
- Run `sudo snap start parca-agent`
- Verify that profiles are arriving on Parca Cloud.
/cc: @brancz
=> feat(snap): add config option for remote store token

Makefile
As it's slow. We should run it in a CI job and report back via email.
=> build: Do not run vulncheck on make lint

.github/workflows/build.yml, test/integration/profiler_test.go
aka JIT <-> DWARF unwinding. This also tests that the symbolization using
perfdump works.
Also changed the running time for the profiler during non-CI runs to
reduce feedback cycles.
=> tests: Add integration tests for mixed-mode unwinding

.github/workflows/build.yml, Makefile, bpf/.clang-format, bpf/Makefile, bpf/cpu/basic_types.h, bpf/cpu/common.h, bpf/cpu/cpu.bpf.c, bpf/cpu/rbperf.bpf.c, bpf/cpu/rbperf.h, bpf/cpu/shared.h, go.mod, go.sum, pkg/pprof/pprof.go, pkg/process/info.go, pkg/profile/profile.go, pkg/profiler/cpu/bpf_metrics_collector.go, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/cpu_test.go, pkg/profiler/cpu/maps.go, pkg/rbperf/headers.go, test/integration/profiler_test.go
This commit adds initial Ruby support by integrating rbperf's unwinder
and adapting it to this Agent.
There is more work to do, but in the spirit of keeping this commit a bit
more contained, right now:
- only Ruby 3.0.4 is supported;
- no focus on efficiency;
- missing clean-ups (such as clearing the interpreter stack maps);
- the Ruby stack is fetched even if the Ruby thread is sleeping as long
as the native stack is on-CPU. This shows up confusingly as the Ruby stack in
many native stacks that aren't actually running the Ruby code;
- there are no integration tests, this will change soon;
All the shortcomings above, and then some, will be addressed in
forthcoming commits.
Architecture
============
The current BPF unwinding architecture as well as the changes that this
commit makes can be …
=> Add initial Ruby support

cmd/parca-agent/main.go
This was previously discussed in
https://github.com/parca-dev/parca-agent/pull/719.
While ideally we could check for the individual capabilities this is fraught with issues: different kernel revisions might require different capabilities, over time we are adding new features that might require or drop the needed capabilities, and in general, capabilities don't seem to be a feature that many users are intimately familiar with.
Checking for the superuser is a reasonable thing to do as it will ensure we can run, and it's how every single deployment that we know of executes this software.
We can always re-evaluate this in the future, but in the meantime let's ensure that running the Agent does not result in surprises (https://github.com/parca-dev/parca-agent/issues/1979, but we've seen this …
=> Ensure we are running under root

pkg/perf/perf.go, pkg/perf/perf_test.go, pkg/perf/testdata/nodejs-perf-map-regression
Perf map files have fundamental race conditions between the producer and consumer and it's never guaranteed for lines to be complete or correct. Therefore we need to be more rigorous about validating lines and expecting the worst. This patch was originally triggered by a customer seeing panics with out of bounds accesses, which have been simulated in the added regression tests.
=> pkg/perf: More robust perf map parsing

.github/workflows/container.yml, .github/workflows/release.yml, .github/workflows/snap.yml, Makefile, bpf/Makefile, bpf/pid_namespace.bpf.c, cmd/parca-agent/main.go, go.mod, go.sum, pkg/contained/contained.go, pkg/profiler/cpu/cpu.go
In Linux resources such as users, processes, mounts, time, etc. can be isolated with namespaces [0]. They are used in tamden with cgroups to implement resource control in containers.
Both namespaces and cgroups are conceptually a hierarchy, where the first namespace is the root of the tree and the common ancestor for all the other slices of the machine.
The Agent requires to be run in the 'root' (this has nothing to do with permissions or users, necessarily) PID namespace, where all the other processes for every single namespace can be queried.
While the kernel does not provide a facility for this check, this commit aims to bring a reliable check to see whether we are inside of a PID namespace or not. It does it with a BPF program that retrieves the pid of the Agent and then we compare it …
=> Detect the agent running in a non-root PID namespace

pkg/perf/map.go, pkg/perf/perf.go, pkg/perf/perf_test.go
Some customers have reported some unexpected nodejs symbols.
Perfmaps are often append-only, therefore the most up to date entries are the ones later in the file. To resolve conflicts, we still sort the results, but resolve conflicts by reverse iterating over the entries and removing entries if they overlap with the "latest" entry.
Unit tests continue to pass, but it's hard to test without a real environment.
=> pkg/perf: Resolve perfmap conflicts

pkg/stack/unwind/compact_unwind_table.go
Rather than allocating new contexts.
```
$ go test -run=^$ -bench ^BenchmarkGenerateCompactUnwindTable$ github.com/parca-dev/parca-agent/pkg/stack/unwind -count=20 > new.txt
```
```
$ benchstat old.txt new.txt
name                           old time/op    new time/op    delta
GenerateCompactUnwindTable-12    23.4ms ±33%    17.2ms ±20%  -26.25%  (p=0.000 n=20+20)
name                           old alloc/op   new alloc/op   delta
GenerateCompactUnwindTable-12    12.9MB ± 0%     5.3MB ± 0%  -59.29%  (p=0.000 n=20+19)
name                           old allocs/op  new allocs/op  delta
GenerateCompactUnwindTable-12      108k ± 0%       66k ± 0%  -39.62%  (p=0.000 n=20+20)
```
**Before**
**After**
Test Plan
=========
Snapshot tests and unit tests pass. We were already reusing the context in the …
=> Reuse context in compact unwind table generation

pkg/js/symbol.go, pkg/js/symbol_test.go, pkg/pprof/pprof.go
When profiling v8 today, symbols look like this
```
JS:*o.fib testdata/external-sourcemap/index.js:1:114
```
All shoved into the function name, which prevents pprof's deduplication and ultimately makes profiling data much harder to read.
Parse JS symbols.
First split by space, then by colon `:` to separate function name, filename, line number and column number.
Wrote unit tests.
=> *: Add support for parsing v8 symbols

pkg/js/symbol.go, pkg/js/symbol_test.go
1) There were correctness issues in cases where the js symbol file name contained `node:` prefixes.
2) Perf was poor.
Fix correctness and improve perf.
```
$ benchstat old.txt new.txt
name              old time/op  new time/op  delta
ParseJsSymbol-10   164ns ± 1%    43ns ± 2%  -73.64%  (p=0.008 n=5+5)
```
Remove allocations from parsing and use base 10 specific parsing function.
Benchmark and unit tests.
=> Js symbols continued (correctness and perf)

cmd/parca-agent/main.go
Add profile store client that was removed by accident in https://github.com/parca-dev/parca-agent/commit/28f5ed1a298a0e5a3ee1e5eec9a1b25f60d46a7b
Test Plan
=========
Can see profiles now
=> Add profile store client that was removed by accident

pkg/cache/cache.go, pkg/cache/cache_with_eviction.go, pkg/cache/cache_with_ttl.go, pkg/cache/lru/lru.go
Get() modify state, for LRU bookkeeping purposes, hence we need to use a writer lock.
Stop spawning goroutines for every callback as this introduces another data race.
Test Plan
=========
The data races reported by tsan (make ENABLE_RACE=yes) are gone!
Both Kemal and myself have ran this code with a very small object pool
over night without any issues
=> pkg/cache: Fix data races

README.md, cmd/parca-agent/main.go
512 elf.Files (+ other metadata) can really balloon memory usage. Assuming
each entry is ~10 MB would result in a heap usage of at least 5 GB. Some
of our users reported 10 GB in heap usage in the pool which is
completely unreasonable.
In the future we want to update this to have an adaptive mechanism so we
can use the cache as much as possible while keeping memory usage at bay.
Right now having a pool to small will result in more files being opened,
(elf.Open) which results in lots of allocations and high CPU usage.
Hence we have a tradeoff of CPU + allocations vs heap usage.
Test Plan
=========
Ran overnight without issues.
=> Reduce size of object pool

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/jsonnet.yml, .github/workflows/pre-commit.yml, .github/workflows/release.yml, .github/workflows/snap.yml
This will cancel all previous jobs if a new commit or change is applied against a PR, tag or branch.
https://docs.github.com/en/actions/using-jobs/using-concurrency
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idconcurrency
> If you build the group name with a property that is only defined for specific events, you can use a fallback value. For example, github.head_ref is only defined on pull_request events. If your workflow responds to other events in addition to pull_request events, you will need to provide a fallback to avoid a syntax error. The following concurrency group cancels in-progress jobs or runs on pull_request events only; if github.head_ref is undefined, the concurrency group …
=> .github/actions: Only allow to run a single action on a group

bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/cpu_test.go, test/integration/profiler_test.go
The newly added rate limits increase the code size of the native unwinder. By default they are disabled, so the abstract paths that the verifier has to analyse are reduced, compared to when they are enabled.
As in Go, structs with fields that aren't explicitely named have a default value, in the case of booleans, false, this feature was disabled in unit and integration tests, working both locally and CI.
In the Agent binary we have this flag enabled by default. This worked in local testing because the kernel I run is new enough to allow for larger programs (6.4.6-200.fc38.x86_64) but both the e2e tests in CI and in our own Demo deployment, which run older kernels, the program fails to load with `Argument list too long`.
Enabled rate limiting by default in tests shows the issue before this …
=> unwinder/native: Accomodate larger program due to rate limits

go.mod, go.sum
As it can greatly reduce the amount of small memory allocations that we make (https://github.com/prometheus/procfs/releases/tag/v0.12.0).
The two genSplit stacks will be gone after this PR lands.
Test Plan
=========
CI
=> deps: Upgrade prometheus/procfs

CONTRIBUTING.md, README.md, docs/design.md, docs/security.md
Related: #1769
According to [this](https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md), 5.4 only introduces `BPF_MAP_TYPE_DEVMAP_HASH` for eBPF. Any explanation for why requiring 5.4 instead of the original 4.18+(e.g. Almalinux 8.7 would be excluded)?
=> docs: update kernel minimum requirement

pkg/process/maps.go
https://github.com/parca-dev/parca-agent/commit/bca32f5267342fcbf70274d0743fdd00fe6e684e introduced an optimisation to just append the executable mappings to the slice, but we are still preallocating it with the original size including non-executable mappings.
=> pkg/process: Do not overallocate executable maps

bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/cpu_test.go
The name of PID (process ID) and TID (thread ID) in the kernel vs. in userspace is different, which is a bit confusing [0].
We tried to be careful here, but in some cases we used the "per thread ID" (using this name for clarity's sake) when we should have used the "per process ID". While I don't believe this caused any correctness issues, it will add overhead for multi threaded applications. For example, in `process_info` we keep a mapping of "per process ID" to the process information, which among other things, it contains the executable mappings of the process, so we can find the current object we are executing. Having this "per thread ID" is redundant, as every sibling thread has the same memory mappings as they share the same address space.
With these changes we will reduce CPU usage …
=> bpf: Fix task identifier usage

cmd/parca-agent/main.go, pkg/kernel/version.go, pkg/kernel/version_test.go, pkg/profiler/cpu/cpu_test.go
Releases >=5.19 && <6.1 have a pretty bad kernel bug that can result in whole sytem lock ups that can only be fixed with a reboot (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1033398).
The fix got backported to -stable
(https://www.spinics.net/lists/stable/msg662452.html, and https://www.spinics.net/lists/stable/msg662218.html for 6.1 and 6.3 respectively).
Let's not run the Agent in these kernels, but provide a flag to bypass this check. Note that running a buggy kernel can result in your machine going down.
Related issue: https://github.com/parca-dev/parca-agent/issues/1675
Test Plan
=========
Tested locally + added unit tests
=> Add check for known kernel issues

pkg/profiler/cpu/bpf/maps/maps.go, pkg/stack/unwind/compact_unwind_table.go, pkg/stack/unwind/compact_unwind_table_test.go
Remove unused argument from GenerateCompactUnwindTable and ensure its benchmark is not failing.
Test Plan
=======
CI
=> pkg/stack/unwind: Remove unused argument

Makefile, cmd/eh-frame/main.go, pkg/stack/unwind/compact_unwind_table.go, pkg/stack/unwind/unwind_table.go
Final BPF tables contain all the post-processing done to them before
being loaded in the BPF maps. This PR also refactors the printing to
be reused in the compact table generation, too.
=> Add support for printing the final BPF tables

pkg/stack/unwind/compact_unwind_table.go, pkg/stack/unwind/compact_unwind_table_test.go
As we binary search over the unwind information, any neighbouring rows with the same unwind info can be summarised in just one.
This optimisation was obvious from early on and I added it back in September last year (parca-dev/parca-agent#794) but it was removed later on and never re-added.
Test Plan
=========
Snapshot tests + added unit tests
=> Remove redundant unwind rows

pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/cpu.go
See https://github.com/javierhonduco/rbperf/tree/fc31fb4c0c0cf23b1c44047b666ac502c7c05e90/src/ruby_versions
Test Plan
=========
Tested:
=> Add support for more Ruby versions

pkg/debuginfo/manager.go, pkg/elfwriter/elfwriter_test.go, pkg/elfwriter/extract.go, pkg/elfwriter/extract_test.go
The debuginfo package has dependencies to Linux only things which makes it hard to test extraction on osx. This is primarily to make development easier.
=> Move debuginfo extraction to elfwriter package

bpf/unwinders/native.bpf.c
Test Plan
=========
Tested on a `5.4.254-170.358.amzn2.aarch64` machine. Sumera is already working on the kernel tests that will catch these issues in the future.
=> Fix for 5.4 and older kernels running on arm64

.github/workflows/container.yml
Container pushing is broken on `main`. Not really sure why this ever worked.
=> .github: Use workload identity rather than hardcoded serviceaccount

bpf/unwinders/native.bpf.c
As it makes the output more obtuse. They were probably a typo.
=> bpf/native: Don't add leading newline to logs

bpf/unwinders/native.bpf.c
Probably a leftover from the previous code. We don't need to retrieve the actual stack, just to walk it.
=> unwinder/native: Remove unnecessary return address read

pkg/runtime/elf_symbols.go, pkg/runtime/python/python.go, pkg/runtime/ruby/ruby.go
https://pprof.me/beb2cec956f42f3b78f38fc2a941ffdf
Ruby: https://pprof.me/4621cebc0f971f2e0f5a8bcfce78a90b
Python: https://pprof.me/14292dfb9a915878533098f53aa9b374
=> runtime/interpreter: Check the paths first for faster and cheaper detection

bpf/unwinders/native.bpf.c, bpf/unwinders/shared.h, pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/bpf/maps/metrics.go, pkg/profiler/cpu/bpf/programs/programs.go, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/metrics.go
TL;DR: Unifying native stacks (fp, dwarf, kernel) decreases our BPF memory usage by ~70MB while reducing the amount of code. The effectiveness of stack storage and aggregation is improved and userspace might need to do less work thanks to it.
Context
=======
DWARF-derived unwinding stores its stack in a BPF hashmap where the stack hash (64 bits) is the key and the value is the stack formed by its addresses and length.
The kernel provided unwinder for user stacks with frame pointers and for kernel stacks was invoked via `bpf_get_stackid()` which only works with maps of type `BPF_MAP_TYPE_STACK_TRACE`.
This divergence led to our code needing two different maps for native stack storage, one for user code unwound without frame pointers `dwarf_stack_traces`, and another one for user code …
=> unwinder/native: Unify native stacks

bpf/unwinders/native.bpf.c, bpf/unwinders/pyperf.bpf.c, bpf/unwinders/rbperf.bpf.c, bpf/unwinders/shared.h, pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/cpu.go
A follow-up to [0] where native stacks were unified. This commit changes the interpreter stack storage to use the same storage as the native stacks, saving ~70 MB of BPF maps when the interpreters are enabled
Test Plan
=========
```
$ make && ./run-agent.sh
level=info name=parca-agent ts=2023-11-08T11:55:27.206248307Z caller=cpu.go:212 component=cpu_profiler msg="loaded rbperf BPF module"
level=info name=parca-agent ts=2023-11-08T11:55:27.208622214Z caller=cpu.go:229 component=cpu_profiler msg="loaded pyperf BPF module"
```
=> unwinder/interpreters: Unify interpreter stacks

cmd/parca-agent/main.go, pkg/metadata/labels/manager.go, pkg/metadata/runtime.go, pkg/runtime/nodejs/nodejs.go, pkg/runtime/nodejs/nodejs_test.go, pkg/runtime/python/python.go, pkg/runtime/runtime.go, pkg/runtime/vm/vm.go, pkg/stack/unwind/executable.go
The version information set in here https://github.com/nodejs/node/blob/36ecf8ca656063060421e5b5440ac056f3a51e20/src/node_version.h so they end up in `.data` or `.rodata` sections.
Tested against multiple versions https://pprof.me/75e08cdd91547a303b82065b9281bf1e
=> metadata: Add runtime labels for NodeJS

pkg/runtime/elf_symbols.go, pkg/runtime/python/python.go
First we were checking for symbols and then dynamic symbols, but we should not err if the symbol check fails due to lack of symbols.
This commit also:
- Removes Python detection via `Py_GetVersion.version`, as it's not an existing  ELF symbol (see below)
- Removes `FindAddressOfSymbol()` as it's unused.
```
$ nm --dynamic /proc/68948/root/usr/local/lib/libpython3.10.so.1.0  | grep Py_GetVersion.version
$ nm --dynamic /proc/68948/root/usr/local/lib/libpython3.10.so.1.0  | grep Py_GetVersion
000000000020ac90 T Py_GetVersion
```
"T" means that it's code , not data, so the memory ready won't work (https://linux.die.net/man/1/nm).
Perhaps in the future we could read [this constant](https://github.com/python/cpython/blob/ce1096f974d3158a92e050f9226700775b8db398/Python/getversion.c#L22) instead? …
=> python: Fix detection logic

pkg/pprof/pprof.go
interpreterSymbol might have missing entries if e.g. there was a collision in the BPF maps.
Let's insert a dummy frame in these instances
=> pprof: Fix panic while assembling interpreter's profile

pkg/pprof/pprof.go
Add missing filenames for interpreters.
e.g. `/home/kakkoyun/Workspace/Projects/parca-demo/python/fibonacci.py  +20`
=> Add filenames for interpreted functions

bpf/unwinders/native.bpf.c, pkg/profiler/cpu/cpu.go
- Buffer the channels we use in Go
- The rate limit was too strict, especially for applications that JIT compile lots of different code sections over time
We might have per event rate limits in the future if needed
=> Improve BPF events handling

cmd/parca-agent/main.go
Especially for:
```text
go_cgo_go_to_c_calls_calls_total 964683
```
=> main: Enable all Go runtime metrics

cmd/parca-agent/main.go, pkg/metadata/compiler.go, pkg/profiler/cpu/cpu.go, pkg/runtime/compiler.go, pkg/runtime/compiler_test.go, pkg/runtime/nodejs/nodejs.go, pkg/stack/unwind/executable.go, pkg/stack/unwind/executable_test.go, test/integration/profiler_test.go
- Wrap ainur.Compiler with a cache
- Control fetching throughput
Should fix the spikes we see in certain environments: https://pprof.me/0ba26790b69399ef65ea84dc3facb424/?profileType=profile%3Asamples%3Acount%3Acpu%3Ananoseconds
=> metadata: Cache and control compiler metadata fetches

.github/workflows/pre-commit.yml
* `golangci-lint` is installed by `pre-commit`
* The Go cache is already set up within `golangci-lint` cache
A follow to #1419 which was itself a follow to #1293
=> ci(pre-commit): clean up golangci-lint

nix/devshell.nix, nix/go-tools.nix
```
trace: warning: `vendorSha256` is deprecated. Use `vendorHash` instead
```
```
clang-14: error: argument unused during compilation: '--gcc-toolchain=/nix/store/hf2gy3km07d5m0p1lwmja0rg9wlnmyr7-gcc-12.3.0' [-Werror,-Wunused-command-line-argument]
```
=> chore: fix nix-shell

bpf/unwinders/pyperf.bpf.c, bpf/unwinders/rbperf.bpf.c, bpf/unwinders/shared.h, pkg/pprof/pprof.go, pkg/profile/profile.go, pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/cpu.go
- Uses `BPF_MAP_TYPE_LRU_HASH` for the symbol table. To eliminate cleaning up the map.
> Both BPF_MAP_TYPE_LRU_HASH and BPF_MAP_TYPE_LRU_PERCPU_HASH were introduced in version 4.10
- Caches the symbol table in the user space.
- Only updates the table if it encounters a new symbol ID.
It should work even better in combination with #2286 
**Before:** 
1500-2500 CGo calls pm
Metrics:
Profile:
- https://pprof.me/aebf36cac18a2f6c1725aec810ea87bc
**After:**
200-300 CGo calls pm
Metrics: 
Profile:
- [TBA](https://pprof.me/d44684fefc312522443fa1c1747a1ac1)
**Comparison**
=> Reduce number of the reads from the interpreter symbol table

pkg/runtime/nodejs/nodejs.go, pkg/runtime/nodejs/nodejs_test.go
- Use ainur.StreamReader instead of io.RuneReader
- Fix tests
<details><summary>Old</summary>
<p>
```text
oos: linux
goarch: amd64
pkg: github.com/parca-dev/parca-agent/pkg/runtime/nodejs
cpu: AMD Ryzen 9 5950X 16-Core Processor            
Benchmark_scanVersionBytes-32                100          11508930 ns/op           32162 B/op        178 allocs/op
Benchmark_scanVersionBytes-32                102          11422398 ns/op           32672 B/op        178 allocs/op
Benchmark_scanVersionBytes-32                100          11774011 ns/op           32991 B/op        178 allocs/op
Benchmark_scanVersionBytes-32                100          11629588 ns/op           32162 B/op        178 allocs/op
Benchmark_scanVersionBytes-32                102          12016436 ns/op           33038 B/op …
```
=> runtime: Use ainur.StreamReader instead of io.RuneReader

pkg/runtime/elf_symbols.go, pkg/runtime/elf_symbols_test.go, pkg/runtime/ruby/ruby.go
- Add tests and benchmarks for isSymbolNameInSection
- Optimize FindSymbol
- Integrate runtime/ruby with FindSymbol
- Use bufio.Scanner instead of regex
- Use testdata submodule
I messed up the history of https://github.com/parca-dev/parca-agent/pull/2280
<details><summary>Old</summary>
<p>
```text
goos: linux
goarch: amd64
pkg: github.com/parca-dev/parca-agent/pkg/runtime
cpu: AMD Ryzen 9 5950X 16-Core Processor            
BenchmarkFindSymbol-32               540           2727986 ns/op          687891 B/op      13820 allocs/op
BenchmarkFindSymbol-32               420           2947543 ns/op          687889 B/op      13820 allocs/op
BenchmarkFindSymbol-32               432           2974568 ns/op          687892 B/op      13820 allocs/op …
```
=> runtime: Optimize FindSymbol

go.mod, go.sum
Our current libbpf version is from early 2023.
Updates libbpfgo to https://github.com/aquasecurity/libbpfgo/commit/456a62b1184bd3da489ce6f32c46949df33f3c56 And libbpf to v1.3.0
=> Upgrade libbpfgo and libbpf

pkg/runtime/python/python.go
Not sure what conditions have to happen for this to be the case, but we've seen some suspicious panics that can be due to an empty buffer.
=> Skip empty sections

pkg/metadata/compiler.go
Previously often saw log lines like:
```
level=debug name=parca-agent ts=2023-11-29T12:43:06.00844425Z caller=manager.go:138 component=labels_manager msg="failed to get metadata" provider=compiler err="failed to get compiler info for /usr/local/bin/node: failed to open ELF file /usr/local/bin/node: error opening /usr/local/bin/node: open /usr/local/bin/node: no such file or directory"
```
=> pkg/compiler: Fix path building

cmd/parca-agent/main.go, pkg/ksym/ksym.go, pkg/perf/dump.go, pkg/perf/perf.go, pkg/perf/perf_test.go, pkg/pprof/pprof.go, pkg/symtab/symtab.go, pkg/symtab/symtab_test.go, test/integration/profiler_test.go
This patch utilizes the optimized symbol table previously only used for ksyms to move the results of parsing perfmaps and jitdumps to external memory and memory map it.
Since the overwhelming majority of symbols are never used this allows saving a large amount of memory while still keeping those that are used often in cache, which is handled by the operating system using mmap.
Holding the results of parsing jitdump/perfmaps in-memory results in unnecessarily high memory usage.
Move the result to external memory and memory map it.
Use the same optimized symbol table as we use for ksyms already.
Only unit tests so far, I will test it some more with actual workloads once merged.
=> *: Use optimized symtabs for jitdump and perfmaps

pkg/profiler/cpu/cpu.go
The err variable was clobbered so we were reading the wrong value
Test Plan
========
```
--- a/pkg/profiler/cpu/bpf/maps/maps.go
+++ b/pkg/profiler/cpu/bpf/maps/maps.go
@@ -1140,6 +1140,7 @@ func (m *Maps) AddUnwindTableForProcess(pid int, executableMappings unwind.Execu
// is challenging if the process name contains spaces, etc).
//  - PIDs can be recycled.
+       return fmt.Errorf("le error")
m.mutex.Lock()
defer m.mutex.Unlock()
```
Before:
```
msg="failed to add unwind table" pid=18846 err=null
```
After:
```
msg="failed to add unwind table" pid=18846 err="le err"
```
=> profiler: Fix error handling

.github/workflows/container.yml
```
Error: google-github-actions/auth failed with: retry function failed after 4 attempts: gitHub Actions did not inject $ACTIONS_ID_TOKEN_REQUEST_TOKEN or $ACTIONS_ID_TOKEN_REQUEST_URL into this job. This most likely means the GitHub Actions workflow permissions are incorrect, or this job is being run from a fork. For more information, please see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
```
=> ci(container): disable gloud auth on PRs

pkg/metadata/erlang.go, pkg/metadata/nodejs.go, pkg/metadata/ruby.go, pkg/metadata/runtime.go, pkg/profiler/cpu/bpf/maps/maps.go, pkg/runtime/compiler.go, pkg/runtime/compiler_test.go, pkg/runtime/erlang/erlang.go, pkg/runtime/erlang/erlang_test.go, pkg/runtime/nodejs/nodejs.go, pkg/runtime/python/python.go, pkg/runtime/ruby/ruby.go, pkg/runtime/runtime.go, pkg/stack/unwind/executable.go
Erlang unwinding was broken.
Detect whether a process is an erlang process and then force frame pointer unwinding as erlang is compiled by default with frame pointers.
Check the executable of the process to contain erlang-specific scheduling strings.
Added unit tests and tested on the parca-demo erlang example.
=> *: Use fp unwinding for erlang and add erlang metadata

pkg/objectfile/object_file.go, pkg/objectfile/pool.go, pkg/objectfile/pool_test.go
In the worst case, determining the build id can be very expensive, as we need to hash the .text section. Determining the mount namespace id is significantly cheaper and with mount namespace id, modtime and path we still have a key that is highly stable for the properties that we need it for.
We have been seeing a lot of text section hashing in CPU profiling data of the agent in customer environments.
Use a cheaper to determine cache key.
Instead of requiring to determine the build id of an object file for its cache key, we use the combination of the processes' mount namespace id, path and mod time.
Old and new unit tests passing and ran for a bit while performing some high process churn loops in bash.
=> pkg/objectfile: Use mount namespace id in cache key instead of build id

pkg/profiler/cpu/bpf/maps/maps.go
Decrease upper number of unwind shards from 50 to 30, saving 70 MB from the locked kernel memory in BPF maps.
We don't need as many shards as we now remove redundant unwind information. After running many tests we've realised that the number was too high, most of the time we don't need a number this high.
See https://github.com/parca-dev/parca-agent/pull/2081.
If needed, in the future, we could make value customisable
Test Plan
=========
**Before**
```
parca_agent_bpf_map_max_entries{bpf_map_name="unwind_tables"} 50
parca_agent_bpf_map_memlock{bpf_map_name="unwind_tables"} 2.17005808e+08 <= 217 MB
parca_agent_bpf_map_value_size{bpf_map_name="unwind_tables"} 3.5e+06
```
**After**
```
parca_agent_bpf_map_max_entries{bpf_map_name="unwind_tables"} 30 …
```
=> Decrease upper number of unwind shards

bpf/unwinders/native.bpf.c, pkg/profiler/cpu/bpf/maps/maps.go, pkg/stack/unwind/maps.go
This commit increases the maximum mappings a process without FP can have. This limitation affected a small number of users, but it was still a blocker for some.
Additionally, rather than a linear search, we switch to using binary search on the mappings as otherwise it's too many instructions for the BPF verifier to check.
Test Plan
=========
```
=== RUN   TestCPUProfilerWorks/mixed_mode_unwinding
=== RUN   TestCPUProfilerWorks/unwinder_metrics_work
--- PASS: TestCPUProfilerWorks (20.79s)
--- PASS: TestCPUProfilerWorks/dwarf_unwinding (0.08s)
--- PASS: TestCPUProfilerWorks/fp_unwinding (0.67s)
--- PASS: TestCPUProfilerWorks/mixed_mode_unwinding (0.04s)
--- PASS: TestCPUProfilerWorks/unwinder_metrics_work (0.00s)
PASS
ok      github.com/parca-dev/parca-agent/test/integration       20.810s …
```
=> unwinder/native: Increase size of mappings

.gitmodules, Makefile, devbox.json, devbox.lock
This PR compiles dependencies, using [Zig Build System](https://ziglang.org/learn/build-system).
As of now, it doesn't address cross-compilation concerns.
- It uses `musl` and statically links everything. 
- It reduces build time dependecies.
=> New Build Pipeline: Use Zig as compiler

pkg/agent/batch_remote_write_client.go
This metric helps to figure out how much each agent is sending in raw profile bytes to the remote store across an entire fleet of agents. 
Adding a Prometheus counter.
For each successfully sent batch we sum up all the bytes of raw profiles and add it to the `parca_agent_batch_writer_bytes_total` counter. 
It allows for queries to figure out how many bytes each agent sends with a query like:
```
sum by(pod) (rate(parca_agent_batch_writer_bytes_total{job="parca-agent"}[5m]))
```
We do the same in our cloud backend.
Run the agent and check out the metric via Prometheus.
=> Add counter metric for total bytes sent to remote store

bpf/unwinders/native.bpf.c, bpf/unwinders/shared.h, pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/bpf/programs/programs.go, pkg/profiler/cpu/cpu.go, pkg/stack/unwind/compact_unwind_table.go
Before this commit we either used frame pointers or DWARF-derived unwind
information to unwind a process. We first attempt to unwind using frame
pointers and if it looks like it worked (we can't be sure about this,
see comments for more details) we aggregate the sample, otherwise we ask
userspace to write unwind information, if present. We have to exceptions
for this case, we never generated unwind info for v8-based apps [0] nor
for Go-based apps [1].
This commit enables per code region switching of unwinders, what this
means in practice is that it will allow us to unwind Go or V8
applications, that should have frame pointers in the majority of their
code using the FP unwinder, but switch to the DWARF-derived unwinder for
part of the code that do not have them, such as for native …
=> unwinder/native: Per code region unwinder selection 

pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/cpu.go
1. I noticed `mappingInfoSizeBytes` is off by `0x10` which may lead to reading little bit of garbage out of bounds of the allocation.
2. Buffer growing in various places seems incorrect - it should not take pointers
https://go.dev/play/p/wSGZw-SAocA
=> fix: bpf struct sizes fixes

bpf/unwinders/native.bpf.c, pkg/profiler/cpu/bpf/metrics/collector.go
Trying to understand why a busy computer isn't generating many samples
=> Add metrics to track number and type of bpf program early exits

cmd/parca-agent/main.go, go.mod, go.sum, pkg/cpuinfo/cpu.go, pkg/profiler/cpu/cpu.go
`runtime.NumCPU()` does not report the present/available CPUs it reports the schedulable ones.
Read available CPUs from sysfs.
Using the [`numcpus`](https://github.com/tklauser/numcpus) package.
Tested locally and it works, and added a metric to report the detected number as well.
=> Use OS num CPUs instead of runtime schedulable ones

.github/workflows/pre-commit.yml, .github/workflows/test-integration-amd64.yml, .github/workflows/test-integration-arm64.yml, .github/workflows/test.yml, bpf/unwinders/native.bpf.c, bpf/unwinders/pyperf.bpf.c, bpf/unwinders/pyperf.h, bpf/unwinders/rbperf.bpf.c, bpf/unwinders/rbperf.h, cmd/parca-agent/main.go, go.mod, go.sum, pkg/agent/preflight_checks.go, pkg/contained/contained.go, pkg/kernel/kconfig.go, pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/cpu.go, pkg/profiler/rbperf/headers.go, test/integration/integration.go, test/integration/native/native_test.go, test/integration/python/python_test.go, test/integration/ruby/ruby_test.go
- Update runtime-data
- Adds arm64 integration tests
- Attempts to add namespace runners for integration tests (vanilla runners are containers, and it doesn't support our agent use case). We will find another way with namespace labs people
- Refactors preflight checks and make sure they ran for the integration tests as well
- Fixes `setUnwindTable` error handling
- Shares the `modcache` with sudo test runners
=> Add initial Ruby ARM64 support

.github/workflows/test-integration-amd64.yml, .github/workflows/test-integration-arm64.yml, go.mod, go.sum, pkg/runtime/python/python.go, pkg/runtime/python/python_test.go, test/integration/python/python_test.go, test/integration/ruby/ruby_test.go
- Use new initial state API
- Use more precise label matches 05d3b97af3d0d759c35e24d7387fd2b78ecf0800
=> python: Use new initial state API from runtime-data

.github/workflows/test-integration-amd64.yml, .github/workflows/test-integration-arm64.yml, go.mod, go.sum, internal/dwarf/frame/table.go, pkg/runtime/elf_symbols_test.go, pkg/runtime/erlang/erlang_test.go, test/integration/integration.go, test/integration/python/python_test.go, test/integration/ruby/ruby_test.go
All the Python integration tests and a single case of Ruby (3.2.1) integration tests fail on ARM64.
The failures are because of a bug in DWARF-based unwinder on ARM64 (which we are currently working on). Hence, I will mark the ARM64 integration tests as not mandatory for our CI/CD.
But I will keep the tests running.
=> Run integration tests on namespace runners

pkg/debuginfo/find.go, pkg/debuginfo/find_test.go
`.debug` pattern is more likely to exists compared to other candidates.
=> debuginfo: Change find order

bpf/Makefile, bpf/unwinders/go_traceid.h, bpf/unwinders/native.bpf.c, bpf/unwinders/pyperf.bpf.c, bpf/unwinders/shared.h, bpf/unwinders/tls.h, cmd/parca-agent/main.go, pkg/pprof/pprof.go, pkg/profile/profile.go, pkg/profiler/cpu/cpu.go
It's already possible to attach trace ids to profiling data with instrumented profilers, but it would be great if we could also create the connection between distributed tracing and profiling data with collection from eBPF. Well this is exactly that.
With the trace ID added to profiled stacks it's possible to view all profiling data of a request in one flamegraph/iciclegraph, which makes it much easier to identify bottlenecks of a request than having to view it on a per process basis.
Attempt to read the `otel.traceid` goroutine label from Go processes. Plus a flag to enable it, by default this will be disabled as it significantly increases the amount of data produced.
Go processes store the current goroutine in thread local store. From there this reads the `g` (aka goroutine) struct, …
=> Add ability to read trace id from goroutine labels of Go processes

bpf/unwinders/go_traceid.h
Go 1.22 is the most recent release, so let's start with supporting that.
=> bpf/unwinders/go_traceid.h: Fix Go 1.22 labels offset

bpf/unwinders/native.bpf.c, internal/dwarf/frame/entries.go, internal/dwarf/frame/entries_test.go, internal/dwarf/frame/parser.go, internal/dwarf/frame/parser_test.go, internal/dwarf/frame/table.go, pkg/profiler/cpu/bpf/maps/maps.go, pkg/stack/unwind/unwind_table.go
I was trying to run parca-agent on my new work laptop which has Fedora 39 in a VM on a mac host, i.e. aarch64. I encountered various problems trying to do so, which this PR fixes.
Probably the reason nobody has fixed this before is that Fedora is building their OS using some special compiler flags for security hardening.
Note that this PR contains two logically distinct changes in separate commits (plus one commit for a minor logging fix).
Please see the individual commit messages for details.
Please see the individual commit messages for details.
parca-agent works on my machine now and generates reasonable-looking output.
=> Various fixes for aarch64

cmd/parca-agent/main.go, go.mod, pkg/cpuinfo/cpu.go, pkg/profiler/cpu/cpu.go, test/integration/integration.go
Previously we counted the number of present CPUs, e.g. n, and then turned on all CPUs from 0 to n-1 inclusive.
This has two defects:
1. It counts present CPUs, not online CPUs, whereas we don't want to attempt to profile an offline-but-present CPU.
2. It doesn't account for the possiblity that there can be gaps in the set of CPUs; e.g., the ranges might be 0-11,13-15 if cpu 12 is offline.
numcpus doesn't have a public API to get the set of online CPUs, so let's implement it ourselves (based on reading numcpus internal code).
Fixes https://github.com/parca-dev/parca-agent/issues/2639
`sudo chcpu -d 12 && sudo dist/parca-agent --log-level=debug` and manually verify that all CPUs except 12 are profiled. Before this would exit with an error.
=> Only attempt to profile online CPUs

cmd/eh-frame/main.go, internal/dwarf/frame/entries.go, pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/bpf/maps/maps_test.go, pkg/stack/unwind/compact_unwind_table.go, pkg/stack/unwind/compact_unwind_table_test.go
When constructing unwind tables, we add a synthetic entry marking the end of functions. This serves to allow the unwinder to detect program counters that fall between two functions. We only insert this synthetic row if it's possible to give it a program counter that doesn't overlap with anything else; that is, if there is a gap between the end of the function in question and the beginning of the next.
It's fine to omit the synthetic entries in the case where there is no gap, because in those cases, there isn't any way the PC can lie between to functions.
However, currently we _also_ use the synthetic entries for another purpose: determining where it's okay to break the unwind table into shards (as it's not acceptable for a function to cross a shard boundary). This is imprecise, because …
=> Fix function end detection

bpf/unwinders/native.bpf.c, bpf/unwinders/rbperf.h, cmd/parca-agent/main.go, pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/cpu.go, pkg/profiler/noop.go, pkg/profiler/profiler.go, pkg/template/statuspage.html, pkg/template/template.go
Each time we return from the eBPF program without a stack, bump a counter describing the reason for doing so. In user space, every time through the profiling loop, slurp these counters and surface them in the status page.
My hope is that this will be a first step towards helping us debug why some processes are not being unwound in some user environments.
We are repeatedly hearing from users that some processes are not being profiled in various situations and they don't know why. It's a bit hard to figure this out from just the `/metrics` output, because that is not broken down per process.
Tested by looking at the status page locally
=> Surface unwind failure reasons in status page

go.mod, go.sum
Include https://github.com/xyproto/ainur/commit/56a434f6d3a1f291861c8604b3bbe01ef7df63d1, which prevents misdetection of Go compiler version, which was causing unwinding to fail in some cases.
Tested elfinfo locally with this version of ainur
=> Bump Ainur to fix Go version misdetection

pkg/profiler/cpu/bpf/maps/maps.go
Every now and then we get reports about a user's process having too many mappings. As is we have to riddle about how many they have, when the error could just say it.
Include the number of mappings found in the error message.
Add it to the error message.
No testing, it compiles.
=> pkg/profiler/cpu/bpf/maps: Improve too many mappings error message

pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/metrics.go
When there are errors in processing `prefetch` events, the goroutine that processes them would exit silently. If this happened to all the workers, the entire agent would seize up as no more events could be processed.
This commit fixes that behavior.
It's easy to reproduce this if I run something that creates a lot of short-lived processes (e.g. C/C++/Rust compilation). The agent eventually gets into a permanently broken state.
=> Fix bug where event processors exit on error

pkg/profiler/cpu/cpu.go
We should only log an error if there is really an error...
=> Oops, don't log unconditionally

pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/bpf/maps/maps_test.go
If the PC of the "end-of-function" marker was exactly one greater than the PC of the last real table entry, and if the unwind entries of the function (including the end-of-function marker) were too big to fit in the current chunk also by exactly one, then we would erroneously take the entire function _except_ the marker, and start the next chunk with the marker. This commit fixes that defect.
Added a test for this case to maps_test.go
=> Fix off-by-one error in chunk splitting

bpf/unwinders/native.bpf.c, cmd/parca-agent/main.go, pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/bpf/metrics/collector.go, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/metrics.go
If a page is not mapped in a process, `bpf_probe_read_user` will not be able to read it (even if the page is resident, so reading would have only caused a minor fault).
In this case, instead of giving up, we can ask the agent to fault it into the process by reading /proc/<pid>/mem at the specified offset.
To test, compile the following program with `-O0` and attempt to profile it:
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
void x(uint64_t orig_page) {
uint64_t this_page = ((uint64_t)(&orig_page) >> 12);
if (this_page != orig_page) {
pid_t pid = fork();
if (pid)
printf("Forked child pid: %d\n", pid);
else
for (;;)
;
} else
x(orig_page);
}
int main(int argc, char *argv[]) {
x((uint64_t)(&argc) >> 12);
}
This program does the following:
1. Recurses until …
=> Add "request read" event

Makefile
This makes the various `make` targets requiring `sudo` work better for Guix-derived development environments, because it ensures that the root shell in which they're executed is using the correct versions of all the development tools, and has the correct environment variables set.
I've been using this patch locally for several weeks. Normally I wouldn't try to impose something that only benefits me on everyone else, but since this should have no effect on "typical" dev environments that just use the system git/gcc/etc., I hope people will be okay with it.
=> Makefile fixes for guix

pkg/profiler/cpu/bpf/maps/maps.go
The original intent of this code seems to be ignoring expected errors (no FDEs found), but it was actually ignoring all errors.
=> Don't swallow errors from GenerateCompactUnwindTable

.github/workflows/test-integration-amd64.yml
The namespace cloud runners are nice, but a little expensive (compared to free).
=> Run amd64 integration tests on public github actions runners

go.mod, go.sum
xref: https://github.com/parca-dev/runtime-data/pull/59
=> chore: Upgrade to the latest version of runtime-data to sync Python versions

pkg/stack/unwind/unwind_table.go
We always use `elf.NewFile` to open elf files, so closing them is always a no-op.
=> remove no-op Close statement

bpf/unwinders/native.bpf.c
See comments, and mailing list thread linked therein, for details. Before this change, recent kernels (6.8 and later) cannot verify the native unwinder, because improvements in the precision of register bounds tracking cause an explosion in state space resulting in exceeding the limit of 1 million instructions processed per load.
This commit works around that issue, as the comment in the code explains.
=> Fix unwinder loading on 6.8 kernels

bpf/unwinders/pyperf.bpf.c
In high PID churn environments we can quickly exceed 4096 PIDs, which currently is a hard limit for the agent. This both changes the map type to be an LRU so newer processes get the same chance of being profiled as old processes as well as increase the number of active python processes to 16384.
Each map entry is 26 bytes, so the total map size is around 450kb after this change.
Having this be an LRU is safe because it gets refreshed with all other process information:
* https://github.com/parca-dev/parca-agent/blob/29d408cd1f9e40c6f63524415cab462fd51cdab2/pkg/profiler/cpu/cpu.go#L523
* https://github.com/parca-dev/parca-agent/blob/29d408cd1f9e40c6f63524415cab462fd51cdab2/pkg/profiler/cpu/cpu.go#L655
* https://github.com/parca-dev/parca-agent/blob/29d408cd1f9e40c6f63524415cab462fd51cdab2/p …
=> bpf/unwinders/pyperf: Use an LRU map and increase the size

bpf/unwinders/native.bpf.c, bpf/unwinders/shared.h
In the leaf frame on ARM, we read the return address directly from x30. But this is wrong during syscalls, where we need to read it from the user task state, like we do for all the other registers during initial startup.
To test, run this program, which spins with high CPU in kernel mode:
```c
// kernspin.c
#include <unistd.h>
int main() {
while (1) {
(void)getpid();  // Repeatedly call getpid to consume CPU in kernel mode
}
return 0;
}
```
=> Properly get return address for leaf frames on ARM during syscalls

pkg/buildid/elf.go
Distros like Ubuntu build Go binaries with GNU build ID sections, and that's how the debuginfo is supposed to be obtained from debuginfod servers, so whenever available, a GNU build ID should always take precedence.
=> Fix build ID precedence

pkg/runtime/version.go
We were looking for the .bss section by parsing the ELF file and getting its address. Unfortunately, we used the `Offset` field instead, which points to a section's file offset rather than its location in memory. These can be the same, but don't have to be.
This was causing python version detection to break in at least some cases.
With this change, I am able to profile Python programs run from the python-test:3.7.17-slim container, which didn't work before.
=> Fix Python version detection

cmd/parca-agent/main.go, pkg/metadata/process.go, test/integration/integration.go, test/integration/native/native_test.go
Add an extra label for distinguishing processes, especially for java processes where the `comm`s are the same.
Add a procfs label cmdline from `/proc/[pid]/cmdline`
The code is short and self-explanatory.
See the modified integration test.
=> feat: add procfs cmdline

bpf/unwinders/native.bpf.c
We already record the leaf frame in `set_initial_state`, so we don't need to record it again during the main unwinding loop.
The FP unwinder handles this by recording the frame that was reached in each iteration of the loop, whereas the DWARF unwinder records the frame from the _previous_ iteration of the loop. This PR changes the DWARF unwinder to match the behavior of the FP unwinder, fixing the issue.
FYI @metalmatze
=> fix duplicated leaf frame for dwarf unwinding

bpf/unwinders/native.bpf.c
For some reason, the verifier on 5.4 doesn't like reading `index` here, and after trying various tricks I couldn't get it to work.
This extra logging info was added recently, so I don't think it's too big of a deal to just revert it.
=> fix verification on 5.4

bpf/unwinders/basic_types.h, bpf/unwinders/common.h, bpf/unwinders/hash.h, bpf/unwinders/native.bpf.c, cmd/parca-agent/main.go, pkg/pprof/pprof.go, pkg/profile/profile.go, pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/bpf/programs/programs.go, pkg/profiler/cpu/cpu.go, pkg/profiler/profiler.go
Instead of giving up when a native stack is too deep, we add a synthetic error from (`<truncated>`)
This has two benefits:
1. It lets the user see something instead of nothing for native frames. If they are most interested in the frames near the leaf, their profile will still be useful.
2. It lets us continue to unwind the interpreted stack in case we are running in a python or ruby program.
=> add the stack anyway in the case of truncation for native frames.

pkg/profiler/cpu/cpu.go
If unwind info is requested for the same PID multiple times, there's no reason to repeatedly attempt to extract it, so let's just deduplicate them here.
=> Deduplicate list of PIDs in processEventBatcher

.github/workflows/container.yml, .github/workflows/kerneltest.yml, .github/workflows/release.yml, .github/workflows/snap.yml
The --debug flag has been deprecated for some time and the --verbose flag does the same thing.
=> Use --verbose instead of --debug

bpf/unwinders/native.bpf.c
We should be doing -1 in the agent everywhere, and _not_ correcting for it on the backend. This was missed when we made that change.
Note that we're already applying -1 for the actual unwinding, but instead using the raw address when reporting the frame. This commit fixes that.
=> ra-1 fix for FP unwinding

bpf/Makefile, bpf/unwinders/common.h, bpf/unwinders/hash.h, bpf/unwinders/jvm.bpf.c, bpf/unwinders/native.bpf.c, bpf/unwinders/pyperf.bpf.c, bpf/unwinders/shared.h, bpf/unwinders/tls.h
This reverts commit cce2bd4700764fe242e44a30ee1bda0ac55eec4a.
Instead use the bpf_perf_prog_read_value trick for all large memzeros
=> Revert "memset the entire unwind_state to make sure no"

bpf/unwinders/common.h, bpf/unwinders/native.bpf.c, bpf/unwinders/pyperf.bpf.c, bpf/unwinders/rbperf.bpf.c, pkg/pprof/pprof.go, pkg/process/info.go, pkg/profile/profile.go, pkg/profiler/cpu/bpf/common_headers.go, pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/bpf/programs/programs.go, pkg/profiler/cpu/cpu.go
The main benefit here is getting line numbers from the errors, there is roughly a couple dozen error sites so having line numbers is nice.  The symbol "class" is the error message, a little clunky but works.  Additionally we add the samples from exitted processes now instead of throwing them away.
=> Remove synthetic unwinder error frames from agent and instead generate them in the unwinder with more context

bpf/Makefile, bpf/unwinders/common.h, bpf/unwinders/go_runtime.h, bpf/unwinders/hash.h, bpf/unwinders/native.bpf.c, bpf/unwinders/shared.h, cmd/parca-agent/main.go, pkg/pprof/pprof.go, pkg/profile/profile.go, pkg/profiler/cpu/bpf/maps/maps.go, pkg/profiler/cpu/cpu.go
This causes the agent to collect arbitrary Go trace IDs, not just `otel.traceid`.
The maximum size of keys and values is 64, and the maximum number of custom labels is 16. The maximum number of unique sets of custom labels is 1000, which we store in a map by their hash. Thus the total increase in memory usage for the native unwinder is ~2MB.
=> Collect custom labels

bpf/unwinders/common.h, bpf/unwinders/go_runtime.h
Rewrite a problematic section of code in assembly language to force the verifier to accept our program.
Otherwise, clang does something with this code (on x86) that is too clever for the verifier to understand.
=> fix x86 verification issues with custom labels

bpf/unwinders/go_runtime.h, bpf/unwinders/native.bpf.c, bpf/unwinders/shared.h
If we are in kernel code, the registers will have the kernel values of various registers, rather than the user-mode ones. We need to get x28 (the current goroutine register) at the beginning of unwinding the same way we do for other registers.
=> fix wrong computation of current goroutine in kernel code on arm

pkg/process/info.go
If this happens, it's a real issue that can break a lot of functionality, so we want to see it in the logs
=> Increase warning level when failing to fetch unwinder info

pkg/runtime/golang/golang.go
Executable containers need to be read through their mount namespace
=> Fix golang runtime detection for containers

.github/workflows/build.yml, snap/README.md, snap/hooks/configure, snap/local/parca-agent-wrapper, snap/snapcraft.yaml
This PR reintroduces the snap package, and the test/release workflow.
Unfortunately, we cannot use the plain `goreleaser` setup for building/releasing the snap, as the project is currently using a Goreleaser Docker image, which is unable to run `snapcraft`.
That said, it makes this job slightly easier, as much of what was in place before will still work. There are a couple of places where we might need to tweak artifact paths and suchlike, but otherwise this should work.
@brancz - at the moment I've tagged on the snap build, and test, and release into one workflow to avoid too much duplication, but we can adjust if you'd prefer.
=> build: reintroduce snap packaging, test, and release flows

README.md, go.mod, go.sum, reporter/metadata/process.go, reporter/parca_reporter.go
Bump to our fork of opentelemetry-ebpf-profiler that supports thread IDs, and add the thread ID as a label.
Previously we were just getting the `comm` of the first thread we saw a sample for and saving that as the entire process's `comm`. This PR saves that as `thread_name` instead and gets the main thread's comm (i.e. process name) from procfs, saving that as `comm` instead.
=> Support TID

reporter/metadata/containermetadata.go
It is not necessarily true that the items in ContainerStatuses are in the same order as those in Spec.Containers, so the old logic was wrong.
container names _are_ unique within a pod, so we can find the container in the spec for a given ID based on its name.
=> Search for k8s containers by name, not position in array.

.github/workflows/build.yml, .goreleaser.yml
Version strips the "v" prefix, which we want to be in the container image tag.
=> Always use git tag for container image

Makefile, snap/snapcraft.yaml
The primary reason for this PR is to address the [failing snap release job](https://github.com/parca-dev/parca-agent/actions/runs/10943881277/job/30384811867).
This job fails because there is no `arm64` build to upload, despite the build artifacts being fetched from the previous steps in the process.
Further investigation showed that the `snapcraft pack` for the `arm64` snap [finished abruptly](https://github.com/parca-dev/parca-agent/actions/runs/10943881277/job/30384611839#step:6:48) having not actually generated an artefact. This turns out to be a [known bug](https://github.com/canonical/craft-application/issues/225), which should be addressed in the next snapcraft release. In the mean time, we can work around by just explicitly stating that the `arm64` snap can be `built-on` an …
=> fix(snap): ensure arm64 build can be performed from an amd64 machine

flags/flags.go, main.go
Currently we fail to run if tracepoints can't be set on various sub-events of /sys/kernel/debug/tracing/events/syscalls/ . Currently these are used to detect various offsets when BTF is not available.
Since some kernel configurations don't have syscall tracepoints, but _do_ have BTF info, things might still work if we just keep running here.
I have confirmed that with this patch, the agent starts up and seems to work normally on a kernel without CONFIG_FTRACE_SYSCALLS, which fails without this patch.
=> Allow running without syscall tracepoints

reporter/metadata/containermetadata.go
Some users are reporting that container name isn't always showing up. Let's give them a fighting chance to see what's wrong by bumping the priority of this error.
=> Warn on failure to get container metadata

go.mod, go.sum
Mainly to pick up https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/231 which fixes a bug encountered by Materialize.
=> bump otel fork

reporter/parca_reporter.go
The way the if statement was written, if there is an io.EOF error, then we still first try reading the response object, however, in the io.EOF case it's null, therefore the if statement needs to be swapped around so it would never try to read something on the nil pointer if an io.EOF error is returned.
=> reporter: Fix io.EOF handling

flags/flags.go, flags/grpc.go, go.mod, go.sum, main.go, reporter/parca_reporter.go, uploader/log_uploader.go
This patch introduces *offline mode*, a mechanism for running the agent without a network connection.
`--offline-mode-storage-path` takes a path to a directory in which data will be stored; it will be created if it does not exist. Samples and stack traces are written to a file with name `<current time>-<agent PID>.padata`. Every 10 minutes (by default), this file is rotated and compressed with zstd.
`--offline-mode-upload` causes the agent to look for these files in the path passed via `--offline-mode-storage-path`, and upload them to the remote store configured with the usual remote store options.
Note that significant parts of `log_uploader.go` -- specifically the `locationsReader` and associated functions -- were mostly copied from Parca.
=> Initial implementation of offline mode

snap/README.md, snap/hooks/configure, snap/local/parca-agent-wrapper
Enables passing a `config-file` flag to `parca-agent` snap
=> snap: expose config-file option

go.mod, go.sum, reporter/parca_reporter.go, reporter/parca_reporter_test.go
Also, re-truncate a value that the tracer
might have truncated at a byte boundary at a
rune boundary instead.
=> Validate that custom labels are utf-8.

reporter/grpc_upload_client.go, reporter/parca_reporter.go
Below is the monitor panel of the number of parca-agent goroutines before and after applying this patch.
=> Fix goroutines leak at reportDataToBackend

reporter/parca_reporter.go, reporter/parca_uploader.go
This PR improves logging readability by using actual file names instead of file IDs.
For example, the log without the PR likes
```
time="2025-08-18T11:34:27+08:00" level=info msg="Attempting to upload with file ID '022fc12e3da7592e13539c00fd038204' and build ID 'a91d7a6f22679b12e78dd91696000b56a294d9d0'"
```
and with the PR likes
```
time="2025-08-22T14:25:18+08:00" level=info msg="Attempting to upload file 'libjava.so' with build ID '32e7acc2fb70979ccffe0522a22d088a5c8e606c'"
```
=> Replace fileId with fileName in log

README.md, reporter/metadata/agent.go, reporter/metadata/containermetadata.go, reporter/metadata/process.go, reporter/metadata/system.go, reporter/parca_reporter.go
This adds docker and containerd container labels as meta labels so users can relabel them onto samples the same way as it is possible with eg. kubernetes pod labels.
=> Add docker and containerd meta labels
