parca-dev/parca-agent

CONTRIBUTING.md, README.md, cmd/parca-agent/main.go
=> *: Fix systemd misspellings

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/jsonnet.yml, .github/workflows/release.yml, Dockerfile, Dockerfile.dev, Makefile
=> Improve Github Actions

.github/workflows/release.yml
=> Trigger vercel deploy hook

.github/workflows/codeql-analysis.yml
=> Fix codeql builds

cmd/parca-agent/main.go, pkg/agent/batcher.go, pkg/agent/batcher_test.go
=> batcher: Pass logger to BatchWriteClient

Makefile, Tiltfile, deploy/Makefile, deploy/dev.jsonnet, deploy/jsonnetfile.json, deploy/jsonnetfile.lock.json, deploy/tilt/0namespace.yaml, deploy/tilt/parca-agent-clusterRole.yaml, deploy/tilt/parca-agent-clusterRoleBinding.yaml, deploy/tilt/parca-agent-daemonSet.yaml, deploy/tilt/parca-agent-podSecurityPolicy.yaml, deploy/tilt/parca-agent-role.yaml, deploy/tilt/parca-agent-roleBinding.yaml, deploy/tilt/parca-agent-serviceAccount.yaml, deploy/tilt/parca-server-configmap.yaml, deploy/tilt/parca-server-deployment.yaml, deploy/tilt/parca-server-podSecurityPolicy.yaml, deploy/tilt/parca-server-role.yaml, deploy/tilt/parca-server-roleBinding.yaml, deploy/tilt/parca-server-service.yaml, deploy/tilt/parca-server-serviceAccount.yaml, scripts/local-dev.sh
=> Tilt for local dev

cmd/parca-agent/main.go, pkg/discovery/discoverymanager.go
=> pkg/discovery: Use promauto constructors for metric types

Dockerfile, Dockerfile.dev, deploy/dev.jsonnet, deploy/tilt/parca-agent-daemonSet.yaml, pkg/debuginfo/debuginfo.go
=> *: Upgrade external tool dependencies

go.mod
We have dependencies which use Go 1.17 language features.
=> *: Update Go version in go.mod

deploy/tilt/parca-server-deployment.yaml, deploy/tilt/parca-server-role.yaml, deploy/tilt/parca-server-roleBinding.yaml, deploy/tilt/parca-server-service.yaml, deploy/tilt/parca-server-serviceAccount.yaml
=> Upgrade local env manifests

go.mod, go.sum
Fixes https://github.com/parca-dev/parca-agent/issues/213
Introduced changes in error handling causes iterator to fail prematurely https://github.com/aquasecurity/libbpfgo/pull/100
xref: https://github.com/aquasecurity/libbpfgo/issues/114
=> Downgrade libbpf-go

go.mod, go.sum
=> Upgrade to libbpf 0.6.1 and libbpfgo v0.2.4

Dockerfile, Dockerfile.dev, Makefile
* Reduce packages fetched by --no-install-recommends
* Replace cd && make with make -C
Looking into multi-arch containers, which might be a bit more tricky for this project, so I push these smaller changes early.
=> Small fixes in Makefile/Dockerfile

cmd/parca-agent/main.go, pkg/profiler/profiler.go, pkg/target/manager.go, pkg/target/profiler_pool.go
=> profiler: Expose missing profile stacks count as a prometheus metric

.github/workflows/jsonnet.yml
=> actions: Only run jsonnet task when needed

.github/workflows/build.yml, .golangci.yml, CONTRIBUTING.md, Makefile, cmd/debug-info/main.go, cmd/parca-agent/main.go, env.sh, pkg/agent/profile_listener.go, pkg/agent/write_client.go, pkg/agent/write_client_test.go, pkg/buildid/buildid.go, pkg/containerutils/containerd/containerd.go, pkg/containerutils/containerutils.go, pkg/containerutils/crio/crio.go, pkg/containerutils/docker/docker.go, pkg/debuginfo/debuginfo.go, pkg/discovery/discovery.go, pkg/discovery/discovery_manager.go, pkg/discovery/kubernetes.go, pkg/discovery/systemd.go, pkg/discovery/systemd_test.go, pkg/k8s/k8s.go, pkg/k8s/podinformer.go, pkg/ksym/ksym.go, pkg/ksym/ksym_test.go, pkg/perf/perf.go, pkg/perf/perf_test.go, pkg/profiler/profiler.go, pkg/target/manager.go, pkg/target/profiler_pool.go
* Upgrade linter
* Fix linter pointed issues
Sync with Parca
=> *: Enable revive and gofumpt linters

deploy/tilt/parca-server-deployment.yaml, deploy/tilt/parca-server-role.yaml, deploy/tilt/parca-server-roleBinding.yaml, deploy/tilt/parca-server-service.yaml, deploy/tilt/parca-server-serviceAccount.yaml
=> deploy: Version bump parca

deploy/dev.jsonnet, deploy/lib/parca-agent/parca-agent.libsonnet, deploy/main.jsonnet
=> jsonnet: Fix pod label selector config

pkg/profiler/profiler.go
=> pkg/profiler: add deregistration for counter metric

.github/workflows/container.yml, Makefile
We recently switched to using podman instead of buildah and missed to
update this.
=> .github: Fix container registry login

deploy/tilt/parca-server-deployment.yaml, deploy/tilt/parca-server-role.yaml, deploy/tilt/parca-server-roleBinding.yaml, deploy/tilt/parca-server-service.yaml, deploy/tilt/parca-server-serviceAccount.yaml, go.mod, go.sum
=> Upgrade libbpf to 7.0.0

.github/workflows/jsonnet.yml
=> Fix failing jsonnet actions

cmd/debug-info/main.go, deploy/dev.jsonnet, pkg/debuginfo/find.go, pkg/debuginfo/find_test.go
=> Fix local debuginfo file discovery

pkg/debuginfo/debuginfo.go
=> debuginfo: Fix cache configuration issue

.github/workflows/build.yml, env.sh, scripts/local-dev.sh
=> *: Upgrade golangci-lint

pkg/debuginfo/upload.go, pkg/discovery/discovery_manager.go, pkg/maps/mapping.go, pkg/maps/maps.go, pkg/objectfile/cache.go, pkg/objectfile/object_file.go, pkg/perf/perf.go, pkg/profiler/profiler.go, pkg/target/manager.go, pkg/target/profiler_pool.go
=> *: Reduce noisy logging

pkg/debuginfo/debuginfo.go, pkg/maps/maps.go, pkg/profiler/profiler.go
=> *: Refactor code for readability

Makefile, parca-agent.bpf.c
=> Change C format styling to LLVM

go.mod, go.sum, pkg/profiler/profiler.go
=> profiler/api: Conform the changes in the WriteRaw API

README.md, cmd/parca-agent/main.go
- fixes #235
- added a flag and updated README
Signed-off-by: Rohit Dandamudi <rohitdandamudi.1100@gmail.com>
=> feat: add configurable ticker duration

cmd/parca-agent/main.go, pkg/target/manager.go, pkg/target/profiler_pool.go
=> pkg/target: Add functionality for using specified sampling ratio

Makefile, go.mod, go.sum
=> go.*: Upgrade prometheus/common

deploy/tilt/parca-server-deployment.yaml, deploy/tilt/parca-server-role.yaml, deploy/tilt/parca-server-roleBinding.yaml, deploy/tilt/parca-server-service.yaml, deploy/tilt/parca-server-serviceAccount.yaml, go.mod, go.sum
=> go.*/deploy: Upgrade backoff

.github/workflows/build.yml, Makefile, parca-agent.bpf.c
Ran `make c/fmt`. Will create an issue to remember to add a CI check 😄
=> Format our C code

Dockerfile.dev
=> Dockerfile.dev: Add delve to dev container

Dockerfile, make-containers.sh
For consistency with our dev Dockerfile and to unblock https://github.com/parca-dev/parca-agent/pull/341
=> make-containers.sh: Update images to go v1.18.1

Makefile
Add ASAN build flag to use during development. This would have helped catch https://github.com/parca-dev/parca-agent/pull/367 (more info in https://github.com/parca-dev/parca-agent/issues/368#issuecomment-1105293674)
**ASAN disabled**
```
$ make
mkdir -p dist/parca-agent.bpf
cp $(find parca-agent.bpf.c dist/libbpf/usr/include/bpf 3rdparty/include -type f) dist/parca-agent.bpf
go mod tidy -compat=1.17
find dist -exec touch -t 202101010000.00 {} +
GOOS=linux GOARCH=arm64 CC=clang CGO_CFLAGS="-I /home/vagrant/work/parca-agent/dist/libbpf/usr/include" CGO_LDFLAGS="/home/vagrant/work/parca-agent/dist/libbpf/libbpf.a" go build  -trimpath -v -o dist/parca-agent ./cmd/parca-agent
find dist -exec touch -t 202101010000.00 {} +
go build  -trimpath -v -o dist/debug-info ./cmd/debug-info
```
**ASAN …
=> Makefile: add asan build flag

MAINTAINERS.md
=> Add official maintainers doc

parca-agent.bpf.c, pkg/profiler/profiler.go
=> Introduce spinlocks for counter values

.goreleaser.yml, Dockerfile, Makefile, make-containers.sh
=> Produce statically linked binaries

.dockerignore, .github/workflows/build.yml, .golangci.yml, Makefile, pkg/profiler/profiler.go
Reverts parca-dev/parca-agent#394
This feature requires a bump in the minimum required Linux version.
cc @javierhonduco  @v-thakkar @Sylfrena
=> Revert "profiler: Use BPF batch operations "

.github/workflows/container.yml, .github/workflows/release.yml, Makefile
cc @cpanato
ref: https://github.com/parca-dev/parca/pull/1039
=> Sign releases and main branch parca images with cosign

deploy/tilt/parca-server-deployment.yaml, deploy/tilt/parca-server-role.yaml, deploy/tilt/parca-server-roleBinding.yaml, deploy/tilt/parca-server-service.yaml, deploy/tilt/parca-server-serviceAccount.yaml
=> Bump Parca v0.11.0 version for local development

.github/workflows/container.yml, .github/workflows/release.yml, Makefile
xref: https://github.com/parca-dev/parca/pull/1041
=> Add crane to determine digest of the container image

.github/workflows/container.yml
similar fix applied here https://github.com/parca-dev/parca/pull/1042
/assign @kakkoyun
=> replace podman login with cosign login for quay.io

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docs.yml, .github/workflows/release.yml, Dockerfile, Dockerfile.dev, bpf/cpu-profiler/rust-toolchain.toml
Let's pin nightly and fix syntax for the --profile
flag.
=> Fix arm64 build

pkg/debuginfo/debuginfo.go
fixes: https://github.com/parca-dev/parca-agent/issues/420
When generating profiles, we might need to extract and upload the debug information present in the binaries so we can symbolise the addresses with DWARF. We do this here:
https://github.com/parca-dev/parca-agent/blob/5f8f1525173e34125a101c374191e1bd0c031b16/pkg/profiler/profiler.go#L612-L622
When profiling many processes, we might have a race condition. For example, the same executables (libc) might show up in multiple processes, and we will attempt to upload them all. 
The explanation of it is in the code comment below. The result is that we end up with corrupted debug files, which this PR fixes!
It's also a performance issue, as we are repeating lots of work (extracting binaries, attempting to send them) that unnecesarily burn …
=> debuginfo: Fix race when extracting debug info files

Dockerfile, Dockerfile.dev, make-containers.sh
* Add dynamic libraries for external commands #427 
cc @v-thakkar
=> Sync release-0.8 and main

.github/workflows/container.yml
=> CI/container: Add a check to list created images

Dockerfile, Dockerfile.dev
Related to https://github.com/parca-dev/parca-agent/issues/449#issuecomment-1150743244
=> build(deps): pin rustup version

.github/workflows/build.yml, .golangci.yml, Dockerfile, Dockerfile.dev, Makefile, Tiltfile, cmd/debug-info/main.go, cmd/parca-agent/main.go, deploy/tilt/parca-server-deployment.yaml, deploy/tilt/parca-server-role.yaml, deploy/tilt/parca-server-roleBinding.yaml, deploy/tilt/parca-server-service.yaml, deploy/tilt/parca-server-serviceAccount.yaml, env.sh, go.mod, go.sum, make-containers.sh, pkg/buildid/buildid.go, pkg/containerutils/containerutils.go, pkg/debuginfo/extract.go, pkg/elfwriter/elfwriter.go, pkg/elfwriter/elfwriter_test.go, pkg/elfwriter/options.go, pkg/k8s/k8s.go, scripts/local-dev.sh
=> debuginfo: Add pure Go ELF Writer to extract debug information

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/jsonnet.yml, .github/workflows/release.yml, Dockerfile, Dockerfile.dev, bpf/Makefile, bpf/xtask/Cargo.toml, env.sh
This basically ensures all dependencies are pinned, Renovate is able to do it in some cases, but I prefer to do it myself to make sure nothing is missed.
This also adds the "renovate" comments for the custom regex
=> chore: prepare dependencies for Renovate

RELEASE.md
Fixes #406 
cc @v-thakkar @javierhonduco @Sylfrena
=> chore: Add RELEASE.md

.github/workflows/build.yml
=> chore: Add upgradable version for golangci lint

scripts/install-minikube.sh
=> chore: Add minikube install script

.gitignore, Dockerfile.dev, Tiltfile, deploy/dev.jsonnet, scripts/local-dev.sh
The previous version was failing when used with multiple nodes.
=> chore: Improve local development script

pkg/elfwriter/elfwriter.go
Fix for https://github.com/parca-dev/parca-agent/issues/523
Let's add a unit test in another PR
=> elfwriter: Initialise c variable of type compressionInfo

deploy/Makefile, pkg/debuginfo/debuginfo.go
Premature optimizations are root of all evil
=> debuginfo/extractor: Removing pooling

Makefile, cmd/debug-info/main.go, pkg/debuginfo/debuginfo.go, pkg/debuginfo/extract.go, pkg/debuginfo/extract_test.go, pkg/elfwriter/elfwriter.go
=> debuginfo/extractor: Make sure .text section is not uploaded

.github/workflows/build.yml, .github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/jsonnet.yml
Same as parca-dev/parca#1269
Related to #509
=> ci: filter paths with a GH action

.github/workflows/build.yml, .github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/jsonnet.yml
=> ci: disable skip_after_successful_duplicate

.github/workflows/container.yml
Fixes https://github.com/parca-dev/parca-agent/runs/7249120965?check_suite_focus=true
=> ci/container: Fix cosign login

.github/workflows/container.yml, .github/workflows/release.yml
=> chore: Fix crane missing dependency

go.mod, go.sum
=> chore: Upgrade docker/distribution

Dockerfile, Makefile
=> container: Fix container binary run issue

deploy/dev.jsonnet, pkg/containerutils/containerd/containerd.go, pkg/containerutils/crio/crio.go, pkg/containerutils/docker/docker.go, pkg/k8s/k8s.go
This targets the release branch. We will merge this branch afterwards.
=> fix: Fix docker socket issue

deploy/dev.jsonnet, pkg/containerutils/containerd/containerd.go, pkg/containerutils/crio/crio.go, pkg/containerutils/docker/docker.go, pkg/k8s/k8s.go
Fix docker socket issue (#595)
=> Merge release-0.9 to main

.github/workflows/container.yml, .github/workflows/release.yml
=> chore: Fix pipeline caching issues

CONTRIBUTING.md
=> docs: Contributing fixes

.github/workflows/build.yml, .golangci.yml, env.sh
=> chore: Upgrade golangci-lint to 1.47.1

deploy/jsonnetfile.lock.json
=> chore: Update jsonnet dependencies

pkg/profiler/cpu.go
=> profiler: Minor documentation fixes

CONTRIBUTING.md, README.md, cmd/parca-agent/main.go, scripts/local-run.sh
=> docs: System-wide profiling related updates

README.md, cmd/parca-agent/main.go
```
[javierhonduco@fedora parca-agent]$ rg -- --temp-dir
[javierhonduco@fedora parca-agent]$ 
```
=> Remove deprecated tmpdir flag

cmd/parca-agent/main.go, go.mod, go.sum, pkg/metadata/compiler.go
=> metadata: Add provider for compilers

.github/CODEOWNERS, MAINTAINERS.md
=> Add codeowners

pkg/debuginfo/manager.go, pkg/objectfile/cache.go
And log / error instead in case of errors
cc @kakkoyun
=> Remove force type asserts linter exclusions

pkg/profiler/cpu/cpu.go
=> profiler/cpu: Preallocate samples slice

internal/dwarf/frame/table.go
We'll have implementation for all instructions. So
this is not needed.
=> Remove unnecessary function unknown

internal/dwarf/frame/table.go, pkg/stack/unwind/plan_table.go
Some outstanding issues:
- PCs (Locs) are wrong
- $rbp offsets are missing
- probably more 😬 
~~- Crash on libc (/lib64/libc.so.6)~~
=> WIP: eh_frame: Full table generation

internal/dwarf/frame/table.go
=> Use executeDwarfProgram

.github/workflows/container.yml
xref: https://github.com/parca-dev/parca/pull/1638
=> ci: Fix version for container builds

.github/workflows/pre-commit.yml
=> ci: fix pre-commit on main branch

docs/hacking_on_native_stack_unwinding_without_frame_pointers.md
=> .eh_frame/docs: Add eh_frame stack unwinding hacking docs

cmd/parca-agent/main.go
Fixes: #683
Signed-off-by: heylongdacoder <heylongdacoder@gmail.com>
=> cmd/parca-agent: add component pprof label

pkg/objectfile/object_file_test.go
=> pkg/objectfile: Add lint ignore for dup word

.github/workflows/pre-commit.yml
Same as parca-dev/parca#1683 and parca-dev/parca#1727
=> ci(pre-commit): run on all files when config changes

pkg/kconfig/kconfig.go
ref: https://github.com/parca-dev/parca-agent/issues/758
=> kconfig: Add tried paths to the error message

pkg/elfwriter/elfwriter.go
Fixes https://github.com/parca-dev/parca-agent/issues/848
=> Handle multiple .shstrtab sections in a file

Makefile
=> test: Re-enable profiler/tests

.gitignore, cmd/parca-agent/main.go, deploy/lib/parca-agent/parca-agent.libsonnet, pkg/kconfig/kconfig.go
Add checks for the required directories
Fixes #758
=> kconfig: Mount required directories for kubernetes config

pkg/discovery/discovery_manager.go
Signed-off-by: heylongdacoder <heylongdacoder@gmail.com>
=> pkg/discovery: fix discovery manager startProvider log mistake

pkg/profiler/cpu/cpu.go
Fixes: #702
Signed-off-by: heylongdacoder <heylongdacoder@gmail.com>
=> pkg/profiler/cpu: check if bpf program and map type are supported

cmd/parca-agent/main.go
This is how it looks after the changes.
Fixes #628
=> ui: Round time duration in Next Profile Started

Makefile, README.md, cmd/parca-agent/main.go, pkg/profiler/cpu/cpu.go, pkg/profiler/rlimit.go, scripts/local-run.sh
=> *: Add ability to set memlock rlimit

bpf/cpu/cpu.bpf.c, pkg/profiler/cpu/maps.go
The unwinder didn't handle some important cases such as when an expression has to be evaluated to find its value, or when it's been stored in another register. While we still don't handle these, let's be explicit about them and log ccordingly.
We also relied on the offset value to signify that the value did not change, this commits makes this explicit.
The size of the unwind table is the same, the previous field that stored the cfa type (`.cfa_type`, a u16) has been split in two fields with half the size (u8), `.cfa_type` and `.rbp_type`.
Tested in Minikube and CRuby without issues.
=> .eh_frame: Improve RBP handling

pkg/elfwriter/elfwriter_test.go
=> elfwriter-test: Clean the files

README.md, cmd/parca-agent/main.go, deploy/lib/parca-agent/parca-agent.libsonnet, pkg/debuginfo/manager.go, pkg/objectfile/cache.go
=> debuginfo: Make debuginfo upload cache configurable

bpf/cpu/cpu.bpf.c
In [0] `add_stacks` was modified to accept a u64 containing the tgid and pid in the form of `current_task->tgid << 32 | current_task->pid`, as the `bpf_get_current_pid_tgid` returns, but in the case of the dwarf based unwinder, only the 32 bit value containing the pid was passed
- [0]: Commit https://github.com/parca-dev/parca-agent/commit/3fba1033ce42a64bb53c206d64547dd8b3a5c283
**Before this PR**
**After this PR**
=> .eh_frame: Pass the right pidtgid to add_stacks

go.mod, pkg/debuginfo/manager.go, pkg/profiler/cpu/cpu.go
=> debuginfo: Add bounded concurrency for debuginfo uploads

deploy/lib/parca-agent/parca-agent.libsonnet
=> deploy: Remove host port

Makefile
=> make: Add a make action to build debug binaries

pkg/debuginfo/find.go, pkg/debuginfo/find_test.go
=> debuginfo/find: Add more local debug information search patterns

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/jsonnet.yml, .github/workflows/pre-commit.yml, .github/workflows/snap.yml
=> Run actions on release branches

README.md, cmd/parca-agent/main.go, pkg/debuginfo/manager.go
Supersedes https://github.com/parca-dev/parca-agent/pull/1038
=> debuginfo: Make sure uploads do not block

pkg/discovery/systemd.go
ref: https://github.com/parca-dev/parca-agent/issues/1037
=> metadata: Reduce systemd polling

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/snap.yml, Makefile
=> Pin clang version

docs/native-stack-walking/design.md, docs/native-stack-walking/hacking.md
=> docs/eh_frame: Add features and limitations doc

.github/workflows/container.yml, Makefile, deploy/e2e.jsonnet
=> ci(e2e): pass container image as artifact between jobs

.github/workflows/pre-commit.yml
Same as parca-dev/parca#2162 with adjustments discovered in parca-dev/parca#2167
=> ci(pre-commit): apply automatic fixes

.github/workflows/release.yml
Fixes #1027 
This should fix the snap release action
=> ci: fix snap build for tags

docs/security.md
This is just a sync from downstream parca-dev/docs. We have forgotten the sync script and updated it in downstream.
=> docs: Update security document

Dockerfile, Dockerfile.dev, Tiltfile, cmd/parca-agent/main.go, deploy/dev.jsonnet, deploy/lib/parca-agent/parca-agent.libsonnet
=> config: Make sure we handle errors when file path specified

pkg/profiler/cpu/cpu.go
This is a quick and dirty solution to frequent updates to unwind tables. We will introduce a better solution before the next minor release.
=> Reduce the updates for unwind tables

docs/design.md
=> Update the design doc for system-wide profiling changes

shell.nix
Now available in nixpkgs stable channel
=> chore(nix-shell): update Go to v1.19

internal/dwarf/frame/table.go
.eh_frame: Remove expensive opcode to function dispatch.
```
$ go test -v github.com/parca-dev/parca-agent/pkg/stack/unwind -bench=. -count=20
```
```
$ benchstat /tmp/old /tmp/new
name                                  old time/op    new time/op    delta
ParsingLibcDwarfUnwindInformation-12    34.2ms ±28%    26.7ms ±33%  -21.86%  (p=0.000 n=20+20)
name                                  old alloc/op   new alloc/op   delta
ParsingLibcDwarfUnwindInformation-12    32.7MB ± 0%    32.7MB ± 0%     ~     (p=0.473 n=20+20)
name                                  old allocs/op  new allocs/op  delta
ParsingLibcDwarfUnwindInformation-12      150k ± 0%      150k ± 0%     ~     (p=1.000 n=20+20)
```
=> .eh_frame: Remove expensive opcode dispatch

go.mod, go.sum
My changes https://github.com/godbus/dbus/pull/344, https://github.com/godbus/dbus/pull/347  related to https://github.com/parca-dev/parca-agent/issues/1037 were merged, so let's bring them here.
=> Reduce dbus allocs in ReadMessage path

.github/workflows/container.yml, .github/workflows/release.yml, Makefile
* Use `$(CMD_GIT)` consistently
* Do not hide errors from `git describe` (hopefully this will help identifying the error next time)
* Simplify setting `GITHUB_BRANCH_NAME` and generalize `refs/` prefix trimming
=> ci: minor fixes to Makefile

.goreleaser.yml, Makefile
https://goreleaser.com/deprecations/#archivesreplacements
Fixes https://github.com/parca-dev/parca-agent/actions/runs/3834880377/jobs/6527674431
=> goreleaser config: Fix deprecated usage

README.md, cmd/parca-agent/main.go, docs/design.md, pkg/profiler/cpu/cpu.go, pkg/profiler/pprof.go
Frederic proposed `--cpu-sampling-frequency` flag https://github.com/parca-dev/parca-agent/issues/1212.
=> profiler: Configurable profiling frequency

cmd/parca-agent/main.go
Fix https://github.com/parca-dev/parca-agent/issues/1133.
=> Exit with an error when DWARF-unwinder is enabled on ARM64

pkg/cgroup/cgroup.go, pkg/cgroup/cgroup_test.go, pkg/discovery/kubernetes.go, pkg/discovery/kubernetes/containerruntimes/containerruntimes.go, pkg/discovery/kubernetes/kubernetes.go, pkg/discovery/systemd.go, pkg/metadata/process.go, pkg/namespace/namespace.go
metadata: Fix metadata association problems concerning children processes (#1232)
https://github.com/parca-dev/parca-agent/pkgs/container/parca-agent/64443181?tag=release-0.11-0e424686
deployed to https://demo.parca.dev, running as expected.
=> Merge release v0.11.1

.github/workflows/release.yml
=> ci(release): fix "detected dubious ownership in repository"

pkg/discovery/systemd.go
=> pkg/discovery/systemd: Downgrade log if PIDNamespaceAdjacentPIDs fails

pkg/profiler/cpu/maps.go
And add more context to the assertions.
=> pkg/profiler/cpu: fix off-by-one in invariants check

pkg/profiler/cpu/bpf_metrics.go, pkg/profiler/cpu/bpf_metrics_test.go, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/metrics.go
=> pkg/profiler: export prometheus metrics for bpf maps

pkg/profiler/cpu/maps.go
As right now the kernel is copying random junk, or failing with `-EFAULT` if the memory after the buffer that's read it's not mapped.
Also moved the "mapping type" to a named constant and did some minor clean-ups.
Test Plan
=========
Run the Agent and collected profiles without any unexpected errors
```
[javierhonduco@fedora parca-agent]$ sudo bpftool prog tracelog | grep err
sshd-297843  [008] d.h2. 159527.693300: bpf_trace_printk:   [error] register 0 not valid (expected $rbp or $rsp)
sshd-297843  [007] d.h2. 159527.798559: bpf_trace_printk:   [error] register 0 not valid (expected $rbp or $rsp)
sshd-663095  [001] d.h2. 159528.009010: bpf_trace_printk:   [error] register 0 not valid (expected $rbp or $rsp)
sshd-297843  [004] d.h2. 159540.114493: bpf_trace_printk:   [error] register 0 …
```
=> pkg/profiler/cpu: reserve enough space for unwind shards buffer

go.mod, go.sum
To include https://github.com/xyproto/ainur/commit/2d16578fc6c96a674eb8bce57adccfcecbd3add4
=> deps: bump ainur to v1.3.1

go.sum
=> chore(deps): run go mod tidy

.github/workflows/build.yml, .github/workflows/container.yml, .github/workflows/release.yml, .github/workflows/snap.yml
To fix the broken CI (https://github.com/parca-dev/parca-agent/pull/1287)
=> ci: More unsafe directory fixes

pkg/debuginfo/manager.go, pkg/debuginfo/manager_test.go
I've added caching of ELF hashes as it was recommended in the TODO comment.
```
$ go test -benchmem -run=. -bench ^BenchmarkEnsureUploadedInitiateUploadError$ ./pkg/debuginfo/
BenchmarkEnsureUploadedInitiateUploadError-2   	     901	   1415440 ns/op	  422646 B/op	     613 allocs/op
BenchmarkEnsureUploadedInitiateUploadError-2   	     888	   1450389 ns/op	  455509 B/op	     618 allocs/op
```
=> pkg/debuginfo: Cache ELF hashes in ensureUploaded

pkg/debuginfo/manager.go
=> fix(debuginfo): ensure cached debuginfo path is not stale

pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go
When we run out of unwind shards, we wipe out the whole state, and reconstruct the unwind info from scratch.
This has two big problems:
- First, we aren't being very fair. The chances of the same profiled processes being profiled again is high as we iterate through procfs in order. We are only trying to make this slightly less bad in this PR. More details below.
- Second, and this is the most important bit, we want to collect enough signal from the processes once we pay the relatively costly price of generating the unwind info for them.
This commits waits up to some defined number of profiling rounds before wiping the state (this would be aking to a free() in a bump allocator).
This is not that important with the current configuration, as the likelihood of using 50 shards is not big, but …
=> .eh_frame: Ensure we give a fairer chance of being profiled

pkg/profiler/cpu/cpu.go
While the procfs library we use does everything properly, we weren't getting all the task PIDs.
As it turns out, while accessing `/proc/$TASK_PID` works, listing `/proc` won't show threads...
=> pkg/profiler/cpu: List all available threads rather than processes

bpf/cpu/cpu.bpf.c
After https://github.com/parca-dev/parca-agent/pull/1352, the verifier is failing on 5.4 with
```
2023-02-16T13:37:38.1632673Z [            ] stderr: ; u64 found_pc = unwind_table->rows[table_idx].pc;
2023-02-16T13:37:38.1636262Z [            ] stderr: 271: (67) r2 <<= 4
2023-02-16T13:37:38.1640155Z [            ] stderr: 272: (79) r1 = *(u64 *)(r10 -80)
2023-02-16T13:37:38.1646306Z [            ] stderr: 273: (0f) r1 += r2
2023-02-16T13:37:38.1650683Z [            ] stderr: last_idx 273 first_idx 270
2023-02-16T13:37:38.1656777Z [            ] stderr: regs=4 stack=0 before 272: (79) r1 = *(u64 *)(r10 -80)
2023-02-16T13:37:38.1660589Z [            ] stderr: regs=4 stack=0 before 271: (67) r2 <<= 4
2023-02-16T13:37:38.1666574Z [            ] stderr: regs=4 stack=0 before 270: (79) r2 = …
```
=> bpf: Remediate LLVM 11 codegen tripping the verifier

shell.nix
See https://github.com/parca-dev/parca-agent/issues/1359
Test Plan
=======
I would appreciate if someone that runs Nix could verify that it works 🙏
=> build/nix-shell: Use LLVM 14

.goreleaser.yml
Fixes https://github.com/parca-dev/parca-agent/issues/1386
=> Fix archive filename template

pkg/profiler/cpu/cpu.go
=> Adjust log level for "failed to list threads"

pkg/debuginfo/extract.go, pkg/elfwriter/elfwriter_test.go
see https://github.com/parca-dev/parca/pull/2491
=> pkg/debuginfo: Add plt symbol

pkg/profiler/cpu/cpu.go
=> pkg/profiler/cpu: Downgrade process name reading error

pkg/profiler/cpu/maps.go
The maximum number of processes we support is 5000. We don't clean up old processes that have already exited, not we reset the process information when the map is full.
This commit introduces a similar mechanism to what we do for the unwind information maps. We won't reset the proc info for x profile rounds to ensure we give all processes a chance of being profiled.
Test Plan
========
```patch
diff --git a/bpf/cpu/cpu.bpf.c b/bpf/cpu/cpu.bpf.c
index 3d5df24..4579332 100644
--- a/bpf/cpu/cpu.bpf.c
+++ b/bpf/cpu/cpu.bpf.c
@@ -28,7 +28,7 @@ _Static_assert(MAX_TAIL_CALLS *MAX_STACK_DEPTH_PER_PROGRAM >= MAX_STACK_DEPTH, "
// Number of items in the stack counts aggregation map.
#define MAX_STACK_COUNTS_ENTRIES 10240
// Maximum number of processes we are willing to track.
-#define MAX_PROCESSES …
```
=> pkg/profiler: Reset process information if full

README.md, cmd/parca-agent/main.go
fixes https://github.com/parca-dev/parca-agent/pull/1075
Only user facing change is `--disable-dwarf-unwinding` to `--dwarf-unwinding-disable`
=> cmd/parca-agent: Refactor flag structs

Makefile, README.md, cmd/parca-agent/main.go, pkg/symbol/symbol.go
depends: https://github.com/parca-dev/parca-agent/pull/1503
=> symbolizer: Add flag to disable JIT symbolization

pkg/cache/stats_counter.go
Instead of this
```
sum by (cache) (rate(cache_hits_total[5m]))
/
(sum by (cache) (rate(cache_miss_total[5m])) + sum by (cache) (rate(cache_hits_total[5m])))
*
100
```
We could have this
```
sum by (cache) (rate(cache_requests_total{result="miss"}[5m]))
/
(sum by (cache) (rate(cache_requests_total[5m])))
*
100
```
Thanks, @metalmatze, for pointing it out.
=> cache stats: Use CounterVec instead of Counter where possible

pkg/cache/stats_counter.go, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/maps.go
=> fix: prevent the panics when we try to retry with a different number of shards

pkg/profiler/cpu/maps.go
We received some reports with this crash running v0.17.1
```
panic: runtime error: slice bounds out of range [:3500014] with capacity 3500000
goroutine 238 [running]:
github.com/parca-dev/parca-agent/pkg/profiler.(*EfficientBuffer).Slice(...)
github.com/parca-dev/parca-agent/pkg/profiler/buffer.go:30
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*bpfMaps).setUnwindTableForMapping(0xc00052d200, 0xa0?, 0xc00b815c38?, 0xc003a6b380)
github.com/parca-dev/parca-agent/pkg/profiler/cpu/maps.go:1057 +0x20ae
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*bpfMaps).addUnwindTableForProcess(0xc00052d200, 0xe03, {0x0, 0x0, 0x0}, 0x1)
github.com/parca-dev/parca-agent/pkg/profiler/cpu/maps.go:575 +0x4c5
```
I managed to reproduce this error, and found that another issue that could occasionally …
=> Fix race in unwind information state

Makefile
build: Pass sanitizers in debug build
=> build: Pass sanitizers in debug build

pkg/profiler/cpu/cpu.go
cpu.go: Show error if there's an error loading the BPF code
CI
=> cpu.go: Show error if there's an error loading the BPF code

deploy/kube-prometheus/parca.jsonnet, scripts/local-observability/docker-compose.yaml
Co-authored-by: Matthias Loibl <mail@matthiasloibl.com>
=> Enable native histograms for local promethei

deploy/dev.jsonnet, deploy/lib/parca-agent/parca-agent.libsonnet, pkg/debuginfo/manager.go
=> debuginfo/manager: Exclude the time to wait for goroutines turn

go.mod, go.sum, pkg/process/info.go, pkg/profiler/cpu/cpu.go
`sync.Map` stood out on the profiles because it's used in the hot path. 
https://github.com/kakkoyun/concurrent-hashmap-bench#results
```
name \ time/op                results/bench-sync.txt  delta       note               results/bench-xsync.txt  delta   note               results/bench-haxmap.txt  delta       note               results/bench-cornelk.txt  delta       note
MapStoreRand                            59.5µs +- 2%    +329.31%  (p=0.000 n=19+20)             13.9µs +- 1%    Best                                 24.1µs +- 2%     +73.96%  (p=0.000 n=19+20)               24.2µs +- 2%     +74.45%  (p=0.000 n=19+20)
MapStoreRand-2                          28.4µs +- 2%    +159.59%  (p=0.000 n=20+20)             11.0µs +-27%    Best …
```
=> Use puzpuzpuz/xsync instead of sync.Map

README.md, cmd/parca-agent/main.go, pkg/grpc/conn.go
=> Add a flag to configure RPC unary timeout

README.md, cmd/parca-agent/main.go, pkg/debuginfo/find_test.go, pkg/debuginfo/manager_test.go, pkg/objectfile/object_file_test.go, pkg/objectfile/pool.go, pkg/process/maps_test.go, test/integration/profiler_test.go
=> Add a flag to control object file pool size

test/integration/profiler_test.go
Test Plan
=======
Added a regression test.
=> tests: anyStackContains should evaluate every stack

.goreleaser.yml
=> Make archive names linux uname -m compatible

pkg/pprof/pprof.go
These changes are supposed to be part of #1837 😅
=> Fix: Make sure thread name is cached

pkg/stack/unwind/executable.go
If a binary has no symbols then this caused a bunch of errors potentially not generating unwind tables.
=> pkg/stack/unwind: Ignore no symbols present for nodejs check

MAINTAINERS.md
Today is my last day at Polar Signals. As I don't plan to be active in the `parca-agent` project after that, remove myself as a maintainer. :)
=> Maintainers: Remove Vaishali from the maintainers list

kerneltest/vmtest.sh
Update kernels
Test Plan
=======
CI
=> Add 6.1 kernel

go.mod, go.sum, pkg/convert/jfr.go
huge improvement:
https://github.com/grafana/jfr-parser/releases/tag/v0.7.0
=> bump github.com/pyroscope-io/jfr-parser from v0.6.0 to v0.7.0

pkg/metadata/java.go, pkg/metadata/java_test.go
add jak label
exec java -version.
use nsenter to fix pod situation.
=> pkg/metadata: provide jdk label

test/integration/profiler_test.go
Exclude known 3rd party offenders.
Test Plan
=======
CI
=> test/integration: Ensure we don't leak goroutines

pkg/profiler/cpu/maps.go
=> pkg/profiler: Remove unused function

pkg/profiler/cpu/bpf/maps/maps.go
=> Use right map name

pkg/process/maps.go
We only ever care about executable mappings, never about any other kinds of mappings. Executable mappings are a small fraction of all mappings typically so this should save a significant amount of memory.
This change was made based on a customer reported heap profile: https://pprof.me/edde8e7/
=> pkg/process: Only keep executable mappings

pkg/stack/unwind/compact_unwind_table.go, pkg/stack/unwind/compact_unwind_table_test.go
During DWARF unwinding, we should first find the function where a given PC is included, and then find the actual instruction boundary. In our case, we don't represent functions and instruction boundaries separately, but we need a way to figure out if a PC is between two functions, but not included in their PC ranges. The reason for this is that we should stop unwinding at that point, as not finding unwind info for a PC indicates this.
In order to solve this in our compact unwind table representation, we were appending a synthetic row after adding every unwind row mapping every instruction from a function. This works when the next unwind row from the following function's first instruction differs from the current function's last instruction, but we were not handling this case.
In practice, …
=> Do not produce bad synthetic rows

README.md
We already have support for Ruby and Python.
=> readme: Update language support roadmap

README.md
=> readme: Remove roadmap

Makefile
=> Makefile: Unify make action naming

.github/workflows/container.yml, .github/workflows/release.yml
=> .github: Update podman container hashes

go.mod, go.sum, pkg/process/info.go, pkg/profiler/cpu/cpu.go
=> Upgrade to github.com/puzpuzpuz/xsync/v3

pkg/runtime/nodejs/nodejs.go, pkg/runtime/nodejs/nodejs_test.go
=> runtime/nodejs: Optimize .data version scans

README.md, bpf/unwinders/native.bpf.c, cmd/parca-agent/main.go, pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/cpu_test.go, test/integration/profiler_test.go
The idea is to allow users to choose the CPU tradeoff they want.
Test Plan
=========
Works on my machine! :D
=> Make the profile events rate limits adjustable

.github/workflows/container.yml, .github/workflows/release.yml
=> removed podman digests

bpf/unwinders/native.bpf.c, pkg/profiler/cpu/bpf/metrics/collector.go
This metric tracks how often the bpf program has been executed without the executing code being purely kernel code and not filtered.
This helps us debug the difference in samples that we expect and the number of samples that we are actually getting.
Add a metric to track how many times the bpf program has been run.
Add a new counter in bpf and read it from user space and expose it as a Prometheus metric.
Tested it by `curl`ing.
=> Add metric to track number of bpf program runs

Makefile, cmd/parca-agent/main.go, pkg/logger/logger.go, pkg/profiler/cpu/cpu.go
=> Fix libbpf logger for tests

go.mod
Reverts parca-dev/parca-agent#2451
=> Revert "build(deps): update module github.com/pyroscope-io/jfr-parser to v0.8.0"

.github/workflows/test-integration-arm64.yml
=> .github: Make sure links are created

bpf/unwinders/pyperf.bpf.c, go.mod, go.sum, pkg/profiler/cpu/bpf/maps/maps.go, pkg/runtime/python/interpreter.go, pkg/runtime/python/python.go, test/integration/python/python_test.go
Actual fix: https://github.com/parca-dev/runtime-data/pull/42
=> Add Python 3.13 support

bpf/unwinders/pyperf.bpf.c, bpf/unwinders/pyperf.h, go.mod, go.sum
A check that I became aware of while reading the Python interpreter traceback code.
https: // github.com/python/cpython/blob/de2a73dc4649b110351fce789de0abb14c460b97/Python/traceback.c#L980
=> python: Check frame owner

bpf/unwinders/pyperf.bpf.c
=> python: Fix broken calculation on arm64

bpf/.clang-format, bpf/Makefile, bpf/pid_namespace.bpf.c, bpf/unwinders/go_traceid.h, bpf/unwinders/jvm.bpf.c, bpf/unwinders/jvm.h, bpf/unwinders/native.bpf.c, bpf/unwinders/pyperf.bpf.c, bpf/unwinders/pyperf.h, bpf/unwinders/rbperf.bpf.c, bpf/unwinders/rbperf.h, bpf/unwinders/shared.h
=> chore: Unify C format

pkg/profiler/cpu/cpu.go, pkg/profiler/cpu/metrics.go
=> Add a bit more logging/metrics when unwind table adding fails

Makefile, pkg/ksym/ksym.go, pkg/profiler/cpu/cpu.go, test/integration/integration.go, test/integration/java/java_test.go, test/integration/native/native_test.go, test/integration/python/python_test.go, test/integration/ruby/ruby_test.go
- Fix nil pointer exception caused by unhandled error.
- Check for context cancelation after long running operations.
=> fast integration

.github/workflows/container.yml, .github/workflows/kerneltest.yml, .github/workflows/release.yml, .github/workflows/snap.yml, Makefile
**Errors:**
https://github.com/parca-dev/parca-agent/actions/runs/8704374541/job/23872912353
```text
bash: line 1: which: command not found
bash: line 1: rev-parse: command not found
bash: line 1: which: command not found
bash: line 1: show: command not found
bash: line 1: which: command not found
bash: line 1: which: command not found
bash: line 1: which: command not found
```
Caused by: https://github.com/parca-dev/parca-agent/commit/470e633e3428fddeadd1158902a47b4050bcc792
cc @gnurizen
=> chore: Fix container builds

bpf/unwinders/native.bpf.c
This was missed in 872d82a740f8ceff4fce806d4cfa8daea83e5395. We need similar logic for FP unwinding as we already added there for DWARF unwinding.
See that commit message for details about what this is.
=> Fix pointer authentication for FP-based unwinding

pkg/profiler/cpu/cpu.go
=> Log in another case where we unexpectedly fail to add unwind table

bpf/unwinders/native.bpf.c
Apparently on x86, we need to try harder to confuse the verifier about variable bounds in the binary search functions.
`main` with this diff applied is loadable on 6.8 on x86.
=> spam opaquify in more places to fix verifier issues on 6.8

pkg/stack/unwind/compact_unwind_table.go
It doesn't work, and we need more time to debug why.
=> Don't use .debug_frame info for Go binaries

bpf/unwinders/go_runtime.h, bpf/unwinders/native.bpf.c, pkg/profiler/cpu/bpf/maps/maps.go, pkg/runtime/golang/golang.go
This obsoletes https://github.com/parca-dev/parca-agent/pull/2748/
=> Get Go custom label offsets dynamically

bpf/unwinders/native.bpf.c
If we have should_use_fp_by_default set we need to honor it or we will fail to unwind go binaries with no dwarf info.
=> If we have should_use_fp_by_default set we need to honor it or we will fail to unwind go binaries with no dwarf info.

bpf/unwinders/native.bpf.c
Properly memset the entire unwind_state.  This in theory should improve our stack hit rate as uninitialized fields wont introduce noise into the hashing.  This by itself isn't fixing any bugs.
=> memset entire unwind_state

pkg/debuginfo/find_test.go, pkg/debuginfo/manager.go, pkg/objectfile/object_file_test.go, pkg/objectfile/pool.go, pkg/process/info.go
See individual commit messages for details.
=> Fix various issues with debuginfo uploading

internal/dwarf/frame/parser.go, internal/dwarf/frame/table.go, internal/dwarf/util/util.go, internal/dwarf/util/util_test.go
Return errors instead of panicking in a bunch of places.
=> Fix various panics in DWARF decoding

pkg/profiler/cpu/cpu.go
=> Fix erroneous nCustomLabels accounting

flags/grpc.go
=> Fix duplicate registration during grpc retry

.goreleaser.yml
=> Fix container image tag handling and use token configured in secrets

go.mod, go.sum, main.go
This is a port to the new agent of
https://github.com/parca-dev/parca-agent/pull/2912 .
=> Auto-limit memory

go.mod, go.sum, main.go, metrics/all.go, metrics/genschema/gen.py, metrics/metrics.json, reporter/parca_reporter.go
Fix metrics.json and run go generate
=> Fix metrics

go.mod, go.sum, main.go
- **Update go.mod to pick up node V8 arm enablement**
- **Pass VerboseLogging down to DebugTracer otel config**
=> Update to point to otel head

go.mod, go.sum
Pulls in https://github.com/parca-dev/opentelemetry-ebpf-profiler/pull/27
=> go.mod: Bump otel

snap/local/parca-agent-wrapper, snap/snapcraft.yaml
=> snap: redirect logs to a file and expose a logs `slot`

README.md, reporter/parca_reporter.go
fixes: https://github.com/parca-dev/parca-agent/issues/3028
=> Renamed cpuid into cpu

main.go
Without it one gets `traces export: the client is shutdown` in the logs.
=> Actually start tracing exporter

go.mod, go.sum, reporter/parca_reporter.go
4a01451 (HEAD -> pr635, origin/pr635) tracer: fix capacity issue (#669)
eaeb362 minor cleanups and refactoring (#670)
00c4264 Remove host.FileID from StackDeltaProvider interface (#664)
0de7377 fix(deps): update go dependencies (#667)
7dbfa2e Update local-collector.sh script (#668)
229c304 Refactor symbol caching (#635)
=> Bump fork for symbol caching refactoring
